### ISSUE TITLE
linux/einkfb.h - missing or unimplemented?

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#1]
Should I start writing one? :-)

debian-armel:~/kindlepdfviewer# make
gcc -O2 -Ilua/src -Imupdf/ -DEMULATE_EINKFB_FILE='"/tmp/displayfifo"' -DEMULATE_EINKFB_W=824 -DEMULATE_EINKFB_H=1200   -c -o kpdfview.o kpdfview.c
In file included from kpdfview.c:28:
einkfb.h:28:26: error: linux/einkfb.h: No such file or directory
make: **\* [kpdfview.o] Error 1

**Comment by hwhw** [comment]
good catch. It's from the amazon kernel sources and I included it in my toolchain. I forgot about it. Will check its licence ASAP and include it - or create a Makefile target that will download it. I'll keep the issue open until such a thing is in place.

**Comment by dpavlin** [comment]
Thanks, I already had it on disk :-) Great reader, BTW Caching pages and mupdf renderer really make it a joy.

**Comment by hwhw** [comment]
thanks. the caching was just a quick try, but it worked out veeeery well.
more on topic: I've included einkfb.h now.
