### ISSUE TITLE
Still select time out in waitForEvent

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#106]
Following is my crash.log for going into screen saver after a period of time:

```
lua config error: ./unireader.lua:931: Waiting for input failed: 4
```

It is strange that the NULL argument is not blocking the select system call forever. Also I don't understand why there is no select time out when running kpv in ssh (even with previous version that does not pass NULL to select).

**Comment by hwhw** [comment]
I guess the energy management on the kindle is tampering with open input file descriptors or sending signals to our process. Error 4 is EINTR (according to <asm-generic/errno-base.h>), so the system call got interrupted.

While not a really nice solution, I guess for now we can get away by catching errors from input.waitForEvent() and just retrying.

**Comment by hwhw** [comment]
Hopefully, 57d769e0ae06cdfa8fe9fefa7fab69c25c42baab fixes this for now.
