### ISSUE TITLE
Widget framework

### ISSUE THREAD

**Issue by hwhw** [koreader/kindlepdfviewer#112]
Hi,

to allow for easily creating Dialogs and Menus, I have started a Widget framework.
It's this commit: b6d75b84ecb315b9df15312e0f876bc0d571c56d

The commit message contains example code.

I think I like to migrate other dialogs over to use a Widget based interface when release is done.

I plan to add an implementation for message boxes and similar stuff.

The nice thing about it is that it can do alignment and size calculations.

Also, I added image handling. I reused mupdf code for that. It's commit 38afb59b3f5cf4e28c2afc95c13be5fd5222a28c
It is already integrated into the Widget framework so that there are now Text and Image widgets.

**Comment by hwhw** [comment]
An example is the creation of the InfoMessage dialog. It is in dialog.lua, and a first use case is the error reporting when opening a document fails (in reader.lua).

**Comment by houqp** [comment]
OMG, I love this one. I wish there is a '+1' button on github :P

**Comment by dpavlin** [comment]
@hwhw +1 this is great

**Comment by dpavlin** [comment]
I tried to add message to filesearcher and failed.

```
diff --git a/filesearcher.lua b/filesearcher.lua
index c042602..e8fcc45 100644
--- a/filesearcher.lua
+++ b/filesearcher.lua
@@ -2,6 +2,7 @@ require "rendertext"
 require "keys"
 require "graphics"
 require "font"
+require "dialog"

 FileSearcher = {
        -- title height
@@ -22,6 +23,7 @@ FileSearcher = {
 }

 function FileSearcher:readDir()
+       InfoMessage:show("Searching")
+       fb:refresh(0)
        self.dirs = {self.path}
        self.files = {}
        while #self.dirs ~= 0 do
```

And when I run it:

```
Program received signal SIGSEGV, Segmentation fault.
0x08063fb2 in fz_lock (lock=0, ctx=<optimized out>) at fitz/fitz.h:388
388             ctx->locks->lock(ctx->locks->user, lock);
```

What am I doing wrong? (aside from fact that it InfoMessage should go into setPath probably ;-)

**Comment by dpavlin** [comment]
I'm getting same SIGSEGV if I try to add it to `crereader.lua` increase/decrease line spacing (which can be slow on device) so I'm **really** doing something wrong.

**Comment by hwhw** [comment]
OK, this is probably something about the mupdfimg implementation I added. Does it work when you comment out the ImageWidget in the InfoMessage dialog?

Ah well, and we need to add the resource directory to the customupdate building. It did not yet test how it fails when the image simply isn't there (but I think this isn't the problem here).

**Comment by houqp** [comment]
> I tried to add message to filesearcher and failed

That's strange, because your patch does not cause segfault in PC. :(

EDIT:
Um.. suddenly, I found many segfults now, and its quite random. I am looking at it.

**Comment by houqp** [comment]
OK, seems that it is caused by mupdfimg. The segfault disappeared after commenting out the ImageWidget. It is because of my broken toolchain?

EDIT:
The strange part is I can trigger the same segfault even in code that calls no API in mupdf, for instance, invoke a none-empty jump history menu.

**Comment by hwhw** [comment]
I think I fixed it. There was that double-free bug, and then there also was a wrong order of parameters for fz_convert_pixmap. I have no idea how this could have worked before. But believe me, it did here :-)

**Comment by houqp** [comment]
Yes, no more segfault here. Great job!

**Comment by dpavlin** [comment]
@hwhw ++ geat work
