### ISSUE TITLE
failed to build ft.o because of lacking required head file.

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#12]
When building, it complains: ft.c:21:22: error: ft2build.h: No such file or directory

The thridparty has been updated, so

FREETYPEDIR=$(MUPDFDIR)/thirdparty/freetype-2.4.4

should be changed to:

FREETYPEDIR=$(MUPDFDIR)/thirdparty/freetype-2.4.8

**Comment by hwhw** [comment]
Fixed by yourself, thanks :-)
