### ISSUE TITLE
Suggestion for introducing API entry in configuration files

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#120]
Given the possibility that we might have to introduce in-compatible entry changes in our `*kpdfview.lua` files in the future, I suggest we add an API number entry in every configuration files so we can detect what version the user is using and update to latest version accordingly.

**Comment by dpavlin** [comment]
I would stick 2011.04 into version (floating point number which will grow, so easy checking for updates) but on the other hand, I would also love to have git commit from which it was built visible somewhere in reader (together with version) so we can get more precise bug reports against versions.

**Comment by houqp** [comment]
Ha, the commit version reminds me the idea of the Lab page in kpdfviewer, in which users can choose to turn on/off experimental features and look for technical related information like memory usage and some other hacky stuff. This page might be a good place to hold that commit version.
