### ISSUE TITLE
Regarding debug output wrapper

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#121]
I am inclined to use a debug output wrapper to print debug information instead of use print directly.

In this way, we can disable all these debug prints in release (users don't care about these output anyway) and even add a debug mode to redirect the debug log to a file.

**Comment by dpavlin** [comment]
This was my original idea when I wrote dump, so I'm all for it :-)

**Comment by houqp** [comment]
Ha, then will you take this task?

**Comment by dpavlin** [comment]
I would love to have something like debug("message", var, " message ", var2, ...) which would check with type(var) and print tables using dump. Does this make sense?

**Comment by houqp** [comment]
looks yummy. This issue has been assigned to you ;)

**Comment by houqp** [comment]
Thanks @dpavlin , closing for now.
