### ISSUE TITLE
Regarding highlight records

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#125]
There is still one more thing that I am not sure about current highlight implementation:

When we are selecting highlights, we select word by word, but when we are  saving it, words are concatenated into lines. That means we are losing information here, i.e., we cannot easily reconstruct the original words from book settings (Yes, we still can since we got the offset of lines). 

I adopted this approach because I want to make the setting files smaller (save word by word will make it harder to read). But I still don't know whether this is a good idea. How do you think? Do we need to save the original text information (word by word)?

**Comment by hwhw** [comment]
Somehow I like the "line" approach. It just feels natural to select a span and the selection goes into a single text.

However, we might want precise information when we add exporting later. So I'm not completely sure yet.

**Comment by dpavlin** [comment]
I would also prefer lines, but real test would be desktop application which returned notes to pdf (or something similar). But, it shouldn't stop release 2012.04 :-)

**Comment by houqp** [comment]
The original text information can be recovered with some computation, so it might not cause too much trouble even on exporting I think. Since you guys are happy with this, I am closing this for now.
