### ISSUE TITLE
Offset calculation messed up in unireader.

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#132]
Not sure whether I am right or not, but following is what I observed when trying to fix a bug in highlight feature:
- when we are rendering pages, the origin point is the upper left corner of the page to render. So the points inside the page all have negative offset, while points above the page have positive y offset and the same goes for points on the left side of the page. (refer to calculation of offset_x and offset_y)
- when mupdf and djvulibre returns offsets of text inside pages, it uses positive offsets.

It works fine if we just support highlight feature in fit_to_content_width mode because we can just transform all the offsets to positive ones and currently, the highlight feature works in that way. But when we want to make it work properly in all modes, we have to unify the offset notion. 

I am afraid we might have to force getPageText() to return negative offsets, or we might need to change the way we calculate offset_x and offset_y. Any thought?

EDIT:

Oh, how stupid am I. We just need a page to screen offset transform (which we already have) to fix this ;P

**Comment by dpavlin** [comment]
I have somewhat related problem: it seems that djvu documents have coordinates of bounding boxes shifted by 10 or so pixels down. I assume that I'm calculating screenOffset wrong for djvu. @houqp do you have any idea why?

**Comment by houqp** [comment]
@dpavlin I cannot reproduce it here. By saying bounding boxes, are you referring to the self.cur_bbox calculated in unireader:setzoom() ?

**Comment by dpavlin** [comment]
If you select bounding box manually, it seems to work, but when you show it using `X` it's shifted down. It seems to be problem with `DjVu3Spec.djvu` but it doesn't show on all djvu files (to be honest, I have just 3, and 2 of them show this behavior). I will have to download more of them to give it proper test :-)

**Comment by houqp** [comment]
AHa, I managed to reproduce it now. It is related to this issue. Previously, `getRectInScreen` is introduced as a helper function for highlight feature. And in the highlight mode, the bbox for djvu file is not the same as pdf because the coordinate in djvulibre starts from the left-bottom. That's why we need to overwrite this function in djvureader.

Now when you use it for the manually crop, the bbox you passed into it has the same coordinate as pdf's bbox. So you get a wrong return from djvureader's `getRectInScreen()` function.

I will try to rewrite part of the highlight code and see if I can fix it.

**Comment by dpavlin** [comment]
@houqp you rock :-) Now I understand what you meant by "overwrite function" :-)

**Comment by houqp** [comment]
OOPS, just noticed that commit a672cf4 is incompatible with previous highlight settings for dvju. So if we read previous setting files for djvu books, the highlight will be displayed in the wrong position. Maybe it's time to use setting API(#120) to handle this incompatibility.

**Comment by dpavlin** [comment]
@hpouqp could you write code along the lines of f55654f03ee29251b7a8830a407a5747a3602152 ?

I don't have any djvu files with highlight saved :-)

**Comment by houqp** [comment]
@dpavlin Yes, of course :) But I will not be able to get back to my development PC before Wed. ;p
