### ISSUE TITLE
page number counting in djvu

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#137]
This bug is reported by eLiNK. Jump in djvu by TOC menu leads to one page ahead of the correct one.

I notice that although the page counting in djvulibre library starts from 0, all of the TOC in my djvu books starts from 1. I don't have much djvu books here, so I am not sure whether it is a bug or it is just my books have corrupted TOC. Can you further check this with your djvu books?

**Comment by dpavlin** [comment]
I have just a few documents which are djvu and have TOC, and it seems that we are jumping one page too far. Nice example file is DjVu3Spec.djvu

**Comment by houqp** [comment]
Oh, how can I ignored `DjVu3Spec.djvu`! Fix commited. :)
