### ISSUE TITLE
incessant cursor movement while pressing and holding a five-way key

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#142]
Hi,

this issues was originally mentioned at http://www.mobileread.com/forums/showpost.php?p=1879699&postcount=17.
It could be used in the file chooser, in the highlighting mode and in the input box.

Doable?

**Comment by hwhw** [comment]
Yes, probably. I'll experiment with it a bit.

**Comment by dpavlin** [comment]
Device and emulator do generate all three event types:

``` lua
-- event values
EVENT_VALUE_KEY_PRESS = 1
EVENT_VALUE_KEY_REPEAT = 2
EVENT_VALUE_KEY_RELEASE = 0
```

So simple change from `ev.value == EVENT_VALUE_KEY_PRESS` to `ev.value ~= EVENT_VALUE_KEY_RELEASE` in `UniReader:inputLoop` generate repeated events for all keys (including fiveway), but I'm afraid that repeat rate is a little bit too fast.

However, it's nice effect to see how fast we can refresh e-ink screen, and it does scroll pretty fast :-)

**Comment by hwhw** [comment]
Funny, I did insert them but didn't bother playing with them. I think an easy filter on a certain number of EVENT_VALUE_KEY_REPEATs would be easy to implement. I'll give this a fast try before releasing.

**Comment by dpavlin** [comment]
OOH, fast refresh is nice combined with partial screen refresh to browse over pages... It's closest possible feature to flipping real book, and it looks nice :-)

**Comment by hwhw** [comment]
luckily, I got distracted :-P so we didn't do duplicate work (and you did it all...). great! I'll be home again in about half an hour and will test. I think this could go into release, couldn't it?

**Comment by dpavlin** [comment]
sure :-)

**Comment by dpavlin** [comment]
I didn't put it in `helppage.lua` and `selectmenu.lua` because I don't think that it makes sense.

**Comment by hwhw** [comment]
I'm not so sure with selectmenu, but for now I'm fine with leaving this as-is, since selectmenu isn't used nearly as often as the other parts you cared for already.
