### ISSUE TITLE
Compile glue code as dynamic libraries

### ISSUE THREAD

**Issue by hwhw** [koreader/kindlepdfviewer#148]
I added an experimental branch "dynlib_test" that introduces the Makefile target "libraries" (plus some dependent targets) and allows to compile the C glue code as dynamically insertable libraries. The glue code itself can remain unchanged for that. It's working up to some point, I think it breaks because those dynamic libraries will contain redundant statically compiled libraries themselves - I think there might be some collisions.

That is intended to allow the code to be integrated into other projects as well. And the "original" lua interpreter has nice stack dumps. But in the end, it will allow us to use LuaJIT - at least I want to experiment with it a bit. I'm pretty fascinated of it since I first read about it - unfortunately that was only a few days ago. It runs on ARM, too :-)

For now, this is more an academic experiment, I just wanted to explain the new branch a bit :-)

**Comment by houqp** [comment]
Looks cool :)

**Comment by tigran123** [comment]
We are already using LuaJIT, so this can be safely closed, I think.
