### ISSUE TITLE
release 2012.05.xx

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#163]
If #158 is resolved are we for last release of old code-base? (remember to replace xx with date :-)

**Comment by dpavlin** [comment]
Sigh, we should probably address #134 and #120 before release...

**Comment by houqp** [comment]
And the last comment in #132 :)

**Comment by dpavlin** [comment]
9de055eb5d881efa3e8a3dbd6ce7372bb6cc6744 is important fix, but it will go in with @NuPogodi changes I guess...

**Comment by houqp** [comment]
Ready for the release?

**Comment by dpavlin** [comment]
I think that @hwhw can use magic toolchain to compile release version :-)

**Comment by hwhw** [comment]
Yep, will do so in a few hours (around 22pm here in CEST - GMT+2)

**Comment by dpavlin** [comment]
Sigh, I totally ignored last code dump from @NuPogodi http://www.mobileread.com/forums/showpost.php?p=2094819&postcount=477 see #178

**Comment by hwhw** [comment]
Released!
