### ISSUE TITLE
problems with go to screensaver behaviour

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#164]
It seemed that if I use the power slider in file browser mode, the DXG will go to a sleep mode with current display. Because there is no prompt nor it is the screen saver, I thought the reader just lost response! Another slide of power switch, it back to normal again.

So I think when user use the power slider in file browser mode, it should either go to screen saver or give some prompt that it has go to sleep mode(like add one line to the bottom of screen), otherwise it could cause some confusions.

Besides, I just found that if I start the reader without amazon framework, the reader cannot go to screensaver even it has the prompt that it was going to. I can understand the behavior, but there should be different prompt message for this.

On the other hand, the reader can freeze input in file browsing mode, without amazon framework, but I'm not sure if this is a battery saving sleep.

**Comment by hwhw** [comment]
Yep, filechooser is not sleep-save at the moment. But it should have presented the screensaver picture, I think. At least _with_ the framework running.

Without the framework, maybe we should present a screensaver image ourselves. But it should go into the sleep mode, I think.

Think of the sleep mode as being a more platform-like event, the framework will just present a nice image when that happens.

**Comment by houqp** [comment]
This has been fixed by @NuPogodi's patches
