### ISSUE TITLE
navigation in mobi

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#179]
The current help page said [1..0] will jump to key*10% location. I tried many times before I realized I need to use "alt+Q" for number 1. I think the description here should be more clear.

Besides, the 10% jump is still too rough for a big book. Why can't we have a jump dialog just like pdf page input? 
1. input G, have a input box
2. input number to jump to xx%, the least unit is 1%. This is small enough. And, like pdf jump input box, user shouldn't need to use alt to input number, just press corresponding keys is enough.

**Comment by dracodoc** [comment]
I also found the mobi support on this file have some problems. The mobi was converted from html by calibre.
https://www.box.com/s/27e2b9dbe61445888e44
1. There is a table of content in original viewer, but kindlepdfviewer cannot find table of content.
2. Certain italic and bold word was treated as a single line. In 46.45% of mobi, kindlepdfviewer treat "New Yorker" as a single line, but if you read the mobi with the original viewer and search "new yorker", you will find it should not be a single line.

Besides, in mobi and epub reading, the last line often was cut in half, and displayed grayed in next page, while the top line could be cut at the top too. I understand this implementation could be simple, but it really is not the ideal display effect expected by user. Before the screen was updated, I think the top and the bottom should be checked, if the top line was too near to edge, it should move down a little bit. If the bottom line was too near, it should be just discarded.

**Comment by dracodoc** [comment]
I don't want to open another issue, so I just post these under this issue because I think they are somewhat connected.
1. epub seemed ignored the paragraph indent. No matter how much I set it, it just the same.
2. can we have a user configurable default font for epub, mobi? I like certain font, but I need to choose it for every epub, mobi every time.

**Comment by hwhw** [comment]
I guess that a lot of these problems are upstream issues in CREngine, but I'll take a closer look when I manage to find some time for that :-)

The problem that lines might be cut in half is hard to overcome, I think. Again this would need a very close look on the bindings of CREngine.

**Comment by dracodoc** [comment]
I found kpdf is quite slow to open certain mobi or epub. It took about 1 minute to open this mobi and its epub version every time. The original software can open the mobi immediately.

https://www.box.com/s/42bc8e9df7cbe11a6126
https://www.box.com/s/59a86614ef552d3f86de

This could also be the problem of the CREngine.

The file is about 2 M which include 180 pic files. I deleted all pic files and open it again, same speed, so it is not about the pic files. It could be the epub have a big table of contents. However the mobi table of contents is not recognized by CREngine, so maybe it's not table of contents too....

**Comment by hwhw** [comment]
I've analysed this a bit and it's indeed CREngine. I didn't go much further, but the time is mostly spend in
doc->text_view->LoadDocument(file_name);
and also
doc->text_view->Render();

It's quite a big document, and I think the culprit is that CREngine is going through it at least once to determine the resulting length.

**Comment by dracodoc** [comment]
I think the document is not too big compare to normal books, especially every chunk of html is less than 200k. CREngine should not need to go through all the length to open certain position, so this is a problem of CREngine. The original software can open them immediately.

Another possibility is the epub was converted by calibre which include a complex css. But the mobi need same time to be opened, so it should not be the problem of css.

Anyway, it's the problem of CREngine. Where can I post a issue to CREngine site?

**Comment by hwhw** [comment]
Implemented jump-to-percent input box as suggested in commit 22ce736e112fa7e760b517b90e4a42636f50b32b
I think we should open a new issue for the long document loading time. However, I'm not sure how we could approach that, though. I'll close _this_ issue for now.

**Comment by hwhw** [comment]
Oh, sorry, I read your reply afterwards. I was mainly talking about that the document will fill ~2k+ pages. It doesn't depend on its file structure, I think. It's just that CREngine takes its time. That will be a profiling job to be done.

**Comment by dracodoc** [comment]
Thanks for the jumping feature! This could be the only one not depend on CREngine, so the other issues I mentioned may have to be put to later on the list, that's alright for me.

**Comment by tchaikov** [comment]
@dracodoc , sure, you may want to file an issue to CREngine . it is actively developed at sf.net . and it is using sf's own bug tracking system at http://sourceforge.net/tracker/?group_id=191284&atid=936756 . i did a quick search for `slow` and `speed` . seems no one has raised this issue before.

**Comment by dracodoc** [comment]
I thought about this before, so I downloaded the coolreader for windows and tried it. Maybe because PC is much more powerful, it don't have the speed issue. Then it's not easy for other people to reproduce the issue in pc.

**Comment by dracodoc** [comment]
I tried coolreader in kindle from here
http://www.mobileread.com/forums/showthread.php?t=148850

Open a 800K epub took it 7-8 seconds, but the second time opening it took just 2 seconds. While kpdf will need a full 25 seconds to open the same book every time.

So it seemed not a issue of CRengine itself.

**Comment by hwhw** [comment]
Hm, we probably use a newer version of CREngine, though. But I also think the paged vs. the continuous display might also contribute to the matter. Really, the time is spent in the both CREngine calls. We probably use CREngine differently - obvious for the paged vs. continuous, but there might be other differences. We even might compile different parts or use different compilation setups. Not easy to track down... We probably need to profile both Coolreader and Kindlepdfviewer (with focus on the CREngine).

I guess the difference in sequential calls with Coolreader has its reasons in a) the document might not have even really been closed, or b) it's the memory allocator.

**Comment by dracodoc** [comment]
So it's more complicated than I thought... Though coolreader for kindle do provide a good reference.
It's a important issue but not emergent for me. 
I opened another issue for this problem since the #179 has been closed and it included multiple issues..
