### ISSUE TITLE
switch to LuaJIT?

### ISSUE THREAD

**Issue by hwhw** [koreader/kindlepdfviewer#186]
I've just tested LuaJIT in place of Lua, and it is working quite well. What do you think about a switch? It would provide a great speedup, although it is probably not worth doing it only to get some speed in edge cases.

It opens up further possibilities, like replacing our C glue code by FFI bindings. However, this is nothing we should tackle now, I guess. For now, LuaJIT is just "a faster Lua" and a drop-in replacement (with a git repository, yay!)

See the new luajit branch in which I did the replacement. The speed improvement is most notable when loading bigger menus or large directories in the file browser.

In theory, it should also allow to use a GDB integration so debugging the software with GDB could become possible.

**Comment by dpavlin** [comment]
I'm all for it. GDB debugging is probably more important to me than speedup :-)

**Comment by houqp** [comment]
+1 for switch :)

I am interested in the performance of FFI bindings.

**Comment by hwhw** [comment]
I did the switch. Yes, FFI is quite interesting and should be _really_ fast, even faster than the C glue code.
However, first experiments with the gdb integration failed here. Will investigate more.

I took the liberty to switch debug() to Debug() (against our naming convention, but it's a special case anyway) to avoid clashing with the "debug" package. Under Lua, it just worked (TM), LuaJIT however ignored all the calls to debug(). Also, I found quite a bunch of wrong escape sequences in strings. Lua just ignored these, LuaJIT complained.

I hope it will be a smooth transition for everyone. Otherwise, please re-open this bug. As soon as I have worked out GDB debugging, I'll create a page in the Wiki about that.
