### ISSUE TITLE
Help section page number

### ISSUE THREAD

**Issue by Verci** [koreader/kindlepdfviewer#187]
Hi to all, I discovered a little bug using KPV; it's just a small thing, btw.

In Reading Mode, pressing H to go to the Help Page, going to the 2nd one, then pressing Back to return to the book, then pressing Home to return to File Browser and finally pressing H to go the File Browser Help page (it is only one), you are been redirect to the 2nd page of this section, but it's wrong because the page is only one, so you have a blank page and the label "Page 2 of 1"; pressing back take to the right page.

Sorry for my English if I made some mistakes.

KPV is a great tool.

Bye

**Comment by houqp** [comment]
thanks for the report, it is fixed now :)
