### ISSUE TITLE
mupdf gamma to implement contrast

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#2]
In my experiments with mupdf's pdfdraw:

https://github.com/dpavlin/k3libre/blob/master/pdf2fb.sh

I found gamma option incredibly useful to change contrast of page. I'm somewhat C/lua newbie, so would you mind wrapping it into lua?

**Comment by hwhw** [comment]
yeah, up to now I didn't even know about this function :-) I added a lua interface for it to the drawcontext (DC). you can set gamma correction via dc:setGamma(1.4) or similar. Still untested, since I'm not in reach of my Kindle right now :-) so I leave this open until tested.

**Comment by hwhw** [comment]
ok, implemented _and_tested. works faster than I thought, about a few tens of msecs.
