### ISSUE TITLE
slow at open some epub/mobi

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#206]
This issue was mentioned before in 
https://github.com/hwhw/kindlepdfviewer/issues/179

That issue included multiple issues so it was closed because some of them were solved.

kpdf is slow at opening certain epub/mobi. It took 1 min to open this 2M epub or mobi every time. The original software can open the mobi immediately.

https://www.box.com/s/42bc8e9df7cbe11a6126
https://www.box.com/s/59a86614ef552d3f86de

Then I tried coolreader in kindle from here
http://www.mobileread.com/forums/showthread.php?t=148850

Opening a 800K epub took it 7-8 seconds, but it took just 2 seconds open it in second time. While kpdf will need a full 25 seconds to open the same book every time.

So it seemed not a issue of CRengine itself.

**Comment by houqp** [comment]
Wow, good to know that it is not a upstream bug :) There must be something wrong with our Lua glue code...

**Comment by dracodoc** [comment]
I'm thinking maybe coolreader created some cached file after the first time opening a book. There are some pdb file in cached directory under cr3 directory, maybe that's why it can open book much quicker after the first time.

**Comment by dracodoc** [comment]
I looked at the creader.lua. It seemed kpv always use local style sheet instead of the built in css from the epub book. I'm not sure if this is desired. Will there be some performance problem if the local css have something mismatch with the epub?

I replaced the epub.css with cr3.css, the time to open one epub seemed reduced a little bit, probably because the cr3.css is simpler.

**Comment by houqp** [comment]
um... to check this out, maybe we need to doing some profiling on crengine to see whether it is spending most of the time on CSS parsing.

**Comment by dpavlin** [comment]
I have been playing with coolreader on Android a bit, and I can see a (small, but Android device is much faster) difference when using internal document CSS (which we do now) and ignoring it.

I also noticed that ignoring document CSS is only way to make font size usable -- on DXG Linux Journal epub always have fonts too small to be readable, and our font size selector seems to change just default font size, so whole document looks very strange.

There is also option to render per-page and scrolling. We are currently using scrolling, but I don't see speed difference between them -- it seems that crengine layouts whole document on open time, so I took a look into Android implementation and found `setCacheDirectoryInternal` (and not back to code...)

**Comment by dracodoc** [comment]
dpavlin, thanks for the explanation! 
As I mentioned earlier, I guessed it's the method coolreader in DX used: cache the layouted document after first time opening, so coolreader can open the document much faster later.

**Comment by houqp** [comment]
Confirm that @dpavlin 's patch (3fe518979c11fa7aebf16eae8e6a008479ca567c) works. Now we have a instance open on the second run!!!!

**Comment by dpavlin** [comment]
@dracodoc can you test lastest build? https://github.com/downloads/dpavlin/kindlepdfviewer/kindlepdfviewer-af53a78.zip

**Comment by dracodoc** [comment]
I tested this build, the time needed for the second time opening is much less!
However, this cache seemed cannot be kept between kpv sessions. Once I quit kpv and start kpv again, the opening time of epub come back to the longer one.

Of course if the cache was to be saved in file, there need to be some more housekeeping work, like deleting the cache when deleting the book. However most epub/mobi file will be much smaller than pdf, so I don't expect there will be a problem of space if kpv keep all the current existing book cache in files.

**Comment by dpavlin** [comment]
The cache is kept between sessions, but on restart reader has to seed in-memory cache from file again. Cache files are in `/mnt/us/kindlepdfviewer/cr3cache` so you can check that cache files are preserved between restarts. crengine does all that handling and file expiration for us.

**Comment by dracodoc** [comment]
I checked that folder, it seemed that crengine only keep the last epub cache, so if user opened more than 1 file, only the last cache is saved. Have you looked at the coolreader in kindle (not in android)? If I remember correct, coolreader in kindle don't have this limit, and on restart the reading cache should be also faster than first time open too. I've uninstalled coolreader a long time ago, so I'm not totally sure about it. 
Right now it took kpv almost the same time to open a file on reader restart even there is cache available.

**Comment by dracodoc** [comment]
I installed coolreader for kindle again, verified that:
1. coolreader can cache more than one books. The cache index and cache looks just the same with kpv, but there are multiple cache files.
2.coolreader loading cache in new session is fast, about 2 seconds.

**Comment by dpavlin** [comment]
@dracodoc thanks for your efforts in debugging this issue. 100 bytes of cache size really isn't enough, so I increased it to 64Mb. I will build it later today when this change lands into master.

**Comment by dracodoc** [comment]
You are welcome!
Thanks for your effort!
