### ISSUE TITLE
Long file names are cut off in the info window

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#214]
Hi,

there is an issue with long files names.
If you've got a file name of the type: Author_ThisIsAVeryVeryVeryVeryVeryLongArticleName–SomeDescription(Journal)_nnp_year.pdf

In the info window (which gets called up by pressin 'I'), the file name is shown on three rows as follows:
Author_
ThisIsAVeryVeryVeryVeryVeryLongArticleName–SomeDescription(Jo
nnp_year.pdf

Thus, some part of the name is cut off.

**Comment by ghost** [comment]
Seems to be fixed by minor corrections to function renderUtf8Multiline(...)
https://github.com/NuPogodi/kindlepdfviewer/blob/master/rendertext.lua

**Comment by eLiNK2gl** [comment]
confirmed

P.S.: tested on https://github.com/downloads/tigran123/kindlepdfviewer/kindlepdfviewer-29-Aug-2012.zip
