### ISSUE TITLE
search word is 'lost'

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#218]
calling up the search function again reveals no search word (i.e. pressing 'S' button, while being in the 'search results' window), which is a regression from previous versions.
It would be better if the old search would be shown.

**Comment by dpavlin** [comment]
This bug is fixed with 1c6421dc3f4ebb18f089456c59c0ea563e25514f

**Comment by houqp** [comment]
Can we close this now?
