### ISSUE TITLE
improvement for the Rename function.

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#219]
being in the file browser, it is possible to rename a file by pressing SHIFT  + R combination.
It would be desirable to show the old name in the rename window as a suggestion (currently nothing is shown).
(in case one wants to do only minor modifications to the file name).

The combination SHIFT + Del should remove the name from the rename input box (already implemented).

**Comment by eLiNK2gl** [comment]
The old name in the rename window is still not shown.

P.S.: tested on https://github.com/downloads/tigran123/kindlepdfviewer/kindlepdfviewer-29-Aug-2012.zip

**Comment by eLiNK2gl** [comment]
As it seems I tested @dpavlin's development build all the time as @tigran123's zipped file cannot be used for the prescribed installation procedure (i.e. copying to /customupdates and installing by pressing shift + shift + I).

The issue can be closed now.
Sorry for the confusion.

**Comment by dpavlin** [comment]
@eLiNK2gl thanks for verifying issue
