### ISSUE TITLE
Updated version of inputbox.lua with Shift+Key support, helppage, calculator, etc.

### ISSUE THREAD

**Issue by ghost** [koreader/kindlepdfviewer#232]
@dpavlin  I've just uploaded new version of INPUTBOX:LUA to my repo https://github.com/NuPogodi/kindlepdfviewer. 
If someone is still going to use inpubox also as calculator, one needs to introduce minor changes to HELPPAGE.LUA (so I've also refreshed this file in my repository).
Alternatively, both lua-files and the description of all changes is uploaded elsewhere http://rghost.net/40063033
Please, test whether this version fits your expectations or not and let me know if you need me to send pull request with the updated code. I hope that it should run smoothly with the last release (kindlepdfviewer-0f22302) and solve most of the problems mentioned in Issues #194, #218, #219
# 

HELPPAGE.LUA (minor changes - to use this function for documentation of math functions available in calculator mode)
1.  LINE 44 & 80: Added the parameter 'title' to function HelpPage:show(ypos, height, commands, title). If defined, it allows us to set arbitrary title instead of usual 'Active Hotkeys' and, hence, to use this function for other purposes -- this feature will be used in INPUTBOX.LUA to enumerate the math functions available in calculator.
2.  LINE 70: I've also a bit changed the vertical shift for displayed items: just cosmetics

INPUXBOX.LUA (a lot of changed code)
1. Lowercase layout is default
2. Uppercase chars by pressing Shift+Key; it will probably require us to remap some old MOD_SHIFT-commands to MOD_ALT (not the upper raw that is responsible for digits: Alt-Q = 1, etc.)
3. New 'documentation' functions
        - usual helppage with active hotkeys (Alt+H)
        - list of available math functions (Alt+M, active in the calculator mode)
4. Added two small functions to move cursor to the first/last position in inputbox (Shift+FW-left/FW-right)
5. Some minor rearrangement for layouts (mostly for convenient work with calculator)
6. Keeping initial "d_text" in InputBox:input(... d_text, is_hint) when is_hint is not true 
    (say, for minor changing of long filenames #219, etc.) or incremental search.
     In order to solve Issue #219 one has to rewrite the rename command in filechooser.lua in the following way

```
self.commands:add(KEY_R, MOD_SHIFT, "R",
    "rename document",
    function(self)
        local oldname = self:FullFileName()
        if oldname then
            local name_we = self.files[self.perpage*(self.page-1)+self.current - #self.dirs]
            local ext = string.lower(string.match(oldname, ".+%.([^.]+)") or "")
            name_we = string.sub(name_we,1,-2-string.len(ext))
            local newname = InputBox:input(0, 0, "New filename:", name_we)
            if newname then
                newname = self.path.."/"..newname..'.'..ext
                os.rename(oldname, newname)
                os.rename(DocToHistory(oldname), DocToHistory(newname))
                self:setPath(self.path)
            end
            self.pagedirty = true
        end
    end
) 
```
1. Added: calculator with a proper documentation of available math functions
   In order to run calculator, one has to add somewhere (say, in filechooser.lua) the following code
   
   self.commands:add(KEY_K, MOD_SHIFT, "K",
       "run calculator",
       function(self)
           local CalcBox = InputBox:new{ calcmode = true }
           CalcBox:input(0, 0, "Calc ")
           self.pagedirty = true
       end
   )

**Comment by dpavlin** [comment]
@NuPogodi thanks a lot. This is great improvement to inputbox, and I hope to use it to implement note-taking functionality in future.

I mostly copy-pasted this explanation to commit message (where it should really be for future reference because this issue will get closed) and merged to master.

**Comment by dpavlin** [comment]
@NuPogodi could you plese do `git pull origin master` in your checkout to be in sync with current development?

**Comment by eLiNK2gl** [comment]
Shift + key does not work on KDXG.
ALT + first row letters (for 1,2, etc) work only in uppercase layout.

P.S.: tested on https://github.com/downloads/tigran123/kindlepdfviewer/kindlepdfviewer-29-Aug-2012.zip

**Comment by ghost** [comment]
1. No suggestions about the problem with Shift + key on KDX. I have no possibility to test & to fix it - do it by yourself. 
2. Try to delete outdated file 'mykeyboard.lua' from the folder with kpdfview & repeat Alt+Q..P test.

**Comment by dpavlin** [comment]
Could you try: https://github.com/downloads/dpavlin/kindlepdfviewer/kindlepdfviewer-20fae93.zip

it seems that @tigran123 build doesn't include latest changes, which is mostly while I like git sha1 in filename because it's easier to find out from which code distribution is built.

**Comment by tigran123** [comment]
I have justed tested my build on KDXG and it works absolutely fine, i.e. Shift+key uppercases it and Alt+Q...P enters the number, as expected. Tested on exactly the same build as eLINK2gl.

**Comment by eLiNK2gl** [comment]
@tigran123  you are right.
In fact, I tested @dpavlin's development build all the time as your zipped file (b/o its internal structure) cannot be used for the prescribed installation procedure (i.e. copying to /customupdates and installing by pressing shift + shift + I).

**Comment by tigran123** [comment]
@eLINK2gl I assume you are talking about the old kpdfview-update.zip (downloaded from http://www.bibles.org.uk) and NOT about the kindlepdfviewer-29-Aug-2012.zip downloaded from github, because the latter has exactly the same structure as the official build .zip files and should be installable via launchpad's shift-shift-I procedure.

**Comment by eLiNK2gl** [comment]
@tigran123 I am talking about kindlepdfviewer-29-Aug-2012.zip from the git webpage. It has one more level inside the zip file than necessary.

**Comment by tigran123** [comment]
@eLiNK2gl  Ah, yes, you are absolutely right. Mea culpa. The next one will have the correct structure.

**Comment by dpavlin** [comment]
`make customupdate` should produce distribution zip without any additional efforts :-)

**Comment by tigran123** [comment]
Thanks, that's cool! :)

**Comment by dpavlin** [comment]
I think we can close this issue
