### ISSUE TITLE
Multi-level TOC in PDF and DjVu files should not be expanded.

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#235]
If a book contains a large multi-level outline tree (aka "bookmarks" or "TOC") it will be very hard to navigate if it is fully expanded (as is the case with kindlepdfviewer at present). For example, if you look at this file (http://www.bibles.org.uk/The-British-Study-Edition-of-the-Urantia-Papers.pdf.zip) it contains four Parts, each Part contains many numbered Papers, each Paper contains  6-15 numbered Sections. (actually each Section contains numbered Paragraphs but I didn't create bookmark entries for these to avoid excessively large size of the PDF file).

The solution to this problem would be to indicate in the standard way (i.e. with the '+' sign, like in Acrobat, CoolReader, etc) that a node can be expanded and then display the appropriate submenu if the user selects it. And if the node is expanded, then selecting it should collapse it.

Also, I should emphasize that by default the tree should be _collapsed_ (like in Acrobat), not expanded (like in CoolReader), because if you expand it and wish to navigate to a node at the bottom you would have to collapse all the previous parents.

A separate small problem is that pressing 'T' to get the TOC should also position you to the current place in the tree, not to the beginning.

NuPogodi showed me how to use menus in kindlepdfviewer and I quite liked the mechanism used. So, if there is some kind of "assignment" mechanism in this project then feel free to assign me to this task --- I would like to try implementing it.

**Comment by ghost** [comment]
[QUOTE]A separate small problem is that pressing 'T' to get the TOC should also position you to the current place in the tree, not to the beginning.[/QUOTE]
I added this feature to my version of unireader.lua just before the release in May, but it was somehow disappeared in the released version.
[CODE]
function UniReader:showToc()
    if not self.toc then
        -- build toc if needed.
        self:fillToc()
    end
    -- build menu items
    local menu_items, item_no = {}, -1
    for k,v in ipairs(self.toc) do
        table.insert(menu_items, ("    "):rep(v.depth-1)..self:cleanUpTocTitle(v.title))
        -- to find current TOC-entry
        if v.page <= self.pageno then
            item_no = item_no + 1
        end
    end
    if #menu_items == 0 then
        showInfoMsgWithDelay("This document does not have a TOC.", 2000, 1)
    else
        toc_menu = SelectMenu:new{
            menu_title = "Table of Contents",
            item_array = menu_items,
            -- to autoselect current TOC-entry
            current_entry = item_no,
        }
        item_no = toc_menu:choose(0, fb.bb:getHeight())
        if item_no then
            self:gotoTocEntry(self.toc[item_no])
        else
            self:redrawCurrentPage()
        end
    end
end
[/CODE]

**Comment by dpavlin** [comment]
This is my fault. As a punishment, I will document whole process of pull request, so that @NuPogodi will forgive me I hope :-)

Update: I moved it to wiki: https://github.com/hwhw/kindlepdfviewer/wiki/PullRequest so it can be used by future developers new to git. Hope it helps...

**Comment by dpavlin** [comment]
@tigran123 consider yourself assigned to this task, but @hwhw will have to add you (and @NuPogodi) as project members so we can record this in issue tracker :-)

**Comment by tigran123** [comment]
Ok, thank you, I will get on with it. But to do it properly --- theory first! I.e. I will quickly finish reading "Programming in Lua" book while browsing the *.lua files of kindlepdfviewer --- this is why I needed crengine to display plain text files as just that --- and there seems to be no way to force this via txt.css, but in the proper/standalone CoolReader I can do this with a single tick in the Settings. (I am sure we'll eventually find a way to force it via crengine and eventually obsolete the standalone CoolReader :)

**Comment by tigran123** [comment]
In my example `origin` is upstream hwhw's repository and `dpavlin` is my copy on github.

However if you forked repository and check it out, origin will point to your repository and not hwhw's.

I will expand explanation to (hopefully) cover this better

**Comment by tigran123** [comment]
Oops, did I close this accidentally??? Sorry! Reopening as it was closed by mistake --- this is FAR from being done yet! :)

**Comment by tigran123** [comment]
Solved by the pull request #255 so I am closing this issue.
