### ISSUE TITLE
Some corrections to crereader.lua

### ISSUE THREAD

**Issue by ghost** [koreader/kindlepdfviewer#237]
https://github.com/NuPogodi/kindlepdfviewer/blob/master/crereader.lua
# List of changes
1. Used another way to find original position in the document after changing its length (i.e. changing fontface, fontweight, interline spacing, etc.) The old method was based on storing & restoring the percentage: it was not always exact. Now the Xpointer is used instead of percents: it takes just a little bit longer, but much more exact.
2. Fixed the screen rotation functions 'K' & 'J' inherited from UniReader ().
3. Removed not crengine-related hotkey for manual cropping Shift-X
4. Added new functions for fast navigation
   a) Shift+Left/Right = scroll 10 pages backwards/forward
   b) Shift+Up/Down    = jump to previous/next item in TOC-list (without calling TOC-menu)
5. Minor modifications in function to choose cre-font (removed excessive procedures of saving [saveCurrentBB] and restoring [restoreFromSavedBB] the screen)
6. Erased my own, outdated comments so that last changes are easy to find

**Comment by dpavlin** [comment]
@NuPogodi is there anything I can do to help you submit changes as pull requests? This way I have to do `git cherry-pick` of your commit and then resolve conflict and bother you again to take a look if I did mistake...

**Comment by dpavlin** [comment]
On related note, fast navigation is really nice, and we should probably add it for mupdf and djvu also :-)

**Comment by ghost** [comment]
Added one more minor correction... Pull request sent...
