### ISSUE TITLE
the current set zoom feature works not so well for file with large page size

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#24]
I found this when testing the djvu file in my computer. The original per-page size is very large, thus after setzoom, its zoom factor turned out to be 0.148515. 

Now if I zoom that page with altmode set, the zoom factor is added by 0.1, which makes the page about 70% larger. This step is too large that it somehow make the zoom feature unusable for this kind of files.

Any ideas for deterministic zooming implementation that handles large page size?

**Comment by houqp** [comment]
I come up with a workaround:
https://github.com/houqp/kindlepdfviewer/commit/84d6bfe3f8ad7bd851b48a82074d6606268a599b

But I think maybe it is a little bit dirty :-(

**Comment by dpavlin** [comment]
I think that concept of calculating zoom step based on page size is good one.

**Comment by houqp** [comment]
workaround added to master
