### ISSUE TITLE
Very easy to crash the viewer via calculator.

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#241]
I really like the calculator feature added recently --- the functionality, the nice keyboard layout switching etc.

But it is very easy to crash the application by entering something like "os.exit()" or even things like "A/B" in calculator input box. Now, the question is: is it possible to trap the errors of the build-in interpreter so that it doesn't terminate the entire viewer, but results in a nice error message displayed? E.g. division by zero is trapped and "Inf" is displayed correctly now.

**Comment by houqp** [comment]
Maybe you can try using `pcall` function? It is used in `keys.lua` and some other places in KPV.

**Comment by tigran123** [comment]
@houqp I don't think I understood how you suggest to use pcall function to trap the errors in the interpreter.

**Comment by tigran123** [comment]
Ah, I see, I just looked at the article "Passing a Language through the Eye of a Needle" by the author of Lua and it discusses the use of pcall for constructing protected environment.

**Comment by ghost** [comment]
The calculator is a typical example of interpretator of commands typed by user in inputbox. It is called by command
if pcall(function () f = assert(loadstring("r = tostring("..s..")")) end) then ... end
so it somewhat blocks the potential user stupidity. But nobody may give 100%-guarantee that user may enter here something that results to crash. The one and the only method is to use calculator for purposes it was written.

**Comment by tigran123** [comment]
The fix for this problem is in my pull request #279

**Comment by tigran123** [comment]
Closing the issue because the pull request was merged into the master tree.
