### ISSUE TITLE
Lua Questions

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#249]
Strictly speaking, this is not an "issue" as such, but we do not have a separate Developers Forum at present, so I thought I'd create this "issue" where one could ask (and answer too) questions about KPV design, Lua programming tricks, etc.

And here is my first question: why if I write the code like this:

```
local curmenu_titles = {}
table.insert(curmenu_titles, self:cleanUpTocTitle(v.title))
```

it fails with the error: "bad argument #2 to 'insert' (number expected, got string)", but using a dummy concatenation makes it work:

`table.insert(curmenu_titles, ""..self:cleanUpTocTitle(v.title))`

I just want to append the value returned by self:cleanUpTocTitle(v.title) to the end of curmenu_titles and I don't see why I should force concatenation. In UniReader:showHighLight() table.insert() is used without concatenation.

**Comment by ghost** [comment]
curmenu_titles[#curmenu_titles+1] = self:cleanUpTocTitle(v.title)

**Comment by tigran123** [comment]
Ok, thanks, that is also the method recommended by the author of Lua (as of version 5.1) --- and it works fine, thank you.

I wonder why we don't do it all the time, instead of table.insert().

**Comment by ghost** [comment]
table.insert(curmenu_titles, #curmenu_titles+1, self:cleanUpTocTitle(v.title))

**Comment by houqp** [comment]
That's strange... Can you always reproduce it?

**Comment by tigran123** [comment]
Yes, here are two lines --- the one commented out works:

```
--curmenu_titles[#curmenu_titles+1] = self:cleanUpTocTitle(v.title)
table.insert(curmenu_titles, self:cleanUpTocTitle(v.title))
```

the second line produces an Lua error:

```
lua config error: ./unireader.lua:1656: bad argument #2 to 'insert' (number expected, got string)
```

**Comment by tigran123** [comment]
Oops, closed by mistake, re-opening.

**Comment by tigran123** [comment]
Here is my next question: how do I add a table local to a document, i.e. re-initialized on each open? I tried to do this by simply adding to UniReader environment, like this (after the line "toc = nil"): `toc_cview = {}` and added the code `self.toc_cview = nil` to UniReader:inputLoop() right after `self.toc = nil`. So, I expect it to _not_ persist across opening/closing the file. However, very strangely, the values in `self.toc_cview` table survive from the previous file _sometimes_. It is quite hard to reproduce as if some other process (one of djvulibre threads?) is writing to our address space simultaneously with ourselves writing to the same addresses in Lua code.

(of course I do know how to debug race conditions like that (and it is not yet 100% established that this is a race condition), I am only asking whether the Lua side is adequate, i.e. I placed the variable in the right place or not).

**Comment by tigran123** [comment]
I see what is going on --- no race conditions, just Tigran not knowing how to manipulate Lua tables properly :)
Basically, I didn't expect that after `self.table = nil` the value of `#self.table` can be non-zero, that is all. I expected it either to generate an error or be zero, but in actual fact it remained the same as before the assignment `self.table = nil`. The solution to my problem is simply to initialize `self.cview = {}` before its use, that is all there is to it :)

**Comment by houqp** [comment]
OK, for the first question, it turns out to be a bug in `self:cleanUpTocTitle`
method. ;p

Internally, `self:cleanUpTocTitle` calls `string:gsub`. But `gsub` actually has two return values. (refer to [this page](http://lua-users.org/wiki/StringLibraryTutorial)) That's why using concatenation works.

Maybe we should do something like the following?

``` lua
function UniReader:cleanUpTocTitle(title)
    s, _ = title:gsub("\13", "")
    return s
end
```

**Comment by tigran123** [comment]
Yes, why not. Also, concerning the second question, it seems a bit inconsistent for Lua to treat simple tables (a=nil, #a generates an error) and tables inside environments/objects (self.a = nil, #self.a does not generate an error) differently.

**Comment by tigran123** [comment]
Btw, shouldn't it rather be:

```
function UniReader:cleanUpTocTitle(title)
    local s, _ = title:gsub("\13", "")
    return s
end
```

**Comment by houqp** [comment]
@tigran123, You are right :) Since it is your idea, could you include this patch in your pull request?

**Comment by houqp** [comment]
As for the second question, following is what I got from the lua prompt:

```
> a = {}
> function a:func() print(#self.a) end
> a:func()
stdin:1: attempt to get length of field 'a' (a nil value)
stack traceback:
        stdin:1: in function 'func'
        stdin:1: in main chunk
        [C]: ?
> a.a = {}
> a:func()
0
> a.a = nil
> a:func()
stdin:1: attempt to get length of field 'a' (a nil value)
stack traceback:
        stdin:1: in function 'func'
        stdin:1: in main chunk
        [C]: ?
```

Seems that I cannot reproduce the inconsistent?

**Comment by tigran123** [comment]
@houqp Ok, I will do (I already included it in my multilevel TOC changes). Btw, concerning the latter --- I am totally rewriting them because last night I simply saw (yes, while asleep :) a beautiful algorithm for converting an array of depths to a tree. It is so simple and efficient that it is worth spending a day to rewrite everything (my current attempt was quite inefficient, because to replace a node with all its children (of just one level down) it had to traverse all the intermediate nodes all the way to the next node, including all the grand-children of all levels down. But in the current tree-based implementation the traversal is not needed, because the list of immediate children is always available for each node.

**Comment by tigran123** [comment]
Btw, those curious about my algorithm can see it here:

http://www.bibles.org.uk/depths-to-tree.lua

**Comment by houqp** [comment]
looks cool! :)

We need to rebuild the parent and children table every time we make changes on the nodes, right?

**Comment by tigran123** [comment]
Thank you.

No, we only need to build the parent and children tables _once_, right after the physical fillToc() returns us a valid self.toc.

After that we only change `toc_cview[]` ("current view of TOC") using the static (for a given document) information about parents and children. These two tables (parent a simple one with no holes (but possibly zeros) and children a table of tables with nil=holes) are indexed on _physical_ (i.e. fully expanded) TOC, so they are static. But `self.toc_cview[]` can change depending on the user's request to expand or collapse of any of its items.

**Comment by houqp** [comment]
Aha, I see. That's a lot more efficient  :)
