### ISSUE TITLE
page:getUsedBBox() sometimes return invalid values

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#25]
On some pages, getUsedBBox return 0.01,0.01 -0.01,-0.01which breaks fit to content and two column zoom factor by increasing it to 60.

Example file: http://bsdmag.org/system/articles/attachment1s/14274/original/FreeBSD_Portability_With_VMware_BSD_04_2011.pdf

This file contains huge bitmap backgrounds and works really bad with this pdf viewer, partly because of our memory limits. But bounding box problem happens even before we hit first memory limit.

**Comment by houqp** [comment]
seems like a bug in muPDF?
