### ISSUE TITLE
Feature: allow deleting bookmarks.

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#256]
The subject says it all: it should be possible to delete a bookmark. Not only because potentially one can fill up storage with bookmarks :) but, more importantly, for a psychological reason: users are less likely to use any feature if it cannot be undone. I use bookmarks a lot in CoolReader but I don't create them in KPV because I cannot remove them.

Anyway, I volunteer to work on this issue, so consider me "assigned" to this task, unless someone is already working on it.

**Comment by houqp** [comment]
Go ahead @tigran123 , many people, including me, need this feature :)

**Comment by tigran123** [comment]
Solved by the pull request #263 so closing this issue.
