### ISSUE TITLE
try to add a unireader class to minimize code duplication

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#26]
I just added a unireader class so pdfreader and djvureader can act as a subclass of it. This makes adding new reader easier and shorcuts can be unified. For details, please refer to this branch:
https://github.com/houqp/kindlepdfviewer/tree/unireader

I am not very familiar with Lua, so not sure whether this is a good idea. Any suggestions?

**Comment by hwhw** [comment]
I think it's a pretty good suggestion indeed. It helps to fledge out the format-dependent bits and leaves the interface logic in the unireader class. I would be ready to pull it, I'd say.

**Comment by houqp** [comment]
Great! Since this branch is based on the djvu branch, I will fire a pull request once I got djvu support stablized :-)

**Comment by dpavlin** [comment]
I pushed last two patches to djvu branch. With them, I compiled first version which runs on my DXG. Good work, houqp. Should we just merge it to master and continue there? :-)

**Comment by houqp** [comment]
I am ok with the merge :-)

**Comment by hwhw** [comment]
I'd say go on then. The fewer loose ends, the better :-)
