### ISSUE TITLE
Feature: PDF reflow.

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#265]
Even though the standard Amazon PDF viewer does not support pdf reflow, most other ebook readers do: for example, Sony PRS-505 (if I remember the model number correctly, I gave it away as present ages ago), Hanlin V3, Hanvon n516 (aka "Azbuka") and Nook Touch Glowlight.

Therefore, it would be a great addition to KPV features if it could support PDF reflow. Although reflow is useless for scientific books (because equations and tables would fall apart), for books on philosophy, history and fiction it is a very useful function indeed.

**Comment by dpavlin** [comment]
I thought about reflow a lot, and it's not easy problem. Most we can get is data for highlight which includes words with coordinates (or even smaller chunks, depedning on pdf producer).

Then we would need to generate some format which we can re-flow, probably generating html for crengine.

It might work, but to be honest, I yet have to see pdf reflow which really works well, so I'm somewhat skeptical, but having one in lua would make it easy to hack on :-)

**Comment by tigran123** [comment]
Yes, I understand. At best we'll be able to do the same as pdftotext command.
I remember on Hanlin V3 I used pdf reflow to read very nice typeset PDF files of Rudolf Steiner's books which were too big for Hanlin V3's 6" screen. Now, Kindle has exactly the same 6" screen size, but with kindlepdfviewer's Shift-X function one can read those very same books nicely on it, even in portrait mode. This is why I say that "Shift-X is the crowning feature of kindlepdfviewer" :)

**Comment by tigran123** [comment]
Something not likely that we'll tackle in the near future, so closing the issue for now...

**Comment by dpavlin** [comment]
I would leave it open. If frequent request on MR and I would love to prevent opening another issue. We can use this one as placeholder (since github doesn't have WONTFIX flag ;-)

**Comment by tigran123** [comment]
Do we still need to keep it open now that KOPTReader has been integral part of KPV for ages?

**Comment by dpavlin** [comment]
no, we don't
