### ISSUE TITLE
Manual bbox values lost in two-column (F or Shift-F) modes on Next page.

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#275]
Here is how to reproduce the problem.
1. Take a real 2-column book with big margins (test/2col.pdf is no good because the margins are so small that the bug is almost unnoticeable).
2. Open a typical page and do "A" to reset to "fit to page" zoom.
3. Press Shift-X and position the bbox boundaries appropriately, i.e. getting rid of all the white margins around the text.
   Then turn to the next page and do the same, thus programming bbox values for both odd and even pages.
4. Press F to start reading. The view is correctly positioned to the top left corner, in accordance with our bbox assignment. (btw, for Hebrew books it should be top right corner, but never mind, we are not talking about Hebrew books right now :)
5. To read the first column keep pressing Down on the 5-way controller until you reach the bottom of the first column.
6. To go to the top of the second column press Right on the 5-way controller. The view is correctly positioned to the top right corner. So far, so good.
7. Keep pressing Down on the 5-way controller until you reach the bottom of the second column.
8. Now, to go to the next page you have two options: either press Right on the 5-way controller or press Next page. Both do the same thing and position the view incorrectly, i.e. showing most of the first column and some part of the second column and a gap in between.

I.e. after turning the page the bbox values are lost. However, if I now press "F" again, then the view is corrected and placed in the proper place.

So, the only annoyance is having to press "F" on every page turn to reposition the view on the top part of the left column. Shouldn't this be done automatically, i.e. without the need to press "F"?

**Comment by eLiNK2gl** [comment]
just checked one of my books.
When I press 'F', the page is placed to the BOTTOM left corner.
Pressing 'Right' on the 5-way controller selects the BOTTOM right corner.

A bit off-topic, on at least one of the pages the bbox is grossly off.
Do I understand correctly that if I deleted the history (using 'Del' in the list of last documents opened) there is no lua file left, which could have contained info on bbox positioning?

P.S.: just got a scrambled picture problem (dotted lines on the display and no text) on exiting kpdfviewer. It is a long time since I saw it last.

**Comment by tigran123** [comment]
On the "scrambled picture" problem --- are you sure you exited in portrait mode? I always get "scrambled picture" when I exit in Landscape mode.

**Comment by eLiNK2gl** [comment]
Yes, I am.
I almost never read in Landscape mode.

As far as I remember, this bug was associated with the auto-rotation feature of the KDXG.
But this time the device was on the table so I just leaned the reader very slightly to press the 'Home' button.

**Comment by tigran123** [comment]
@eLiNK2gl Yes, you understand correctly concerning bbox stored in the history file, so deleting it will make it disappear.

**Comment by eLiNK2gl** [comment]
@dpavlin, sent you the file.

**Comment by tigran123** [comment]
Pull request with the fix was merged in, so closing the issue.
