### ISSUE TITLE
write access to repository needed to close issues in commit messages

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#28]
I experimented with closing issues using commit messages, and according to https://github.com/features/projects/issues I need write access to repository. This way I create two issues, one for bug itself and another for pull request and that just clutter issue tracker.

https://github.com/features/projects/issues

Close and Reference with Commit Messages

Issues know all about commits. By using a few simple keywords you can close an issue right from a commit message, or just leave a note on the issue.

The syntax is basic: if you want to close issue #35, put closes #35 somewhere in your commit message then push to GitHub.

Supported keywords: close, closes, closed, fixes, fixed

Leaving a note on an issues referencing your commit is even easier — just mention the issue number without using one of the above keywords, e.g. This commit references #35.

Anyone with write access to your repository may close an issue or leave a note.

**Comment by hwhw** [comment]
I would be very willing to give you and dave write access. You've already invested so much work, it's quite amazing.

**Comment by hwhw** [comment]
Well, I've not found that config option here in github yet :-) Errm, and it seems to work nevertheless: In the moment I commit a relevant pull request, the ticket gets indeed closed. Nice.

**Comment by houqp** [comment]
Wow, this feature is cool! Never know github has this.

**Comment by dpavlin** [comment]
I would guess that you have to add us as collaborators under https://github.com/hwhw/kindlepdfviewer/admin/collaboration

**Comment by hwhw** [comment]
well, let's see :-) done that now.

**Comment by houqp** [comment]
Got it. Thx hw. Just create djvu branch so other can work directly on it.

**Comment by hwhw** [comment]
I would like to invite traycold to be a collaborator, too. What about the others? And traycold, would you like to have access?

After all, it's git, so damage can be done only temporary and a revert will all make good again :-)

**Comment by houqp** [comment]
second that. welcome traycold :)

**Comment by dpavlin** [comment]
traycold++

**Comment by dpavlin** [comment]
@traycold: I think that your repostory started as fork of djvu branch, which might explain huge number of files on each of your pull request. If that is still a problem, you can delete your local master branch and checkout again hwhw's (origin) with something like this:

```
git checkout -b new origin/master
git branch -d master
git branch -m new master
```

**Comment by traycold** [comment]
> @traycold: I think that your repostory started as fork of djvu branch, which might explain huge number of files on each of your pull request. If that is still a problem, you can delete your local master branch and checkout again hwhw's (origin)

thanks for the tip, i will try it

> And traycold, would you like to have access?

thank you all! i will gladly try and contribute as much as possible to this project. So my answer is yes, even if in the near future, until i get quite confident with git, i will try not to mess too much with your repo :-) Anyway i may help you to manage "administrative tasks" like closing issues, and so on

**Comment by hwhw** [comment]
Great :-) So I'll close this issue for now, I intend to reuse it for collaboration-related stuff :-)

**Comment by dpavlin** [comment]
If you want to have another pair of eyes on your code, just submit pull request as you did before. That's kind of peer-review for source before it lends in master, and I noticed that @houqp doesn't push directly to master, while I mostly do. But, now that you have write permission you can also merge pull requests if they look good to you :-)

**Comment by traycold** [comment]
thanks for your tip, i will indeed follow your suggestion

**Comment by houqp** [comment]
> If you want to have another pair of eyes on your code, just submit pull request as you did before. That's kind of peer-review for source before it lends in master, and I noticed that @houqp doesn't push directly to master, while I mostly do. 

Well, I sometimes do directly push to master, but only for little fixes. :)
