### ISSUE TITLE
new release 2012.09

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#282]
Lots of changes have been introduced since last release. Is it stable enough for a new release now?

**Comment by tigran123** [comment]
How about a code freeze for a few days (so we test everything thoroughly) and then have an official release? The current state of the program seems very good and stable to me. Or do we still have anything critical?

**Comment by houqp** [comment]
Yes, I agree. After five months, finally come the new release :)

**Comment by tigran123** [comment]
Good, and I am working on my local branch called "auto-upgrade" and you can guess what that means --- certainly not for the current stable release :)

**Comment by dpavlin** [comment]
I was thinking about read-only rsync repository for wifi or correctly configured usbnetwork, what are your ides for auto-update?

Another idea was to pack whole update into pdf file and extract it using mupdf. This would enable download over 3G (and possibly provide some documentation to really be useful as document) and at the same time provide update if opened with kindlepdfviewer.

**Comment by houqp** [comment]
The pdf packing approach looks cool :)

But why not just the customupdate from github and extract it locally?

**Comment by tigran123** [comment]
Yes, I was thinking along the lines of @houqp suggestion, i.e. wget the downloads page from github, parse it to see if there is a latest zip with git-rev other than currently installed and then either unzip it (dealing with ETXTBUSY issue on the executable) or just put it to customupdates and advice the user to do "Shift-Shift-I" after the application exits.

But packing the update into pdf is an interesting idea. In my typesetting environment there is an option "attachfile" so I can easily produce PDF files with anything embedded as attachment (actually Acrobat Professional can do this as well, so it is no big deal).

Very interesting idea, @dpavlin . Is it easy to extract the attachment via mupdf?

**Comment by tigran123** [comment]
Back to the release topic: should someone write some kind of ChangeLog describing the features (only the major ones, not every single commit, obviously) between the last release and the current one.

I think the most important changes are @dpavlin 's yesterday's fixes to zoom modes/position handling, so these should definitely be mentioned as many people on the forum(s) complained about this (and not only them but everyone in my household and my friends, who get their Kindle's jailbroken and kindlepdfviewer installed the moment they enter my house  --- and if they don't have a Kindle already then the first thing they do when the leave my house is to run to the nearest webbrowser and buy one from Amazon.co.uk immediately :)

**Comment by tigran123** [comment]
By "code freeze" I meant allowing bugfixes only, not an "absolute code freeze", of course.

**Comment by houqp** [comment]
@NuPogodi , you mean a `changelog` file included in the release zip file?

**Comment by ghost** [comment]
@houqp , changelog is a good idea, but I am not qualified enough to make it properly (I missed 2 weeks when a plenty of commits & pull requests were made)

**Comment by tigran123** [comment]
I think someone can start writing it and others can contribute items if something was missed. The hardest thing is to start, then it will grow like a snowball :)

**Comment by tigran123** [comment]
For the actual release candidate I suggest to perform the following simple optimizations:
1. Remove "-d" switch to reader.lua to disable debugging output. We will still get exactly the same data in crash.log as we do now, i.e. the crash message with the indication as to where it occurred.
2. Disable warning/log messages coming out of crengine. I don't know which switch controls them. We need to find out.
3. Find out why "Dingbats" and "StandardSymL" fonts are included in the fonts directory and remove them if they are not needed internally by mupdf (e.g. to substitute builtin fonts like it does with Nimbus\* fonts). This is to avoid wasting time on startup trying to register them (and crengine rejects them with warning messages anyway).
4. Don't bind mount/umount the system fonts in kpdf.sh. This would save considerable time on startup/exit. Now this item is very tentative (unlike the above three) and if there are good reasons to keep it then let's keep it. I am just throwing it in as a suggestion to be evaluated.

**Comment by tigran123** [comment]
For item 1. I included the change in my current pull request (as it is obvious), but the other items require discussion.

**Comment by ghost** [comment]
I've just noticed two places where minor cosmetic corrections could be applied, namely
1. ATM, the footers in selectmenu.lua & helppage.lua are left-adjusted, these also contain the prompt for users how to call help (selectmenu.lua) and how to go back (helppage.lua). By minor correction to function DrawFooter() in filechooser.lua, one may readily make the rest footers to look in a similar way.
2. When writing the code of inputbox.lua, I left wrong command to delete the 1st entry in the math function list (called in calculator mode by pressing Alt-M). It might also be readily avoided.

ATM, I've synchronized my repo to the hwhw's one so I could submit these changes.by myself or, alternatively, any other colloborator may cherry-pick 3 files stored in my repo
-- filechooser.lua [ see functon DrawFooter(), line 91 ]
-- fileinfo.lua [ added footer with 'Page 1 of 1 - Press H for help', line 203]
-- inputbox.lua [ line 496 should look like self.calcfunctions:del(KEY_P, MOD_SHIFT, "P") ]

**Comment by tigran123** [comment]
Ok, I'll try to do this.

**Comment by tigran123** [comment]
Done, see pull request #340.

**Comment by tigran123** [comment]
Actually, I could have done it in a neater way by a little bit of extra overhead (creating remote branch, cherry-pick a commit from it, merge back to master, etc) and this would have given you proper attribution for the fixes.... I hesitated for a second whether to go through all these and then decided that for the sake of two small fixes it is not worth it (hope you don't mind).

**Comment by ghost** [comment]
Thanks... Although everyone knows that one shouldn't judge a book by its cover, but there always exists a black sheep who may consider a bit different footers as a bug.

**Comment by houqp** [comment]
As for changelog file, we can just copy the content  from wiki. I think everyone should add their own contributions to the wiki changelog to make sure no important update is missed :)

> Find out why "Dingbats" and "StandardSymL" fonts are included in the fonts directory and remove them if they are not needed internally by mupdf (e.g. to substitute builtin fonts like it does with Nimbus\* fonts). This is to avoid wasting time on startup trying to register them (and crengine rejects them with warning messages anyway).

For this one, I am not sure yet. I have no idea why mupdf ships with these two fonts. Anyone want to take a look at `mupdf/pdf/pdf_fontfile.c` ?

**Comment by tigran123** [comment]
Yes, the answer was right there --- we cannot remove these two fonts because they are used for substituting the builtin fonts "ZapfDingbats" and "Symbol" which PDF specification demands that the implementation must support. Ok, let them stay...

**Comment by houqp** [comment]
But we can indeed exclude these two files from crengine's font loading list to make it boot faster.

**Comment by dpavlin** [comment]
@tigran123 you can commit changes with different author using `git commit --author=nupogodi` which is smart enough to track you as commiter and original author.

**Comment by tigran123** [comment]
I suggest that for the release we change the default value of rcountmax to 0. This is the more sensible value (and used by default by Amazon and other viewers) and many users may not know that they can use `Shift-R` command to set it and instead will complain that KPV has "bad quality rendering, the page is too dark sometimes". But those who wish to set it explicitly to a higher value can still do so via `Shift-R`, though I can't imagine why they would want to do that, unless they are on an uninhabited island and wish to preserve every last drop of battery, knowing that they can't recharge it again.

**Comment by houqp** [comment]
I agree with the default rcountmax to 0 settings. Usually when some one use eink for the first time, they would want to use higher partial refresh because it is insanely slow compared to liquid crystal screen. But the longer they use, at least for me, the more they would want to do full screen refresh...

**Comment by houqp** [comment]
Ready for the release now? We have many great patches waiting for merge ;P

**Comment by tigran123** [comment]
@houqp In that case, could you please change it (rcountmax) yourself? I didn't check rcount/rcountmax logic and so I am not sure if _both_ rcount and rcountmax initial values should be zero (I think they are, aren't they?) for this to work.

Yes, I agree that the release is now due. Well, @NiLuJe 's patches look interesting (the part about zombies, NOT about Makefile which I think he wisely reverted) but maybe they can go in immediately _after_ the release, to give us a chance to test them properly....

**Comment by tigran123** [comment]
Btw, I assume that for the release we make some sort of git branch (for critical fixes if need be) for easy reference to the exact state of code that went into release?

**Comment by dpavlin** [comment]
Git relase is simply a git tag. I will tag 3bd8c5c9f47ea2d83eb537ef6584ffce3ea9645f as v2012.09 and upload build to hwhw download page, so we can continue development...

**Comment by tigran123** [comment]
Ok, but maybe the name v2012.10 is more appropriate as it is the 10th month now, not 9th :)

**Comment by dpavlin** [comment]
We'll cheat a bit and hope that 2012.10 will be new release with bugfixes :-)

**Comment by tigran123** [comment]
Ah, I see, ok :)

**Comment by dpavlin** [comment]
taged, uploaded to hwhw's download so we can continue working in master branch.

Thanks for all your hard work, it was a privilege to be part of this release with you all!

**Comment by tigran123** [comment]
and how do I switch from master branch to the state tagged by v2012.09? Create a local branch "v2012.09" and then what? How do I connect it to the remote tag "v2012.09"?

**Comment by tigran123** [comment]
Also, shouldn't @NuPogodi announce it on the-ebook.org?

**Comment by dpavlin** [comment]
tag isn't a branch. It's just a name for one commit which you can use in log, diff etc so you don't have to switch anything

**Comment by tigran123** [comment]
Ah, ok, so it is like an alias for the sha1 number.

**Comment by dpavlin** [comment]
In it's simplest form. Nowadays we also have annotated git tags which are proper commits -- if you wanted to understand how git works http://marakana.com/s/advanced_git_graphs__hashes__compression_matthew_mccullough_github,1280/index.html is probably best video I found so far...

**Comment by kai771** [comment]
@dpavlin Sorry if this has been discussed before, but... page turning in two-column mode is way slower than it was in 2012.05. Have you by any chance removed caching of the next page? I noticed this on pdf document, that consists of scanned pages, if it's of any help.

**Comment by tigran123** [comment]
@kai771 Pre-caching in two-column mode was disabled by @dpavlin in SHA1:  69e43d1c4d. I don't know why. The pull request with this change is #343. Try undoing the change (in lines 1533-34 of unireader.lua) and see if it makes a difference.

**Comment by tigran123** [comment]
I assume the reason it was disabled is that precaching would obtain the data for the next page in the zoom mode other than the current one, i.e. useless for us. But if I am wrong @dpavlin would surely correct me.

**Comment by hwhw** [comment]
Thank you all so much for the vast amount of work you put into this. It truly became a community approach and it saddens me a bit that I got so distracted lately. Still planning to get back into matters, but "real life" did not permit this lately. However, the last two weeks I was on vacation and that put some things back into perspective somewhat. So, this should be a thank-you note to you all, I'll not bother you with my busy life :-)

**Comment by tigran123** [comment]
@hwhw We ought to thank you for starting it up --- starting up from scratch is always the hardest bit. Just as without Linus Torvalds I wouldn't have become a Linux kernel hacker, likewise without you I would hardly bother to start hacking the Kindle now (don't look at the photo on the left --- it shows me in the somewhat "younger days" ) :)

@kai771 the same applies not only to two-column mode but also to creating manual bbox via Shift-X --- then precaching is disabled.

**Comment by tigran123** [comment]
@dpavlin I just measured the times and it seems @kai771 is right --- even though in two-column mode we call precache far too many times (i.e. on each fiveway move down the column and right to switch to the next column), still the time saved on the next page :show() far far outweighs (especially if it is a DjVu file with 4000x7000 resolution) the time lost...

I will re-check the timings again to make 100% sure, but so far they suggest that pre-caching in two-column and manual bbox mode is not a bad idea.

**Comment by kai771** [comment]
Reverting the changes in #343 worked. It's back to normal now. Thanks. If it's of any help, I just opened pdf file, and immediately pressed Shift-F. I didn't set bbox.

**Comment by tigran123** [comment]
Here are the actual numbers. With no pre-caching the times spent in the call to drawOrCache() from show() are:

```
# show()->drawOrCache(93) in 127703 us
# show()->drawOrCache(93) in 1824 us
# show()->drawOrCache(93) in 2045 us
# show()->drawOrCache(93) in 2252 us
# show()->drawOrCache(93) in 2142 us
# show()->drawOrCache(93) in 2176 us
# show()->drawOrCache(93) in 2141 us
# show()->drawOrCache(94) in 138217 us
# show()->drawOrCache(94) in 1890 us
```

And with pre-caching enabled, they are:

```
# show()->drawOrCache(93) in 2428 us
#       preCache->drawOrCache(94) in 139649 us
# show()->drawOrCache(93) in 32297 us
#       preCache->drawOrCache(94) in 8421 us
# show()->drawOrCache(93) in 2082 us
#       preCache->drawOrCache(94) in 1779 us
# show()->drawOrCache(93) in 1877 us
#       preCache->drawOrCache(94) in 1812 us
# show()->drawOrCache(93) in 2142 us
#       preCache->drawOrCache(94) in 1895 us
# show()->drawOrCache(93) in 2162 us
#       preCache->drawOrCache(94) in 1927 us
# show()->drawOrCache(93) in 2070 us
#       preCache->drawOrCache(94) in 1836 us
# show()->drawOrCache(94) in 2103 us
#       preCache->drawOrCache(95) in 134079 us
# show()->drawOrCache(94) in 1555 us
#       preCache->drawOrCache(95) in 1445 us
```

So, turning from page 93 to page 94 without precaching takes 138217 microseconds whereas with precaching it is only 2103 microseconds, i.e. 65 times faster!

**Comment by tigran123** [comment]
I have just discovered something interesting: the behaviour on PDF and DjVu file is different. I.e. for PDF files (I mean typeset PDF files of course, not like your scanned one --- if you have a scanned PDF that means it is in the wrong format and should be converted to DjVu) enabling precaching in two-column mode has no benefit, i.e. the time spent on turning to the next page is exactly the same as without precaching. Maybe that is why @dpavlin disabled it. But for scanned books (i.e. DjVu files and also your strange "for some reason still in PDF that should be in DjVu" books) the benefit of precaching is enormous.

**Comment by tigran123** [comment]
I created the issue #349 to track this properly, so let us go yonder and deal with it.

**Comment by houqp** [comment]
@tigran123 , sorry that I didn't response to your post. I had a really busy day today, and probably next two weeks. :( I send the change in my pull request, hope it works ;P

@hwhw , good to see you again, I know you are watching us :)

BTW: I just received my paper white today, the reading experience sucks as always :P Hopefully I will have a one week thanksgiving vocation, I can then sit down and work on porting kpv to kindle touch series.
