### ISSUE TITLE
disabling debug messages for production release?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#289]
In kpdfdjview branch I disabled all debug messages by assigning

```
function nodebug()
return
end
Debug = nodebug
```

and also commenting out the unconditional printf() to the terminal in pdf.c. Shouldn't we do the same in the master branch for the final release? The rationale is that all these writes to a 38kbps terminal are slowing down the program unnecessary.

I think debug messages should be enabled as and when necessary by the developer on his own system, not for all end-users actually using the program. If the end-user is experiencing a problem and is so kind as to wish to assist with debugging then he will be asked to edit reader.lua (comment the above four lines) or, if absolutely necessary, supplied with a binary compiled with all those printf()s in.

What do you think?

**Comment by tigran123** [comment]
Oh, I forgot that it is Lua, not C, so we can make it even shorter:

```
Debug=function()end
```

**Comment by dpavlin** [comment]
I would love to leave debug output (at least until we are sure that everything works), but missing peace is a easy way for users to submit debug log together with bug report.

**Comment by tigran123** [comment]
Ok, understand. Closing the issue.

**Comment by xeonxu** [comment]
How can I get debug messeges on emulator?

**Comment by chrox** [comment]
You can run reader.lua with debug option like this `./reader.lua -d test`.

**Comment by xeonxu** [comment]
Perfect. Thank you!
