### ISSUE TITLE
Speed optimizations

### ISSUE THREAD

**Issue by hwhw** [koreader/kindlepdfviewer#29]
I've just switched the default CFLAGS in the Makefile to stop outputting debug symbol information (not performance relevant, but doesn't make much sense when optimizing) - and more importantly switched over to "-O3". The former "-O0" lead to the horrible performance regarding bitmap scaling since a fz_mul255 wasn't properly inlined then - which made for lots and lots of function calls. "-O2" is already much better, "-O3" does give another small performance benefit.

Also, I've specified "-march=armv6", gives a small speed-up.

There's room for more optimization in the muPDF code, I think. We could edge out a few cases that are more directed towards colored output, we could use the fact that we're going grayscale there.

This also works great for the PDF linked in issue #25

**Comment by houqp** [comment]
This change rocks!!!!!!!

It  used 20s to render one of my test fileone page previously. Now it can be rendered in 3s!

**Comment by dpavlin** [comment]
@hwhw how did you find inline problem? Do you run some kind of profiler on code?

**Comment by hwhw** [comment]
Yep. I did run gprof. And then I was surprised to find fz_mul255 among the functions that got called most often.

In order to compile with gprof, you have to add "-pg" to the compiler options. Note that your toolchain and the corresponding sysroot must match closely since the profiling API has changed a bit between glibc version, if I got that correctly. A binary compiled with "-pg" will then dump profiling information, by default to a file "gmon.out". With the "arm-xxx-linux-gnueabi-gprof" you can generate textual information from that file.

**Comment by houqp** [comment]
Should we strip kpdfview for releases?

**Comment by tigran123** [comment]
We already compile with -O3, so it seems sensible to close this issue.
