### ISSUE TITLE
Deleting a directory does not refresh the filechooser list

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#297]
When one deletes a file the list is immediately updated, but if you do the same with a directory then it stays in the list and attempting to enter it causes an error and then the list is refreshed and it disappears.
Looking at the code for KEY_DEL handling in FileChooser:addAllCommands() I see no obvious reason why this happens.

**Comment by dpavlin** [comment]
thanks, pull request merged to master
