### ISSUE TITLE
performance issues with the bookmarking feature

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#301]
I have a feeling it became slower.

1) when you select a bookmark from the bookmarks' list, the page you were on, before pressing 'B', shows up and only then the page corresponding to your bookmark. This was not the case in '25edd31'.
2) as I used the bookmarking feature yesterday, my dxg froze for at least 30 sec. Could be something else at play, but somehow I believe this freezing is related to the bookmarks.

**Comment by dpavlin** [comment]
Did screen had small black box visible on top at the moment it was frozen?

I added to provide some kind of visual indication when page is rendering in attempt to better troubleshoot frozen moments, so I'm wondering did you noticed it while kindle was frozen? (was it pdf file or some other format?)

**Comment by eLiNK2gl** [comment]
It was a pdf book.

I don't remember seeing a small black box but on the other hand I was not paying attention.

**Comment by tigran123** [comment]
@eLiNK2gl Do you still experience performance issues with PDF bookmarks? If so, email me the PDF file -> tigran@bibles.org.uk (if it is less than 25MB) or put it somewhere where I can download. If not, please close the issue.

**Comment by eLiNK2gl** [comment]
as it seems the issue 1 has been surreptitiously fixed.
has not experienced a problem with issue 2 either.
