### ISSUE TITLE
kpdfviewer made an epub book corrupt (?)

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#316]
while opening an epub book, kpdfviewer crashes with the following error 'Segmentation fault'.
Before it worked just fine. I read more than half a book. But yesterday, kpdfviewer did not go into screensaver.
As I wanted to proceed with reading, I noticed the message 'Going into screensaver ...' and no screensaver.
I managed to get in and closed the book and cannot open it anymore. Removing the corresponding lua file from the history does not help.

If you need the book, please contact me at MR.

**Comment by dpavlin** [comment]
Does removing cache file from cr3cache helps?

Can you rename book and try it again, just to figure out if it's epub specific problem or more general crengine bug?

**Comment by eLiNK2gl** [comment]
@dpavlin  Yes, renaming the book helps.

**Comment by houqp** [comment]
@eLiNK2gl , did you try removing the cache file before renaming the book?

**Comment by eLiNK2gl** [comment]
@houqp  removing the cache helps as well
