### ISSUE TITLE
Question: FileChooser:choose() and callback() return to reader.lua?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#317]
In reader.lua we currently expect two return values from FileChooser:choose() like this:

```
local file, callback = FileChooser:choose(0, G_height)
        if callback then
            callback()
        else
            if file ~= nil then
                running = openFile(file)
```

However, looking at the code of FileChooser:choose() I see it never returns this callback, so shouldn't we modify reader.lua to do this instead:

```
local file = FileChooser:choose(0, G_height)
       if file then
          running = openFile(file)
```

**Comment by houqp** [comment]
Yes, go ahead, this was a dirty workaround I added when there is no `command.lua` module in KPV ;p

**Comment by tigran123** [comment]
Ok, thank you, added to pull request #318
