### ISSUE TITLE
SHIFT + left / right broken

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#322]
if you press 'SHIFT + left / right', it is supposed to take you 10 pages backwards / forward (epub).
And it obviously does, but the page does not get refreshed.

**Comment by ghost** [comment]
1. Make sure that you have updated your unireader,lua after https://github.com/hwhw/kindlepdfviewer/pull/313 - generally, it should help
2. Please, test whether the any jumps (like Shift-Up/Down = prev/next chapter, Alt-Q..P = 0%.99% , etc) are accompanied by the same problem (not refresh)

**Comment by eLiNK2gl** [comment]
@NuPogodi
tested https://github.com/downloads/tigran123/kindlepdfviewer/kindlepdfviewer-c4b04d9.zip
All's fine now. Thanks.

**Comment by tigran123** [comment]
Closing as you confirm it was fixed.
