### ISSUE TITLE
Need to undo the previous commit by NuPogodi to crereader.lua

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#336]
The commit (persumably done by mistake, not intentionally of course) by @NuPogodi to crereader.lua broke the current crereader functionality because it relies on the future :inform() method of InfoMessage(), so we need to undo it for the current release. I don't know how to revert commits, @dpavlin can you do this?

I checked, it certainly did not come with my pull request #335, i.e. @NuPogodi pushed the change directly to hwhw/master tree.

**Comment by tigran123** [comment]
The commit to be reverted is SHA1: f872473604

**Comment by ghost** [comment]
Hmmm... I have no idea how it happens. I guess I've gradually committed the changes to my own repo and not ask anyone about any pull requests.

**Comment by tigran123** [comment]
No problem, I think you just accidentally typed "upstream" instead of "origin" once, so the change went to upstream instead of origin. I sent a pull request which reverts it, so all should be fine.

**Comment by ghost** [comment]
No, I don't... Am I really allowed to commit  to the other's repo in any other way than commiting to my own fork, then sending pull request and finally accepting it?

[UPDATED] I've looked in my repo -- the crereader.lua is 3 days old. But i thought i did refresh it today. It seems that  I'm somehow allowed to commit directly to hwhw / kindlepdfviewer  Never knew about it...

**Comment by tigran123** [comment]
Yes, you have WRITE access now and you can push changes directly to the master tree. However, it is a "custom" not to do that, but submit a pull request and let your fellow collaborators review the code (and even test it if it is critical) and then merge the pull request.

Once (recently, infofont change, remember?) you submitted a pull request and then instantly merged it yourself, this is essentially the same (though physically not quite the same in terms of git transactions) as pushing the change directly to hwhw/master tree. It is best not to do such things but let others review the code and merge it.

For example, I reviewed @dpavlin 's code and then merged his pull request. Does this make me "more senior" than @dpavlin ? Not in the least! No, I recognize @dpavlin 's obvious seniority in KPV development, but as I was the one who reviewed and tested his code (reporting bugs at each iteration) it was natural to let me merge it. And vice versa, when I submit a pull request then @dpavlin or @houqp review it and then merge it (though in this direction one could also say that they review/merge it because of their more senior status in KPV development).

**Comment by tigran123** [comment]
A separate long-term branch is a different issue. For example, I had a branch called "kpdfdjview" (in hwhw tree, not just in my own fork) and to that one I was committing changes without bothering to open pull request for each change. But that was because I was essentially the sole maintainer of kpdfdjview branch and so it was ok.

Btw, my advice on having a separate branch for your InfoMessage:inform() improvements was a good one, it is a pity that you ignored it... I.e. it would have made things easier for you first of all.

**Comment by tigran123** [comment]
And, btw in my above comment one could add "or @NuPogodi" to "... then @dpavlin or @houqp review it and then merge it". I.e. reviewing and merging the code is the peer to peer thing and not "senior to junior" thing. You and I are peers, @dpavlin and @houqp are our seniors, but I see nothing wrong with each of us reviewing/testing/merging the other's pull requests. Problems would arise only if some of us would be too junior/inexperienced to be trusted with this. But I am sure that none of us fall into this category, so it should probably be ok.

**Comment by ghost** [comment]
Ok, now I understood that having a possibility to commit directly to hwhw / kindlepdfviewer I should be at least twice more careful. Till now I just always followed the 3 steps procedure, albeit once accepted my own pull request to correct an evident typo...

**Comment by tigran123** [comment]
Yes, that is why I said nothing at that instance (infofont) as it was an obvious thing and you fixed it several times already :)

**Comment by tigran123** [comment]
Closing the issue as the corresponding pull request was merged into the master.
