### ISSUE TITLE
return to file chooser from opened document

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#34]
It seems that Alt+Back now exists reader, just like Home does. I would love to have ability to return to file chooser without restarting reader.

Maybe shift+Home could bring file chooser instead of exiting?

**Comment by houqp** [comment]
If Alt+Back behaviors the same as 'Home', then maybe this shortcut can just be removed.

**Comment by hwhw** [comment]
Hi, wasn't on purpose. The reader ought to return a boolean to the file chooser that tells whether to continue running. I think I have just messed up and made a typo or something. Will look into that.

**Comment by dpavlin** [comment]
closeDocument return is one to blame :-)

**Comment by dpavlin** [comment]
Alt+Back now exits reader (to be honest I don't understand why since it doesn't touch keep_running which _should_ still be true after break), and Home gets you back to file chooser.

**Comment by hwhw** [comment]
Err, it does? because I've just written a small fix -- the unireader integration sucked up some parts of the exit logic (not in unireader code, but rather in the openFile() in reader.lua)

**Comment by dpavlin** [comment]
Damn. I had similar changes locally, but they where intermingled with lot of print debugs so I didn't commit them :-)
