### ISSUE TITLE
Disabling precaching in two-column mode slows down DjVu enormously.

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#349]
The change that went in the pull request #343 slowed down viewing scanned books (i.e. DjVu files and also some legacy "scanned PDF" files) greatly. Depending on the resolution it can be up to 65 times, see the timings below (on a book scanned at 600dpi with 3677x6418 resolution):

With no pre-caching the times spent in the call to drawOrCache() from show() are:

```
# show()->drawOrCache(93) in 127703 us
# show()->drawOrCache(93) in 1824 us
# show()->drawOrCache(93) in 2045 us
# show()->drawOrCache(93) in 2252 us
# show()->drawOrCache(93) in 2142 us
# show()->drawOrCache(93) in 2176 us
# show()->drawOrCache(93) in 2141 us
# show()->drawOrCache(94) in 138217 us
# show()->drawOrCache(94) in 1890 us
```

And with pre-caching enabled, they are:

```
# show()->drawOrCache(93) in 2428 us
#       preCache->drawOrCache(94) in 139649 us
# show()->drawOrCache(93) in 32297 us
#       preCache->drawOrCache(94) in 8421 us
# show()->drawOrCache(93) in 2082 us
#       preCache->drawOrCache(94) in 1779 us
# show()->drawOrCache(93) in 1877 us
#       preCache->drawOrCache(94) in 1812 us
# show()->drawOrCache(93) in 2142 us
#       preCache->drawOrCache(94) in 1895 us
# show()->drawOrCache(93) in 2162 us
#       preCache->drawOrCache(94) in 1927 us
# show()->drawOrCache(93) in 2070 us
#       preCache->drawOrCache(94) in 1836 us
# show()->drawOrCache(94) in 2103 us
#       preCache->drawOrCache(95) in 134079 us
# show()->drawOrCache(94) in 1555 us
#       preCache->drawOrCache(95) in 1445 us
```

So, turning from page 93 to page 94 without precaching takes 138217 microseconds whereas with precaching it is only 2103 microseconds, i.e. 65 times faster!

I have also found that the behaviour on PDF and DjVu file is different. I.e. for PDF files (I mean typeset PDF files) enabling precaching in two-column mode has no benefit, i.e. the time spent on turning to the next page is exactly the same as without precaching. Maybe that is why @dpavlin disabled it. But for scanned books the benefit of precaching in two-column mode is enormous.

**Comment by tigran123** [comment]
Ah, I suspect I know what is going on here.... The probable reason why pre-cache was disabled was because the actual page rendering done by precache would be useless for us (in those modes where it was disabled). However, page pre-rendering is NOT (for DjVu) the benefit of precaching --- the main time saved is not due to pre-rendering but due to pre-decoding the page, i.e. the work done by :openPage() method in this loop:

```
while (! ddjvu_page_decoding_done(page->page_ref))
        handle(L, doc->context, TRUE);
```

And this page pre-decoding (even if subsequent rendering is useless) is of huge benefit.

**Comment by kai771** [comment]
This might be for another issue, but I'll write it here anyway - cbz files open slower on 2012.09 than on 2012.05. Same goes for turning pages of cbz files. I still have #343 reverted - it doesn't help in this case.

**Comment by tigran123** [comment]
Btw, the code in unireader.lua which is supposed to disable precaching if manual bbox is defined does not seem to work:

```
if self.bbox.enabled and #self.bbox > 0 then
            Debug("no preCache -- using custom bbox")
```

I never get this Debug() message even when I page through the book having defined bbox (and history file shows there is a bbox with entries in it).

**Comment by kai771** [comment]
Oh, and btw, before I start digging for it... is there a way to disable that little square on top of the screen? It stays for some time even after a page is rendered... without it it would seem much snappier.

**Comment by tigran123** [comment]
This is the local function page_render() in UniReader:drawOrCache() in unireader.lua. Just remove it and three calls to it and it will disappear.

**Comment by kai771** [comment]
There is no page_render(), but there is page_indicator()... I suppose that's it :)

**Comment by tigran123** [comment]
Oops, yes, that is what I meant. I actually edited my comment and replaced it with page_indicator() but my internet provider dropped adsl link and so the change wasn't saved. And by the time the link was up I already forgot about it :)

**Comment by tigran123** [comment]
Oh, it dropped it again and SN margin is about 5 (instead of 20 on my line), so looks like they are doing some repairs on the exchange which means I may be off the internet for a couple of days... The cheapest (practically free) providers (TalkTalk in my case) are wonderful when all is fine, but a nightmare when something does go wrong....

**Comment by dpavlin** [comment]
page_indicator shouldn't get stuck. If you see it on screen, kpdf is busy rendering page and won't respond to keypresses until it's finished.

**Comment by tigran123** [comment]
@dpavlin I am glad you are back. I am really curious to know your opinion on the main issue (before my internet completely goes off :)

I.e. with the fact that page pre-decoding is extremely beneficial (for DjVu files) would you agree that we should re-enable pre-caching for two-column mode?

And the second question is why #self.bbox always zero, even when our custom bbox definitely has entries (according to history file). This is why the "no preCache --- using custom bbox" is never reached.

**Comment by kai771** [comment]
No, I didn't mean that it's causing the problem...
What I ment, page is already shown. I get it that it's still busy rendering parts that are not on the screen... but the mere presence of it invokes a feeling that it's slow... I don't know if I explained this properly. It just "feels" snappier without it.

On the other hand, cbz files do open and change pages a lot slower than on 2012.05... with or without indicator :).

**Comment by dpavlin** [comment]
pre-caching in to column mode might help for files which have same margins on all pages and if you don't hit any margin while reading page.

Difference is speed between 2012.05 and 2012.09 version is hard to explain. On one hand we switch to luajit, and I don't really know if that might have negative impact (I suspect not). However, this is first release compiled with older toolchain `x-tools-glib2.5` and @hwhw used newer toolchain for previous releases, and this might explain difference.

**Comment by kai771** [comment]
I don't think it's TC related... Reverting changes in #343 gave back the speed of 2012.05 for scanned pages in pdf files. Cbz should also be handled by muPDF, right? I can't be sure, of course, but I do think it's not TC's fault.

I can always compile it with CS 2012.03 and see, but it's kinda late now... will have to wait till tomorrow.

**Comment by dpavlin** [comment]
I will revert #343 4d187aad4ee49a20254048ca301119176b54039b until we understand this better.

**Comment by tigran123** [comment]
@dpavlin Thank you.

**Comment by kai771** [comment]
It's definitely not TC. I didn't try it with CS 2012.03, but I had a copy of tigrans build of 09.09.2012, v2. It's normal there too. I know he also uses x-tools, so it's definitely not TC.

**Comment by tigran123** [comment]
@kai771 Yes, we understand that, thank you. Looking at the timings I have shown at the very top of this issue makes it clear too. However, what @dpavlin is saying is that we need to understand deeper the underlying code and the safest and wisest first step is to revert it to the working state and then try to understand what is going on. I totally agree with him.

Also, I have explained (admittedly for DjVu files only) how page pre-decoding (indirectly done via our precaching that calls openPage() method) can have enormous benefit in any mode, including two-column one.

**Comment by tigran123** [comment]
@kai771 btw, you have not yet confirmed explicitly whether reverting the "don't precache in two-column mode" change solves the cbz issue too.

**Comment by kai771** [comment]
@tigran123 I totally agree with dpavlin too. Since he suggested that it might be because of the TC, I wanted to make sure it's not the problem. And, since I tried it with your build of 09.09.2012., it's clearly not luajit either.

In response to your previous post:
"This might be for another issue, but I'll write it here anyway - cbz files open slower on 2012.09 than on 2012.05. Same goes for turning pages of cbz files. I still have #343 reverted - it doesn't help in this case."

It clearly says, that #343 is reverted, and that cbz files open slowly, does it not?

To help you even further, I happened to find dpavlins bild of 10.09.2012. It's slow too on that build. Furthermore, I installed your build of 09.09.2012, and coppied over unireader from dpavlins build of 10.09.2012. and it got slow. I think it's safe to coclude that the bug was introduced here. Here's a diff between that 2 versions of unireader.lua:

--- unireader.lua.0909  2012-09-09 20:43:14.000000000 +0200
+++ unireader.lua.0910  2012-09-09 21:44:05.000000000 +0200
@@ -1046,6 +1046,14 @@
    -- #3 goal: we render the full page
    -- #4 goal: we render next page, too. (TODO)
-   local pg_w = G_width / ( self.doc:getPages() )
-   local page_indicator = function() 
-       fb.bb:invertRect( pg_w*(no-1),0, pg_w,10)
-       fb:refresh(1,     pg_w*(no-1),0, pg_w,10)
-       Debug('page_indicator',no)
-   end
-   page_indicator()
  +
  -- ideally, this should be factored out and only be called when needed (TODO)
  local ok, page = pcall(self.doc.openPage, self.doc, no)
  local width, height = G_width, G_height
  @@ -1083,6 +1091,9 @@
              self.cache[pagehash].ttl = self.cache_max_ttl
          end
          -- ...and return blitbuffer plus offset into it
  +
- ```
        page_indicator()
  ```
  
  +
          return pagehash,
              offset_x_in_page - self.cache[pagehash].x,
              offset_y_in_page - self.cache[pagehash].y
  @@ -1145,6 +1156,8 @@
  page:draw(dc, self.cache[pagehash].bb, 0, 0, self.render_mode)
  page:close()
-   page_indicator()
  +
  -- return hash and offset within blitbuffer
  return pagehash,
      offset_x_in_page - tile.x,
  @@ -1556,7 +1569,7 @@
  function UniReader:modifyGamma(factor)
    Debug("modifyGamma, gamma=", self.globalgamma, " factor=", factor)
    self.globalgamma = self.globalgamma \* factor;
-   showInfoMsgWithDelay("New gamma = "..self.globalgamma, 1000, 1)
-   InfoMessage:show("New gamma = "..self.globalgamma, 1) -- we don't want delay here
  self:redrawCurrentPage()
  end

I hope it helps to resolve this quickly.

Update: Damn, markup got it... :(

**Comment by dpavlin** [comment]
This makes a lot of sense. eink refresh twice for each page has significant impact. In my defense, I usually use DXG with huge documents so it's slow always and I spent most of my time developing and not reading so I didn't noticed difference. Thanks @kai771 for bisecting this one.

**Comment by tigran123** [comment]
This fix was merged already, so closing the issue.
