### ISSUE TITLE
implement manual page crop

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#35]
Some pdf files have bounding boxes totally wrong. djvu doesn't have it at all. Before I started using this reader, I was cropping pdfs manually to provide better experience, but now I can code that in lua :-)

Idea is to provide manual margins (with option to specify different ones for odd and even pages) and use that instead of page:getUsedBBox values. This would make two-column mode and all fit-to-content zoom levels work automatically.

To implement it, I would need a way to draw lines over rendered pdf page. Something like xor 0xff might be perfect, since I could just re-draw line if I move it. I did a quick look in blitbuffer.c, and it seems to me that I need paintRect which will do XOR with value, so I will give my rusty C knowledge a spin.

**Comment by houqp** [comment]
Great feature.

I crop pdfs manually before sending to kindle too, which is tedious.

Just one suggestion. It will be better if it supports cropping for even pages and odd pages separately.

**Comment by dpavlin** [comment]
I would probably just save cropping in local file setting and use last available odd or even crop. If coupled with user interface for "recall crop from page xx" it would provide easy way to define cropping I think.

This crop data can afterwards be used to crop pdf on desktop to perfect shape :-)

**Comment by dpavlin** [comment]
I have plan to also implement cropping which isn't based on currently visible area, but on separate top/bottom, left/right margins but that shouldn't block next release #46

**Comment by houqp** [comment]
That might be better indeed.

**Comment by eLiNK2gl** [comment]
I just would like to make a suggestion as to the possible implementation. Feel free to ignore it if it does not fit into your framework.

Currently shift or alt are to be used in combination with the five-way to pan around.
It is considered by many (me including) as too imprecise.

So, I thought that maybe the following idea would fill the bill.
By, say, pressing 'P' you enter a special panning mode.
In this mode, a grid is overlaid over your page (from a pdf or djvu file), which essentially shows you the boundaries of the page you can move to. These boundaries are be effective upon a consecutive pressing of a number and a five-way key.

E.g. if you press '1' and the five-way key to the left, the page is panned by say 100 pixels to the left.
If you press '2' and the five-way key to the left, the page is panned by 90 pixels to the left, and so on.
To make sure the display is not cluttered you can only draw 5 lines (every second line corresponding to 1,3,5,7, and 9) on each side of the display.

What do you think?

**Comment by dpavlin** [comment]
@eLiNK2gl would you give it a try? I did variant of your idea which shows ruler with multiple steps which cover all alphabetic keyboard. I hope that you like it anyway :-)

**Comment by eLiNK2gl** [comment]
actually, I liked it quite a lot. A very nice implementation.
But I think the choice of font size for the lettering would be criticized.

**Comment by houqp** [comment]
Why? Too small?

**Comment by eLiNK2gl** [comment]
yes.
But maybe the time has come for me to think about using glasses while reading. :)
