### ISSUE TITLE
hotkeys for pdf links are 'out of focus' in some modes

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#351]
take https://github.com/downloads/tigran123/russian-synodal-bible/Russian-Synodal-Bible-USletter-twocolumn.pdf
change to 'Shift +A'
Press 'L'
Observe that hotkeys are not at proper positions

I am almost sure this was not an issue after the first implementation of the feature.

P.S.: Release 2012.09

**Comment by tigran123** [comment]
Reproduced and labeled as bug.

**Comment by tigran123** [comment]
Strangely, in other zoom modes it works correctly.

**Comment by tigran123** [comment]
@eLiNK2gl  No, the bug is also present in the initial implementation. I have just tested with 27 Sep 2012 build:

https://github.com/downloads/tigran123/kindlepdfviewer/kindlepdfviewer-cc1ab45.zip

**Comment by dpavlin** [comment]
`screenOffset` seem to return different values when showing link indication (underline) and when drawing link shortcuts.

**Comment by dpavlin** [comment]
There is another nice example: go to page 1 of document and show bounding box with `x`. You will see box shifted right. I guess that we have similar problems with highlighting because they all use `zoomedRectCoordTransform` which is affected by it.

Still nothing to merge, BTW

**Comment by tigran123** [comment]
The fix merged into master, closing the issue.
