### ISSUE TITLE
Misuse of Lua local scoping in our command handlers?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#358]
Let us look at any command handler in unireader.lua, for example "goto page" (search for KEY_G). It should refer to `unireader.pageno` and not `self.pageno`. The latter would also work because of the local scoping of local functions in Lua (i.e. `self` is also visible), but logically it should be the former. And the same applies to all other handlers in that same list that refer to `self` instead of `unireader`. But maybe I misunderstood something, so I am asking here to confirm. I have only tested this for "goto page" handler, not all the others.

**Comment by houqp** [comment]
I have pointed this out when @traycold first implement the command module. i.e. we can use closure to get access to self thus pass unireader to the handler is some what redundant. But maybe it might make the code harder to understand, so I am not sure whether it is a good idea.

**Comment by houqp** [comment]
For now, maybe we should just change that self to unireader since it requires much less work ;P

**Comment by tigran123** [comment]
Well, what about the instances where we have `function(unireader,keydef)` --- in those cases presumably one has to leave `self` alone, as it must refer to UniReader object, right?

**Comment by houqp** [comment]
Um.. I don't quite get what you mean ;P

`unireader` and `self` should all refer to UniReader object I guess. So using either one should be fine.

**Comment by tigran123** [comment]
At line 2269 in unireader.lua we have this:

```
        function(unireader,keydef)
            if keydef.keycode == KEY_PGFWD or keydef.keycode == KEY_LPGFWD then
                unireader.step_manual_zoom = unireader.step_manual_zoom * 2
                self.settings:saveSetting("step_manual_zoom", self.step_manual_zoom)
                --showInfoMsgWithDelay("New zoom step is "..unireader.step_manual_zoom.."%. ", 2000, 1)
            else
                local minstep = 1
                if unireader.step_manual_zoom > 2*minstep then
                    unireader.step_manual_zoom = unireader.step_manual_zoom / 2
                    self.settings:saveSetting("step_manual_zoom", self.step_manual_zoom)
                    --showInfoMsgWithDelay("New zoom step is "..unireader.step_manual_zoom.."%. ", 2000, 1)
                else
                    showInfoMsgWithDelay("Minimum zoom step is "..minstep.."%. ", 2000, 1)
                end
            end
        end)
```

The above mixes references to `self.step_manual_zoom` and `unireader.step_manual_zoom`. What should be the correct references?

**Comment by houqp** [comment]
I think both of them are correct in that case. We might want to stick to `unireader` for the command handler because: 1) it involves less changes. 2) someone who does not know closure can still understand the code.

**Comment by tigran123** [comment]
OK, closing for now as it is clear to me but is too "cosmetic" to bother to do anything about it....
