### ISSUE TITLE
Can't open any PDF files

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#359]
With the current build using x-tools we cannot open any PDF files. (this has nothing to do with TTS enabled, I just happened to have it enabled at the time, but reproducible with it disabled too. The same issue as I mentioned before "invalid page size in page 1" errors from mupdf and then lockup, so I have to hard-reset the Kindle).

So we need either:

a) clear instructions on upgrading TC to a more recent one.

b) undo the recent optimizations in the Makefile in order to work with x-tools TC.

**Comment by NiLuJe** [comment]
I'll add some more explicit flags when I get back, see if it helps.

But, yes, will also provide TC instructions, because I'm pretty sure the one you're using generates binaries that won't work on a K2.

**Comment by tigran123** [comment]
Ok, excellent, thank you very much! :)

**Comment by tigran123** [comment]
Just for completeness let me mention the exact messages in the crash.log I get when compiling the current state of KPV with x-tools:

```
warning: cannot find page size for page 1
warning: invalid page size in page 1
```

And then total lockup: can't go to screensaver or connect via usb --- only hard reset of device will help.

These are exactly the same symptoms as what I got when blindly (apart from a typo fix) applying @NiLuJe 's makefile-mangling patch a couple of days ago. I assume that changing mupdf compilation is dangerous. I could track it down and say which changes need to be reverted, but a better solution would be to upgrade the TC to the more recent and recommended by @NiLuJe so I shall patiently wait for his instructions.

Also, if we are all building with the same TC then it would make the development much smoother.

**Comment by NiLuJe** [comment]
Huh. Surprisingly enough, it does work on a K2. It shouldn't, though: 2.6.26 > 2.6.22.

**Comment by tigran123** [comment]
Well, I get this when building with 2012.03:

```
./kpdfview: /lib/libm.so.6: version `GLIBC_2.15' not found (required by ./kpdfview)
```

This is without your `-mfloat-abi=softfp -marm` change. trying with it now...

Even though I added -DGNU_SOURCE (as per @kai771 recommendation) and also passing all the stuff to djuvulibre build as per one of your commits in your fork).

**Comment by tigran123** [comment]
I meant `-D_GNU_SOURCE` of course. Btw, without it I would get GLIBC_2.17 error as well.

**Comment by NiLuJe** [comment]
@tigran123 : I'll go get 2012.03 (and whatever the latest one might be) to check it out myself ;).

**Comment by tigran123** [comment]
That is the latest, I'll test your softabi change right now.

**Comment by NiLuJe** [comment]
Indeed! Downloading right now ;). ... and building thirdparty...

**Comment by tigran123** [comment]
No, I still get the same:

```
./kpdfview: /lib/libm.so.6: version `GLIBC_2.15' not found (required by ./kpdfview)
```

My changes to Makefile are:

```
-BASE_CFLAGS:=-O2 -ffast-math -pipe -fomit-frame-pointer -fno-stack-protector -U_FORTIFY_SOURCE
+BASE_CFLAGS:=-O2 -ffast-math -pipe -fomit-frame-pointer -fno-stack-protector -U_FORTIFY_SOURCE -D_GNU_SOURCE
-ARM_ARCH:=-march=armv6j -mtune=arm1136jf-s -mfpu=vfp
+ARM_ARCH:=-march=armv6j -mtune=arm1136jf-s -mfpu=vfp -mfloat-abi=softfp -marm
 ifdef EMULATE_READER
-       cd $(DJVUDIR)/build && ../configure --disable-desktopfiles --disable-shared --enable-static --disable-xmltools --disable-largefile
+       cd $(DJVUDIR)/build && CC="$(HOSTCC)" CXX="$(HOSTCXX)" CFLAGS="$(HOSTCFLAGS)" CXXFLAGS="$(HOSTCFLAGS)" LDFLAGS="$(LDFLAGS)" ../configure --disable-desktopfiles --dis
 else
-       cd $(DJVUDIR)/build && ../configure --disable-desktopfiles --disable-shared --enable-static --host=$(CHOST) --disable-xmltools --disable-largefile
+       cd $(DJVUDIR)/build && CC="$(CC)" CXX="$(CXX)" CFLAGS="$(CFLAGS)" CXXFLAGS="$(CXXFLAGS)" LDFLAGS="$(LDFLAGS)" ../configure --disable-desktopfiles --disable-shared --
 endif
```

**Comment by NiLuJe** [comment]
@tigran123 : Confirmed. I'll look into it. (It's also about 1MB larger than with my own TC, so, yeah, I'll hunt that down).

**Comment by tigran123** [comment]
@NiLuJe  Great, thank you!

**Comment by NiLuJe** [comment]
Yup, got it. libm pulls some finite math functions, because MG asks for it with -ffinite-math-only because of -ffast-math.

(Did I mention how much I love readelf & gcc -Q -v? because I do ^^)

I'll try to neuter it (hopefully without getting rid of ffast-math entirely) ;).

**Comment by tigran123** [comment]
Wonderful, you caught it incredibly fast! :)

**Comment by tigran123** [comment]
I love readelf too --- without it I woudn't have written /proc/kcore in Linux :)
(and much of iBCS stuff too :)

Btw, when installing FC17 I looked at some modern web page that talks about optimizing FC17 boot and noticed it recommended using "rootfstype=" boot parameter for forcing the filesystem type. It brought back nostalgic memories and I thought "interesting, I did something for some purpose and 15 years later it is used for something completely different, but very useful nevertheless" :)

**Comment by NiLuJe** [comment]
Okay! That was it! readelf now looks okay. Will check if it actually doesn't blow up on my K2....

It's still roughly 800KB larger than what I end up with my TC, so I have some more stuff to check before sending the PR...

EDIT: Seems to be okay on my K2, yay. Now to see why it's been eating ALL THE COOKIES! ...

**Comment by tigran123** [comment]
Excellent. And if it reads PDF files too --- that would be a very nice bonus! :)

**Comment by NiLuJe** [comment]
Hmm. Definitely still 800KB larger... Let's hear it for GCC 4.7?

I'm doing one final build/emu build to check, and then it's PR time!

(Also, I ran into (the usual) parallel build issues with MG, so, err if fails with strange errors, try again with a single job: make -j1 thirdparty instead) [that's of course if you were running make with multiple jobs before, as I was ^^].

**Comment by tigran123** [comment]
I wouldn't worry about the size too much --- can we actually read PDF/DjVu files on K3 with your fixes?

**Comment by tigran123** [comment]
No, I was running a single job (except Linux kernel I wouldn't trust other software to handle parallel builds correctly :)

**Comment by NiLuJe** [comment]
@tigran123 : Yup, works fine on my K2/K3 & in EMU mode. I'll prepare the PR ;).

Yeah, the parallel build issues are usually pretty recognizable, I was just mentioning it since I switched make to $(MAKE) to actually be able to use it, and I had a streak of luck with my own TC and -j2 that didn't last ;).

**Comment by tigran123** [comment]
Thank you! Btw, your PRs are exemplary in that they contain multiple commits with each one containing one logically autonomous change. Even if some patches then revert the changes made by previous patches --- still it is much easier to review than bundling tons of changes into a single commit. I wish everyone was as meticulous :)

**Comment by NiLuJe** [comment]
@tigran123 : Everyone has his own style, and I tend to go on the extreme side of 'a lot of small commits with more comments than code'... ^^

I actually like to commit (heh) to memory (nearly) every attempts, and the commit logs usually provide me with the reasoning behind the changes when I review the stuff later on. That helps me avoid wondering why the hell I did something when looking at the code two weeks later ^^. It also makes git/svn log/blame tremendously more helpful.
