### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by traycold** [koreader/kindlepdfviewer#37]
when making the project (in EMULATE_READER mode), i have to lauch make three time, since it goes in error the first two times. I don't know if it's an issue of my specific environment, or something wrong with makefile.

```
user@compilebox:~/kindle/git/kindlepdfviewer-traycold$ make clean
rm -f *.o kpdfview
user@compilebox:~/kindle/git/kindlepdfviewer-traycold$ make
gcc -c -O3 -Ilua/src -Imupdf/ -Iluafilesystem/src kpdfview.c -o kpdfview.o
gcc -c -O3 -Ilua/src -Imupdf/ -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -DEMULATE_READER -DEMULATE_READER_W=412 -DEMULATE_READER_H=600 \   einkfb.c -o einkfb.o
gcc:    : No such file or directory
make: *** [einkfb.o] Error 1
user@compilebox:~/kindle/git/kindlepdfviewer-traycold$ make
gcc -c -O3 -Ilua/src -Imupdf/ -Iluafilesystem/src pdf.c -o pdf.o
pdf.c: In function ‘openDocument’:
pdf.c:65: warning: passing argument 2 of ‘pdf_authenticate_password’ discards qualifiers from pointer target type
mupdf/pdf/mupdf.h:370: note: expected ‘char *’ but argument is of type ‘const char *’
gcc -c -O3 -Ilua/src -Imupdf/ -Iluafilesystem/src blitbuffer.c -o blitbuffer.o
gcc -c -O3 -Ilua/src -Imupdf/ -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -DEMULATE_READER -DEMULATE_READER_W=412 -DEMULATE_READER_H=600 \   input.c -o input.o
gcc:    : No such file or directory
make: *** [input.o] Error 1
user@compilebox:~/kindle/git/kindlepdfviewer-traycold$ make
gcc -c -O3 -Ilua/src -Imupdf/ -Iluafilesystem/src util.c -o util.o
gcc -c -O3 -Ilua/src -Imupdf/ -Imupdf/thirdparty/freetype-2.4.8/include ft.c -o ft.o
ft.c: In function ‘newBuiltinFace’:
ft.c:73: warning: passing argument 1 of ‘pdf_find_builtin_font’ discards qualifiers from pointer target type
mupdf/pdf/mupdf.h:622: note: expected ‘char *’ but argument is of type ‘const char *’
gcc -c -O3 -Ilua/src -Iluafilesystem/src luafilesystem/src/lfs.c -o lfs.o
gcc -c -O3 -Ilua/src -Imupdf/ -Idjvulibre/ djvu.c -o djvu.o
gcc -lm -ldl -lpthread -L/usr/lib -lSDL -lstdc++ \
        kpdfview.o \
        einkfb.o \
        pdf.o \
        blitbuffer.o \
        input.o \
        util.o \
        ft.o \
        lfs.o \
        mupdf/build/debug/libfitz.a \
        mupdf/build/debug/libfreetype.a mupdf/build/debug/libjpeg.a mupdf/build/debug/libopenjpeg.a mupdf/build/debug/libjbig2dec.a mupdf/build/debug/libz.a \
        lua/src/liblua.a \
        djvu.o \
        djvulibre/build/libdjvu/.libs/libdjvulibre.a \
        -o kpdfview
lua/src/liblua.a(loslib.o): In function `os_tmpname':
loslib.c:(.text+0x46): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
user@compilebox:~/kindle/git/kindlepdfviewer-traycold$ 
```

**Comment by hwhw** [comment]
Hm, funny issue you have there. And I have absolutely no idea how to approach it... needless to say that I certainly do not have these problems...

**Comment by houqp** [comment]
Make complains `make: *** [input.o] Error 1` and you still got `input.o` compiled?

**Comment by dpavlin** [comment]
I compile with following snippet:

pdf=$1
test -z "$pdf" && pdf=~/Downloads/pdf/
file kpdfview | grep Intel || make clean cleanthirdparty
EMULATE_READER_W=600 EMULATE_READER_H=800 EMULATE_READER=1 make kpdfview
./reader.lua -d emu $pdf

and cross-compile with following one:

export PATH=/home/dpavlin/t61p/k3libre/x-tools-glib2.5/arm-kindle-linux-gnueabi/bin/:$PATH
file kpdfview | grep ARM || make clean cleanthirdparty
make customupdate CC=arm-kindle-linux-gnueabi-gcc

we might have dependency problem, since I don't have any problems, but than again, I do clean before compile, mostly because I'm switching between local and cross-compile a lot.

**Comment by houqp** [comment]
Just a little bit OT. 

Maybe we should introduce autotools to make remote build possible. This will be handy for switching between local and crosscomplie builds. I find it quite CPU and TIME wasting to keep building this two version from scratch :P

**Comment by houqp** [comment]
um... this happen to me today after I pulled down latest codes. Fix added to my pull request.

**Comment by traycold** [comment]
> we might have dependency problem, since I don't have any problems, but than again, I do clean before compile, mostly because I'm switching between local and cross-compile a lot.

Just to be more precise about the snippet i posted:
- I'm referring to compilation in mode `EMULATE_READER=1`;
- I also launched `clean` before make;
- after third launch of `make` i'm indeed able to successfully exeture kpdfview in emulation mode;
- this issue doesn't occur when compiling for kindle; i use scratchbox, set up for `arm` to do this (thus i posted my little mod on `Makefile`, to use standard compiler executables in case we are using scratchbox);

> um... this happen to me today after I pulled down latest codes. Fix added to my pull request.

Thank you for the fix; tonight i will try it.

**Comment by traycold** [comment]
hi, the issue is fixed after commit by **houqp**
