### ISSUE TITLE
Wrong output of `git describe HEAD` on the master branch?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#378]
I have just done a clean "git clone" followed by "make fetchthirdparty" etc etc all the way to "make customupdate" and the resulting package had a very strange filename:

`kindlepdfviewer-v2012.04.2-501-gf7040b3.zip`

so I checked `git describe HEAD` and indeed it says `v2012.04.2-501-gf7040b3` but in the old tree it said things like `v2012.09-90-g89dbe7a`. So, what should I do to have the correct (v2012.09*) output of `git describe`? I don't want my builds (to go into Downloads) to look like based on some ancient "2012.04" code...

**Comment by dpavlin** [comment]
`git describe` uses annotated tags (added with `git tag -a` as opposed to just `git tag`. Would `git fetch upstream  -tags` help ?

**Comment by tigran123** [comment]
@dpavlin Yes, thank you, running `git fetch upstream --tags` did the trick, now `git describe` output is good! :)
