### ISSUE TITLE
status font should use document font in crereader

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#388]
I'm using kpv to read a Chinese epub book. kpv can select any user customized font, but the status screen was using fixed font which cannot display Chinese characters, so the Chapter name will not be displayed.

It'll be better to let the status screen use the document font, so it can display chapter name in any language. Or if that have difficulties, as least use some droid font that support CJK.

The height of status line probably need to increase too, current height is too small for Chinese characters.

**Comment by tigran123** [comment]
When you are in filemanager press `F` and then `E` to select the font for `rifont` (reading position info). Then select the font which has CJK support from the list. If no such font appears then you have to copy it manually to your Kindle, remember to put it into kindlepdfviewer/fonts directory and observe the same naming convention (for Italic, Bold etc) as the fonts already there. Then it will work.

**Comment by dracodoc** [comment]
Sorry I don't know this exist! It works, no problem.
