### ISSUE TITLE
Can crereader just discard the bottom half line?

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#389]
For zoom and pan in scanned pdf, a gray shade is helpful to tell the edges. But for text based epub, the bottom half line is not so right. None of any other epub/mobi reader will have this effect.

Is it possible to just discard the last half line if the space is not enough for a whole line? There is really no need for a half line to remind what the last sentence of last page is, we have been reading book without that hint forever.

**Comment by tigran123** [comment]
During the normal course of reading there is no such line at the bottom. It is only if you press page `Prev` then it appears to show that that bit of text was already shown on the previous page i.e. to show the overlap between screens.

And in normal course of reading (i.e. pressing page `Next`) you get the grey line at the top to show the overlap. It may not seem needed to you if you read a continuous text but if you have formulas or other complex items you may not easily remember what you were just reading and so the grey overlap area serves as a reminder. Also, it helps to decide if you need to use the fiveway panning to get the item completely into the view if it was split across two screens.

**Comment by tigran123** [comment]
Well, if you really want this feature I can implement it as a configurable.

I see that @kai771 also provided this (as a hack), so presumably many people want it. And it is very easy to implement both for books (PDF/DjVu) and ebooks (MOBI/ePub/fb2/etc).

**Comment by tigran123** [comment]
Ok, this feature is in the PR #395

**Comment by dracodoc** [comment]
Thanks a lot!
I believe many people will feel this more natural, and make it configurable is certainly the best method.

**Comment by dracodoc** [comment]
I checked the newest build, the configuration method is good, but it just turn off the gray shade while I was suggesting remove the half line from the view all together... I think user reading a text book should not see any half cut line in page top or bottom, which is not seen in any other reading apps.

However to detect if there is a half line in top or bottom may not be easy, and it involves to move the discarded bottom line to next screen, so it is a complicated issue.

Anyway the current implementation is acceptable, just maybe not perfect for some people.

**Comment by tigran123** [comment]
@dracodoc Yes, your understanding is correct. What you originally suggested is not only too complex but also a bad idea in terms of performance, i.e. it would require shifting the WHOLE TEXT (i.e. the remainder of it from the current point to the end) up and down (which may take a minute for a huge book) on every page turn which obviously is unacceptable, i.e. too slow.
