### ISSUE TITLE
djvu support is broken in 3.2.1 firmware

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#39]
ELiNK reports that djvu files cannot be opened in 3.2.1 firmware. When selected a book, kpdfview exits and launchpad displays "Success!".

Do any of you has a 3.2.1 firmware for testing?

**Comment by traycold** [comment]
I opened a DJVU document on my Kindle DXG updated on firmware 3.2.1 without any problem, building with latest sources as of now.

**Comment by houqp** [comment]
> I opened a DJVU document on my Kindle DXG updated on firmware 3.2.1 without any problem, building with latest sources as of now.

That's strange. Then what might cause crash? Custom hacks? Maybe we need debug dump in the program to help testing.

Close this issue for now.
