### ISSUE TITLE
adding bookmark in crereader cause refresh first

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#390]
When reading an epub, adding bookmark will cause a global refresh first, then pop up the "bookmark added" dialog, then the dialog disappears with no refresh. The first refresh seemed meaningless. If the page is already bookmarked, there is no this refresh, the dialog just pop up then disappear.

This behavior doesn't appear in pdf.

**Comment by tigran123** [comment]
Interesting, thank you, I will have a look.

**Comment by tigran123** [comment]
Thank you, it was a bug indeed and the fix is in the PR #393

And thanks again to you --- your findings and comments are most helpful and productive! :)

**Comment by dpavlin** [comment]
#393 merged into master
