### ISSUE TITLE
How make kpdfv on DXG partial refresh ?

### ISSUE THREAD

**Issue by kaysin** [koreader/kindlepdfviewer#391]
I try to add 'partial_refresh_count' into .reader.setting.lua .but it doesn't work..  

My setting file is following ........... Please HELP ~~

-- we can read Lua syntax here!
return {
    ["lastfile"] = "/mnt/us/documents/Prentice Hall.-.The C Programming Language(2nd Edition).pdf",
    ["version"] = 2012.05,
    ["pan_overlap_vertical"] = 30,
    ["fontmap"] = {
        ["hfont"] = "host/CJK.ttf",
        ["infont"] = "host/CJK.ttf",
        ["rifont"] = "host/CJK.ttf",
        ["hpkfont"] = "host/CJK.ttf",
        ["infofont"] = "host/CJK.ttf",
        ["ffont"] = "host/CJK.ttf",
        ["cfont"] = "host/CJK.ttf",
        ["scfont"] = "host/CJK.ttf",
        ["tfont"] = "host/CJK.ttf"
    },
    ["filemanager_expert_mode"] = 2,
    ["partial_refresh_count"] = 5
}

**Comment by tigran123** [comment]
In a good application (like KPV) there is no need to edit any settings files manually.
When you open a file please press `H` to get the help and then read the help page. You will discover that the answer to your question is in the hotkey `Shift-R`. Oh, I just checked it myself and see that it doesn't actually explain `Shift-R` properly --- I will fix the help page now, thanks for bringing this up! :)
