### ISSUE TITLE
How to use git-rev content to generate a source diff?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#402]
Presumably we store the output of `git describe HEAD` in git-rev file so we can easily see the state of the sources the distribution was built from? But how do we actually do this? I.e. how to generate `git diff` output between the current master and git-rev value of `v2012.09-114-gcb25029`?

**Comment by dpavlin** [comment]
`git diff upstream/master v2012.09-114-gcb25029` should be enough. You can also add path as last argument. Does this help or did I misunderstand your question?

**Comment by tigran123** [comment]
Yes, thanks. I thought I tried it, but obviously I did something different because it didn't work :)
