### ISSUE TITLE
Shoule we add a new zoom mode or change current fit to content mode?

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#41]
Currently, fit to content width/height mode is not so useful for my k3. Every time I press the shortcut, it is zoomed, but offset is set to the middle of the page. But what I want is to read from the beginning. And I cannot use other keys to navigate inside the page. I am kind of trapped in the middle.

I think a more useful mode will be something like this:

zoom to fit content width, set offset to the beginning. And when you press `PGFWD`, it jump to next part of current page. If reached page bottom, then do a real page turn. Just like the native reader does.

**Comment by dpavlin** [comment]
We could turn on navigation rather easy, but I would agree that it would make sense that zoom to page/content width should position view on top of page. @hwhw do you agree with me?

**Comment by hwhw** [comment]
Makes perfect sense to me. In fact, centering makes no sense :-) I guess it's a leftover from the time when only zooming was implemented, but navigation wasn't. Which reminds me: I wanted to implement a better pre-caching for zoomed pages. But I'll open another issue for that.

**Comment by houqp** [comment]
mode added, close for now
