### ISSUE TITLE
How to override some UniReader defaults in PICViewer module?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#427]
I thought that to override the default values of UniReader object all I have to do is this:

```
PICViewer = UniReader:new{
    show_overlap_enable = false,
    show_links_enable = false,
}
```

But it doesn't work. So, then I tried to define an :init() function like this:

```
function PICViewer:init()
    self.show_overlap_enable = false
    self.show_links_enable = false
    self:addAllCommands()
end
```

Still doesn't work, i.e. when I press `Shift-L` it actually turns OFF `show_links_enable` instead of turning them ON. So, how do I change the UniReader's defaults in a specific reader, in this case PICViewer?

**Comment by houqp** [comment]
Actually, both way will work. You can verify it by printing `self.show_links_enable` in the init method. The real cause of this bug is the code that reads setting in `unireader`:

``` lua
self.rcountmax = self.settings:readSetting("rcountmax") or self.rcountmax
self.show_overlap_enable = self.settings:readSetting("show_overlap_enable")
self.show_links_enable = self.settings:readSetting("show_links_enable")
```

`self.settings:readSetting("show_links_enable")` will always return true and overwrite the variable. The problem here is why it always return `true`... I have too go to bed now ;p see if we can figure this out tomorrow :)

**Comment by tigran123** [comment]
The `self.settings:readSetting("show_links_enable")` will only return true if there is no value of `show_links_enable` in the history file. But if there is a value and it is false, then this function will return false.

**Comment by tigran123** [comment]
I think the `self.settings:readSetting("show_links_enable")` should return `nil` if there is no value in the history file. And the code to load the setting should be modified to check for this:

```
self.show_links_enable = self.settings:readSetting("show_links_enable") or self.show_links_enable
```

But this is a dangerous change because it would require checking all the callers of `self.settings:readSetting()`. For example, the `show_overlap_enable` should also be updated to:

```
self.show_overlap_enable = self.settings:readSetting("show_overlap_enable") or self.show_overlap_enable
```

**Comment by houqp** [comment]
Yes `nil` is what it is supposed (and it did before) to return when no value in the hist file, we do all these kind of checks for previous `self.settings:readSetting()` calls. I just have no idea when it started to return `true`...

**Comment by tigran123** [comment]
Interestingly, for integer-valued configurables (like rcountmax) that is exactly what it does, i.e. returns `nil` if there is no value in the history file. So we need to find out why for boolean configurables it has a different behaviour.

**Comment by tigran123** [comment]
Hmmm, wait... Now I have rested it and it seems to work! :)

**Comment by tigran123** [comment]
Ah, no, it would work for letting PICViewer override them correctly, but it would break because the wrong value for non-pic items (PDF, DjVu) would be loaded. So there is still a problem.

**Comment by tigran123** [comment]
I have to go now, so I'll have a look at this later (or tomorrow) unless someone beats me to it.

**Comment by tigran123** [comment]
Actually, maybe it still returns `nil` but we are just doing the wrong check. I.e. instead of saying:

```
self.x = readSetting("x") or self.x
```

we should be explicitly checking for `nil`, i.e. like this:

```
local tmp = readSetting("x")
if tmp ~= nil then
   self.x = tmp
end
```

I will test this idea now and see if it was the right guess or not.

**Comment by tigran123** [comment]
Yes, it works. I will test it a abit and then will send a PR.

**Comment by tigran123** [comment]
Actually, there is another bug there, in the inputLoop() we have to reset the values to defaults, otherwise the previous value is kept (for a given object, i.e. for all DjVu files or all PDF or all cre-files) between close/open of the document. So, my PR will fix two bugs.

**Comment by houqp** [comment]
This is very strange, I also tested with `self.rcountmax`.

I don't understand why assigning `nil` to an entry in `self` table won't turn that entry into `nil`. Instead, `self.rcountmax` is changed to `0` and `self.show_link_enable` is changed to `true`. While assigning `nil` to local var works....

**Comment by tigran123** [comment]
Just for the record, the PRs to address what was discussed here are #432 and #434

**Comment by dpavlin** [comment]
merged into master, so closing
