### ISSUE TITLE
copying files to clipboard not possible

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#429]
Procedure:
1) select a directory with a long list
2) go to the second page
3) select the first or the second file
4) press shift + X 
5) watch the message 'Unsupported function!'

**Comment by tigran123** [comment]
Bug confirmed, I'll deal with it, as I have been looking at this code just yesterday.

**Comment by tigran123** [comment]
Btw, the bug is present before my yesterday's changes as well.

**Comment by tigran123** [comment]
Ok, fixed. It was introduced recently, but, fortunately, this particular code is readable and so the fix is straightforward. I'll test it thoroughly and put out a PR. Thanks for finding this bug.

**Comment by dpavlin** [comment]
merged into master
