### ISSUE TITLE
move third-party git checkouts into submodules

### ISSUE THREAD

**Issue by traycold** [koreader/kindlepdfviewer#43]
Was: Should we include a git pull when compiling third party libs?

Since mupdf, djvulibre and luafilesystem are cloned from their git repositories with target `fetchthirdparty`, I think adding a `git pull` statement within target `makethirdparty` could help having more consistent builds (at least, not dependend on when last executed target `fetchthirdparty`)

**Comment by dpavlin** [comment]
That would make makethirdparty tareget dependent on network, which is unfortunate because we call it when switching from emulation mode to cross-compile which would introduce additional network delay and it would break build when not connected to network.

**Comment by traycold** [comment]
you're right.
So maybe another approach could be: in target fetchthirdparty, specify the exact commit we want to use, and not just HEAD, when cloning repos. So we are sure that everyone that builds the project, independently by the time it execute the target fetchthirdparty, will get the same code of the third-part libraries.
From time to time, someone may update the Makefile to move to a more recent revision of third-party repos, if needed.
As already told on another topic, i'm a git noob, so not sure if what i wrote makes sense (i'm used to think in terms of cvs/svn repos). But i think that expecially when we want to focus on stability, respect to development, it's important that anyone is aligned and work with the same code, also the third part one.

**Comment by dpavlin** [comment]
We should switch to git submodules for third-party git checkout because it already provides ability to checkout exact git version (even on simple clone of our repository).

**Comment by houqp** [comment]
submodule +1

**Comment by hwhw** [comment]
Yep, totally in favor. +1.

**Comment by houqp** [comment]
I cannot build after pulled submodule changes. I removed the original directories and do a submodule init, then make fetchthridpart.

When compiling, it complains:

```
LINK build/debug/mudraw
build/debug/libopenjpeg.a(opj_jp2.o): In function `opj_jp2_encode':
/home/dave/documents/code/kindle/kindlepdfviewer/mupdf/thirdparty/openjpeg-1.5.0/libopenjpeg/jp2.c:1196: undefined reference to `write_cidx'
collect2: ld returned 1 exit status
make[2]: *** [build/debug/mudraw] Error 1
make[2]: Leaving directory `/home/dave/documents/code/kindle/kindlepdfviewer/mupdf'
make[1]: *** [mupdf/build/debug/libfitz.a] Error 2
```

I have to some how manually do following changes in mupdf:

``` diff
diff --git a/Makethird b/Makethird
index 1ce606c..de80026 100644
--- a/Makethird
+++ b/Makethird
@@ -163,6 +163,11 @@ OPENJPEG_SRC := \
        j2k.c \
        j2k_lib.c \
        jp2.c \
+       cidx_manager.c \
+       phix_manager.c \
+       tpix_manager.c \
+       ppix_manager.c \
+       thix_manager.c \
        jpt.c \
        mct.c \
        mqc.c \
```

What's happenning here?

**Comment by hwhw** [comment]
We were faster than the muPDF code itself :-) http://git.ghostscript.com/?p=mupdf.git;a=commitdiff;h=e7bb1c4937593c95065dbbbdd7eb15a73996c470
(we need to push the tag we want at least up to this commit)

**Comment by houqp** [comment]
Thanks for the Tip HW :)

Fixed added to pull request.
