### ISSUE TITLE
I want to know why kpfv just set 10 or less pages before full refresh .. I want 100 pages before full refresh. ...

### ISSUE THREAD

**Issue by kaysin** [koreader/kindlepdfviewer#446]
I want to know why kpfv just set 10 or less pages before full refresh .. I want 100 pages before full refresh. ... .... 

and ...the 'H' for  HELP page is not including M for zoom mode ..~~~~

**Comment by eLiNK2gl** [comment]
A somewhat arbitrary decision (re. 1-10) but
I do not think you would be happy with the result for 100.

**Comment by kaysin** [comment]
@eLiNK2gl  before this limit ...I  use  150 pages before full refresh ...because I need dxg to turn page quickly ..and  I'm not very particular about contrast .....

**Comment by tigran123** [comment]
@kaysin Help page does show `M` for setting the zoom mode for those formats where it is applicable (PDF, DjVu, JPEG). I assume you are reading some kind of ebook format (like FB2 or mobi or epub) and for these the `M` command would be meaningless.

As for the limit, ok, we can increase it, if you really need it. Would 200 be sufficient?

**Comment by kaysin** [comment]
@tigran123   ... Er. ... i think 200 is sufficient .~ I like this app very much ... maybe .Er.. .I want to translate it into Chinese ...

**Comment by kaysin** [comment]
@houqp   Are u in China ?

**Comment by tigran123** [comment]
Ok, done, see PR #447

**Comment by houqp** [comment]
@kaysin, I am in US now ;P
