### ISSUE TITLE
~A suggestion~~ Can we make kpfv use keyboard to choose books ,,just as choose TOC 

### ISSUE THREAD

**Issue by kaysin** [koreader/kindlepdfviewer#454]
~A suggestion~~ Can we make kpfv use keyboard to select books ,,just as choose TOC ..five-way is slow for selecting ...

**Comment by tigran123** [comment]
If we cut a huge chunk of horizontal space for a keyboard shortcut then the amount of space left for the filename will be diminished. And there are plenty of books with very long filenames, so...

Btw, I assume you realize that there is now a new command "Goto" (bound to `G` key) which helps you to quickly jump to any desired page in a long list of files.

**Comment by tigran123** [comment]
@kaysin Also, do you realize that you can also use page `Next/Prev` keys for navigating the file manager's list as well, not just the fiveway keys?

And also you can press `S` and search for the file by pattern (special pattern consisting of single space ' ' finds ALL files --- we need to document this somewhere).

Also, you should organize your files into directories (you know, the thing invented in Unix, stolen into "quick & dirty OS" and then renamed to "folder" to make people forget the origin of the grand idea of hierarchical tree-like organization of information) and then you will never have too many entries in any given list. My directories never grow to more than 500 books and at this size it is easily manageable.

**Comment by kaysin** [comment]
@tigran123  thanks for your reply  in patience.. I have realized  some troubles before i asked .. ..  and  when we read pdf ..we use vol-/+ to decrease/increase gamma .. can we use shift + vol -/+ let decrease or increase quickly ..?? i know shift + vol -/+ is TTS speed ... ..

**Comment by tigran123** [comment]
Hmmm, I thought 10% increment for gamma was big enough...

**Comment by houqp** [comment]
@kaysin , if you want to in crease the step of gamma adjustment, find following code in unireader.lua (around line 2430):

``` lua
    self.commands:addGroup("vol-/+",{Keydef:new(KEY_VPLUS,nil),Keydef:new(KEY_VMINUS,nil)},
        "decrease/increase gamma 10%",
        function(unireader,keydef)
            unireader:modifyGamma(keydef.keycode==KEY_VPLUS and 1.1 or 0.9)
        end)
```

change  (`1.1` and `0.9`) to (`1.2` and `0.8`) will increase the step to 20%. Or you can set it higher. But I think you need to only adjust the gamma for one book once, so you need use that feature very often right?

**Comment by tigran123** [comment]
closing this as it seems to be explained and resolved now.
