### ISSUE TITLE
epub table of contents not recognized

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#456]
Epub don't have a page number so it will be difficult to locate certain location without table of content support. 

Some epub's table of content is not recognized by kpv but can be used in pc software or calibre viewer, is it some compatibility problem?

https://www.box.com/s/7ibfr8uyo7l7ts7vf13r

**Comment by houqp** [comment]
You  mean you can see the TOC menu after pressed `t`? Which version are you using?

**Comment by dracodoc** [comment]
I'm using the latest build kindlepdfviewer-v2012.09-264-gffaa770 from @tigran123. After pressed "t", the pop up message said "no table of contents" while that epub do have table of contents.

The epub is generated from calibre, its table of contents is stored in toc.ncx inside the epub package.

**Comment by houqp** [comment]
That's strange, can you get the TOC of that epub with previous version before? Is TOC support not working for all of your epubs or just that one?

**Comment by dracodoc** [comment]
My first post is not clear so I updated it a little bit. I have epub that can't show TOC before so I thought they all don't work, but I double checked, some do work, so it's book specific.

I looked at the epub but didn't find specific difference. This epub is converted from html by calibre, and I can't see table of contents in kpv:

https://www.box.com/s/7ibfr8uyo7l7ts7vf13r

**Comment by houqp** [comment]
I just checked the book, very likely to be an upstream bug. Anyone want to give it a try? I am on my way of porting KPV to paperwhite now, so won't have time recently...

BTW, the typesetting of this book in KPV is some how sucks..... everything sentence is centered. sigh...

**Comment by dracodoc** [comment]
Calibre convertion have some problem so the preface part is not right, though after the preface the major part is ok :)
The book is a pdf first converted to html by mobipocket then converted to epub by calibre. I consider this kind of result good already for converting pdf to epub...

So it is book specific and not a easy to solve problem, you can just put this request on shelf, no big deal, I'll try to edit the epub or go through other software to ensure better compability.

**Comment by tigran123** [comment]
@dracodoc is the original PDF not readable on KPV even with the knowledge of how to use `Shift-S`/`Shift-F` modes properly? Maybe it will be readable with the new reflow feature we are working on?

Converting a book (i.e. PDF or DjVu file) to an ebook format (i.e. one of fb2, epub, mobi, etc) is, strictly speaking, a fundamentally IMPOSSIBLE task. Well, DjVu files are out of the question entirely because they are just images (except that some very rare DjVu files include the (very poor full of typos, OCRed) text embedded (for searching) and conversion can use that, of course). So, all those converters that claim to do it (including calibre) are basically lying, i.e. they are just extracting some bits and pieces (mostly text) from the PDF and throwing them together into an ebook. The result is never satisfactory on sufficiently complex books.

**Comment by dracodoc** [comment]
The orginal pdf have too small font and too wide page width, so even with shift-S it is still not practical to read directly. 

I knew converting pdf to other format is very difficult so I usually rely on cropping and landscape mode. That being said, I used to find that English text based pdf can be converted to html relatively well by mobipocket, the end result will at least comparable to reflow result. If you checked the book I posted, you will find other than the first chapter, the later content have pretty good format.

If you have similar need, I suggest you try mobipocket creator. It's freeware, you can import a pdf and save as html. From html any tool can convert it to other format.

**Comment by tigran123** [comment]
Ok, thanks for the suggestion, I will try mobipocket creator at some point.

**Comment by dracodoc** [comment]
I found a book could be the best sample for this bug: the table of contents is recognized by KPV, but only from Chapter 2, the chapter 1 is ignored. I looked at the epub file but didn't find any difference between chapter one and the other chapters, maybe you can find something in debug information.

https://www.box.com/s/t8r2ty09pvjzdnueyin3

**Comment by dracodoc** [comment]
The new build of KPV (@houqp 's epub cache patch build) still have some problem recognizing epub table of contents.
The epub from here have 6 entries in table of contents, but KPV can only see 5 of them, ignoring the first one. Sony T1 can find all 6 without problem.
http://readlists.com/998e160a/
http://readlists.com/998e160a/download/epub

**Comment by houqp** [comment]
Thanks again for reminding me this! I previously thought it was a bug from upstream ;p

**Comment by houqp** [comment]
closing for now since it's fixed in master
