### ISSUE TITLE
any plan for new release?

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#46]
We have added lots of new stuffs in the reader and the change log in wiki now has one page long. :) It's amazing.

Among all the changes, I think the new `settings` module should be delivered to end users as soon as possible, otherwise, with older version, they will have many sqlite DBs generated in their book folders, which will not be used by the new version from now.

I suggestion once we stopped adding features, we should do some testing and pack a release. I am in curious, how many new features are under development currently?

**Comment by hwhw** [comment]
Yep, I think a new release would be a good idea. Some thoughts on whether we need a migration path for the old .kpdfview SQLite files? I've just chosen .kpdfview.lua - it's quite long for a suffix, but it makes reasonably clear what it's for. I think we can get away with a short instruction to clean up the old files, I do not think we need to migrate data. Opinions?

The amount of work and new features is quite amazing.

What I really, really would like is to bring 90-degree-rotation into place. Including working zoom modes. But this can easily wait for a later release version.

Then I would like to have a settings dialogue. Something like Duokan has, I think. If I'll be the one to do it, I would incrementally work on the menu implementation and create more complex variants of menu entries.

**Comment by houqp** [comment]
> Yep, I think a new release would be a good idea. Some thoughts on whether we need a migration path for the old .kpdfview SQLite files? I've just chosen .kpdfview.lua - it's quite long for a suffix, but it makes reasonably clear what it's for. I think we can get away with a short instruction to clean up the old files, I do not think we need to migrate data. Opinions?

I think the long suffix if fine, users will not care about it anyway :)

Agree that no need for data migration. Instructions on Wiki will be enough. For those really lazy users, we can just add a clean up function.

> What I really, really would like is to bring 90-degree-rotation into place. Including working zoom modes. But this can easily wait for a later release version.
> 
> Then I would like to have a settings dialogue. Something like Duokan has, I think. If I'll be the one to do it, I would incrementally work on the menu implementation and create more complex variants of menu entries.

I have added these two features to issue page and tagged with `Feature`. If anyone would like to implement those features, please assign relevant issues to yourself to notify others. Hope that can avoid reinvention of wheels. :P

**Comment by houqp** [comment]
OK, I guess I will stop adding new features and focus on fixing stuffs before the new release.

**Comment by houqp** [comment]
I just went through the issue page. All the new features are not intended to be included in current release, so I guess we can do a release in this weekend? 

BTW, what will be the version number for this release? ;-p

Oh, one more thing, the download hits in the download page suddenly jumped from 40+ to 60. I don't know why.

**Comment by hwhw** [comment]
Should we release now so we can go on? I see already some loose ends growing...

As for a version number: I'm not quite sure. For what I expected to happen half a year ago, this would definitely earn a "1.0". But then this might mislead some people. We might still aim for the "playful" people - and thus call it "0.9"? Ah, this might make no sense either. I think my vote is on date-based release schemes. What about "2012.03"?

**Comment by traycold** [comment]
+1 to relase now: i think there is nothing really blocking as of now, and also the reader could already be used by a general audience (well, probably the fact thay have already rooted the kindle means they are in any case on the geek-side) wihout particular issue. Moreover, the more people use a recent version, the more easily other issues (if any!) could be discovered and fixed.

And also +1 for date-based release schemes.

**Comment by houqp** [comment]
GOGOGO! Can't wait for the release ;P

Also agree that kindlepdfviewer is not mature enough for 1.0 release, so 2012.03 seems more appropriate.

**Comment by hwhw** [comment]
I just tagged v2012.03, updated the Wiki download page and edited the mobileread forum thread. Thank you all very much! It's a real pleasure.
