### ISSUE TITLE
koptreader cuts the bottom of the page off

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#473]
On some djvu files a part of the bottom of the page is not visible and there is no way to get at it. Changing zoom either makes it worse or makes no difference. See pages 6 and 8 in this test file:

https://github.com/downloads/tigran123/libdjvu/koptreader-test.djvu

**Comment by tigran123** [comment]
The bug is also present on PDF files, see page 8 of this file:

https://github.com/downloads/tigran123/libdjvu/koptreader-test.pdf

**Comment by chrox** [comment]
@tigran123 In test file koptreader-test.djvu both page 6 and page 8 display all right when zoom value is set above 1.2 while both display abnormally when zoom value is below 1.2 . And in koptreader-test.pdf page 8 increasing zoom value above 0.70 just makes things worse but setting zoom value below 0.70 is just fine. They are quite interesting test cases.

**Comment by chrox** [comment]
The fix is already in master, so this issue should be closed.
