### ISSUE TITLE
koptreader has memory leak when reflowing pdf/djvu pages

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#486]
The memory leak bug is found on reading almost all pdf/djvu documents. Usually 10MB of memory is leaked out when reading 100 pages. A quick solution for this bug right now is restarting KPV after reading  a lot with `koptreaders`, namely the `PDFReflow` and `DJVUReflow` in reader choosing dialog.

**Comment by tigran123** [comment]
Yes, and obviously we shall leave it up to the users to restart KPV when needed.

**Comment by hwhw** [comment]
Well, although I tend to agree - the web browser folks have nowadays all
given up and create a new process context for a "tab"...

But after all, it shouldn't be too hard to track the memory leak down.

**Comment by hwhw** [comment]
And it's quite easy, I think after a short first glimpse on how the
reflow is implemented. The bitmap created by k2pdfopt is just never
freed.

Another note: I don't like the way how it is fitted into pdf.c and
something is fishy about the state information, I'm not sure if it's
properly isolated. But that could probably be done later.

**Comment by chrox** [comment]
@hwhw The master bitmap is freed as `bmp_free(&masterinfo->bmp);` at Line 431. If the main bitmap image were not freed the leak would not be 10MB/100 pages, virtually you just cannot read more than 20 pages before Kindle runs out of memory. I used mtrace to trace the memory allocate and free calls and found that the leak comes at the dynamic expansion of master bitmap. At the beginning of a reflow process the master bitmap is allocated with an arbitrary size of memory. When page regions are larger than the pre-allocated size the master bitmap will reallocate itself. And memory leak is just happened at that moment even though I haven't found exactly which line leak the memory.

**Comment by chrox** [comment]
@hwhw The author of K2pdfopt has already said sorry in his page for those blocks of global states. But I think it just works fine at most cases right now.

**Comment by hwhw** [comment]
Oh, I missed the freeing, sorry. And yes, I agree that it's a matter that
can be dealt with later. k2pdfopt is coming from being a standalone tool,
bringing it into proper shape for being a library might well be a matter
for later.

**Comment by chrox** [comment]
Since fix of this bug is already in master this issue is closed. See #627 for more info.
