### ISSUE TITLE
pdf zoom mode messed up sometimes

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#503]
I used shift-X to define page box for pdf A and read it in shift-S mode. If I quit that book and switch to pdf B (which don't have any page box, it was opened with default settings), then switch back to pdf A, the zoom mode seemed to be messed up. It is not the shift-S mode, nor any normal mode like fit height, fit width. The screen is located at top left of the page, with some contents of right side clipped off.

I guess it was because the page box information was messed up by the pdf B. If I quit pdf A, open an epub then open pdf A again, the zoom mode will not mess up.

**Comment by tigran123** [comment]
Yes, that is well known and the solution is simply to press `Shift-S` when you re-open the pdf file.

**Comment by dpavlin** [comment]
We are not storing zoom mode in file data, so we can't restore it on next document load. We _could_ invoke some  sensible zoom mode (`a` or `shift+a`) on document open. In current version we are using offsets from last document which are wrong as you noticed.

**Comment by dracodoc** [comment]
I checked the history file of that pdf, there are some data of zoom mode and some offsets. 

I think at least the customized pagebox is saved for each file in history file, otherwise user need to use shift-X every time when he open the pdf, right? So if the pagebox is saved, why not save the zoom mode too?

**Comment by dpavlin** [comment]
Yes, we are restoring `self.globalzoom_mode` on document open (ignore my previous comment), and it does work for some zoom modes, but `shift+s` is somehow special.

**Comment by dracodoc** [comment]
OK, I think it's acceptable to just press shift+s again if this is not that easy to solve. And I agree with you that maybe "a" mode should be used on document open instead, at least user will not think something wrong happened.
