### ISSUE TITLE
Time for the new 2012.10 release?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#506]
Shall we do a release now? KPV is nice and stable at the moment. Have we got any urgent stuff planned to go in?

**Comment by dpavlin** [comment]
I don't have anything ready, so if there are no objections I will push v2012.10 tag later today.

**Comment by houqp** [comment]
+1 for the release, so many cool features added wow! And it's great that we have two more active developers :)

**Comment by dpavlin** [comment]
added tag, build release, updated wiki, wrote MR announcement.
