### ISSUE TITLE
problems with koptreader on reflow

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#509]
I tried the refow feature on version v2012.09-389-g1f11513, this is very promising, one of pdf got pretty good result. However there are some problems.

Please look at these screenshots I made:
https://picasaweb.google.com/dracodoc/PdfReflow?authuser=0&authkey=Gv1sRgCMXkmL7-gIqPAQ&feat=directlink

pic 1 and 2, a single column pdf reflowed with small and medium font. 
1. the edge of page is cut off so every line is not complete. 
2. Note there are also large white area around the content, this is not right, why would small font in reflow mode have larger white area than medium font? Compare to pic 3 which is the original page, it seemed that some wrong crop box is applied before reflow.

pic 4 is the original page of another pdf (it's not screenshot by kpv, but screenshot from pc), and pic 5 is the reflowed page. 
1. There is also some cut off but it's different from above. Only the first line of paragraph is cut off for 2 letters.
2. In every wrap of lines of original text, several letters were cut off and the display is not complete.

pic 6,7, 8 don't have the cut off of first line of paragraph, but have the cut off in every wrap of lines.

**Comment by chrox** [comment]
@dracodoc Could you please send me a copy of the original document so that I could try to figure out what's wrong with the reflow mode?

**Comment by dracodoc** [comment]
I uploaded the 3 pdf to a zip here

https://www.box.com/s/bm3m9kwel13fvxlfg3mt

**Comment by chrox** [comment]
@dracodoc All tests are done on my Kindle 3 with KPV2012.10 release and KPV emulator on Ubuntu with a resolution of 600x800. 
1. I can repeat that the edge of page 3 of the bacteria article you provided is cut off as in pic1 and pic2. The reason is that the document was pre-cropped which confused K2pdfopt. I then downloaded the original article from ScienceDirect.com and feeded it to KPV. And everything was fine.
2. I can repeat the glitch on the "The art of seeing" at page 80 as in pic6 and pic7. I suspect it's the same reason as the first one I mentioned above. The book was pre-cropped. 
3. I cannot repeat what you have shown in pic5 with the book you provided at page 16 neither on my Kindle nor on the emulator. Given it has the same problem as the first two books. I'm afraid that you sent me the original book but you tested with a cropped one.

I suggest that you test again with original documents. It seems that k2pdfopt will do the crop things itself but probably in a stupid way even the crop work has been done already.

**Comment by dracodoc** [comment]
It do seem related to the crop. k2pdfopt may need to recognize the existing crop box.
I think pre-cropping is often useful because it's quicker to crop in pc than in kpv. And there is software like briss which can have a much more powerful crop feature than kpv.

k2pdfopt also could work better with pre-cropped pdf, for example the page header and footer can be cropped and make the page simpler.

**Comment by chrox** [comment]
@dracodoc The reason for porting K2pdfopt to KPV is to simplify the process of reading. The ideal reading experience is that with one click in Amazon book store or in your mail box your device will receive the documents you want to read. And you can start reading immediately without caring much about the bboxes or crop boxes whatever, just like you are reading a web page. If one page is finished you press the page forward key and the next page shows up as it would be. This is the PDF reader I would like to create on Kindle devices.

**Comment by dracodoc** [comment]
I understand you want manual operation as less as possible and I total agree. Though I haven't find a method to remove a crop box in pdf... Some pdf have a crop box (or maybe trim box) from day 1.

Actually the DSL book which tested without problem also have a crop box. I uploaded that version and further cropped version here
https://www.box.com/s/k5hmh2tajf6eg4p24rol

You will find they both have a crop box, just with different sizes. I checked all the other boxes(trim box, bleed box etc) they are matching crop box. So I'm not sure why K2pdfopt can handle one version well but not another version.

And with the version you tested with good result (6M version), there are some line wrapping not handled right. I didn't take screenshot but I believe you will find them on page 18 and 19. If you didn't find problem with these 2 pages I'll upload my screenshots.

Kindle DX could be somewhat slow to handle this task, it took a long time to page down sometimes...

**Comment by chrox** [comment]
@dracodoc I can repeat the glitch with the sixth font size but I failed to repeat it with the fifth font size. Probably you just set a too large font size.

**Comment by dracodoc** [comment]
I tried with the 5th font size, it did come out much better, but I still find one wrong line wrapping (page 18, "with a superclass").  You may have different result because your screen resolution is different from mine.

Anyway, this wrong line wrappings must be a bug (it should not be changed by font size), though I understand it's quite difficult to deal with this for pdf, and this bug could be from upstream and that will be more difficult to dealt with.

**Comment by chrox** [comment]
This bug has been fixed in PR #544 with a no trimming option in koptconfig. And a more generic manual trimming procedure will be added in koptreader. So this issue should be closed.
