### ISSUE TITLE
a BUG still exist in the latest released version

### ISSUE THREAD

**Issue by kkzxak47** [koreader/kindlepdfviewer#512]
on a Kindle DXG:
1. shift+p+d to enter KPV
2. open a pdf book
3. press 'k' to rotate screen 90° clockwise
4. alt+back to close the book

and your screen should froze...it's not the end though:
try your joypad, try 'L' or 'H' or 'F', they should work. But no matter what you try, the file browsing interface is not going to show again before you restart KPV.

-EOF-

**Comment by tigran123** [comment]
There is a suggestion (being discussed in issue #573) to disable landscape mode for file browsing interface (including Last Documents) and force the portrait mode upon return from the book. But when re-opening the book it would restore landscape mode if that is what it was read with before it was closed.

**Comment by tigran123** [comment]
The fix for this bug is in the master --- on closing a book the orientation is reset to portrait.
