### ISSUE TITLE
I can't push to github

### ISSUE THREAD

**Issue by kai771** [koreader/kindlepdfviewer#514]
I tried pushing my local branch to github, the same as I did earlier, but it didn't work this time.

```
git checkout rtl_mode
git push origin rtl_mode rtl_mode

error: dst ref refs/heads/rtl_mode receives from more than one src.
error: failed to push some refs to 'https://github.com/kai771/kindlepdfviewer.git'
```

I tried deleting kindlepdfviewer folder, then doing the clone again, then changing files, commiting - thus far it works. Then, when I try to push, it reports the same error. Anyone has any idea what's wrong? I couldn't find anything with google.

UPDATE:
I'm officially an idiot. After I deleted my repo, and forked it again, I finally noticed I missed a column between branch names.

**Comment by tigran123** [comment]
Not a colon (a column?) but an extra "rtl_mode" on the second command line, i.e. all you need to do to push the branch is

```
$ git push origin rtl_mode
```

no need for the second `rtl_mode` there.

**Comment by kai771** [comment]
What do you mean a "column"? It was a colon (http://en.wikipedia.org/wiki/Colon_%28punctuation%29). The syntax I found and was using earlier was:

```
git push origin local_branch:remote_branch
```

so, I should've used

```
git push origin rtl_mode:rtl_mode
```

Of course, using only one `rtl_mode` is probably a shortcut. The error reported by git was not helpful at all.

**Comment by tigran123** [comment]
Yes the single one is a shortcut. The colon is useful, for example, when the first part is empty, i.e. when you want to delete the remote branch.

**Comment by kai771** [comment]
And if you want your remote branch to have different name than the local one. :)

**Comment by tigran123** [comment]
Oh yes, I always keep those names the same which is why I never needed to use it...
