### ISSUE TITLE
Should we create a nightly build system for KPV?

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#522]
For there are so many features added recently and many of them may have great improvements but the improvements cannot be incorporated into the latest release timely. If we have a nightly build system compiling the latest code from the master tree, we can release it as a development channel for the braves.

**Comment by houqp** [comment]
Sure, that will be great. :)

**Comment by tigran123** [comment]
@chrox have you checked the wiki page? We already have the channel you are looking for, namely my and @dpavlin's development builds. E.g. if you look at my builds here:

https://github.com/tigran123/kindlepdfviewer/downloads

You will see that the latest build is only 5 hours old and there are releases almost every day. And people download them, as you can see from the counts shown on the right.

When I had a team of people working on a set of about 40 Bibles we were typesetting, I had a nightly build system on a very quiet Dell Optiplex machine which was switched on all the time in my study (and people ssh'd to it from all over the world). It was a humble Celeron 600MHz with 256MB of RAM was supporting the international development team of about 15 people (with 2-3 people always working simultaneously logged in to it via ssh!) --- but it was running a custom Linux kernel which I manually tuned to this specific hardware so it was incredibly fast :)

Anyway, how are you proposing to automate the build process, namely the part about uploading it to github.com? Isn't it only possible manually via their GUI interface? Or can one upload to Downloads area via scp?

**Comment by tigran123** [comment]
I forgot to mention that I agree with @houqp that it will be great if you arrange it. I.e. have you got a spare machine that is switched on all the time that could serve as a build server?

Btw, apart from the scp issue we should find out if we have some kind of disk quota on github --- i.e. we don't want to cause hwhw's account to be suspended because we filled up the Downloads area with the nightly build zip files...

**Comment by houqp** [comment]
Github has API that supports file upload and people have written wrappers around it:
http://stackoverflow.com/questions/1431082/programmatically-add-files-to-a-github-download-page

But @tigran123 is right, if we want to do nightly build, we probably want to store the package in somewhere else ;p

**Comment by chrox** [comment]
@tigran123 @houqp Yes, I have a spare machine running as a web server which is awake for 24*7. I think it might be capable to do the compilation work. And Github do have a Repo Downloads API with which we can list, upload and delete files in the Downloads section of a repo. See http://developer.github.com/v3/repos/downloads/ . But I prefer to use a python library called PyGithub which is a complete wrapper for Github API v3. And I will clone a new repo from hwhw's KPV repo called kindlepdfviewer-nightly against which nightly builds will be compiled and installable ZIP files will be uploaded to kindlepdfviewer-nightly.

**Comment by chrox** [comment]
Oh I just cannot fork one repo twice.

**Comment by chrox** [comment]
The nightly build server is working now. Source code of the server can be found here https://gist.github.com/4002028 . Latest KPV installable zip file will be automatically uploaded to https://github.com/chrox/kindlepdfviewer/downloads/ at 00:00 GMT+8 everyday.

**Comment by dpavlin** [comment]
chrox++ Can you add that link to wiki page so users can find nightly builds, please?

**Comment by tigran123** [comment]
@chrox Thank you very much!

**Comment by tigran123** [comment]
Ok, since this is now implemented we can close this issue. Thanks to @chrox  again for doing this.

**Comment by houqp** [comment]
Cool :) I added your script to wiki too

**Comment by dpavlin** [comment]
@chrox would it be better if we have original name of file as produced by `git describe` ? This would be some indication which is last commit of nightly build without downloading it first.

**Comment by chrox** [comment]
@dpavlin The latest git revision is extracted from the original name and is appended to the comment of the uploaded file.
