### ISSUE TITLE
[Done, please merge after review]Change bookmark dialog to a marker?

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#538]
Bookmaking a page in my DX need about 2 full seconds to wait the pop up dialog appear and disappear. Compare to other Eink reader app, this is rather long and breaks the reading flow.

Usually when a user bookmarking a page, I assume he already read some content of that page(otherwise how can he decide to make that bookmark?), so I think to put a small mark on top of page will not interfere with his reading. 

Kindle software and Sony T1 software both put a triangle mark on right top corner of page as a bookmark, this is simple and intuitive. I'm thinking kpv should also put a mark on right top corner of page, and this mark can be showed with partial refresh, just like the status bar brought by menu button. Assume user most likely already read the content of right top corner, the marker will not be a problem even it blocked a small part of page. User can continue to read current page without the need of a refresh, this make the bookmarking procedure only take half time and without refresh.

After user completed current page, a page down/up should bring next/previous page directly, no need to refresh and remove the marker.

Of course, if the marker did block some content, user can always use "back" to remove the marker and refresh the current page.

If current page is already bookmarked, I think showing a slightly different marker is enough, just like the regular bookmarking case.

Kindle software can show the bookmark mark when a page with bookmark is shown. This feature can be implemented or just ignored, both have its reasons. I think this is not a must.

**Comment by dracodoc** [comment]
There could be some other pop up dialogs that can also use this method. Like the gamma value , font size, zooming step etc. Instead pop up a dialog then disappear it, the page can be refreshed first then add a tiny area of text at right top corner, and it can be turned off by pressing "back".

This "marker style" can be an alternative to pop up dialog, and it can be user customizable. KPV can customize pop up dialog already, I expect it will not be too much hassle to add it as a special style of dialog.

**Comment by tigran123** [comment]
There are two things to remember here before rushing to implement this feature:
1. You do not really need to wait 2 seconds when you add a bookmark. Immediately after pressing `Alt-B` you can press `B` (or any other key) again (while your finger is still on it) and this would terminate the message "Page marked" instantly.
2. I thought about implementing a little triangle at the top right corner, like in Amazon's readers, but there are two issues here:
   
   a) the top right corner of the page and top right corner of the screen are not the same thing in some zoom modes (e.g. fit page height). So, we would have to calculate the exact location of the top right corner of the page.
   
   b) we would have to show this not just when you add a bookmark but every time you look at the page which has a bookmark. That means for each page we need to maintain a marker and check it on each page draw.

I am not saying this cannot (or should not) be done. I am just wondering whether it is worth implementing given the fact that this (and any other) info message can be terminated by any key press anyway.

**Comment by dracodoc** [comment]
I'm talking about the time that the dialog need to appear and disappear, this doesn't include the delay set in program. Actually my delay time is set to 50ms(and I've been modify this value for a long time so I knew the delay timer can be reduced), but DX need 2 seconds to show and close the dialog even the delay time is set to 0.

I thought about the effort to maintain the marker, that's why I said this part can be ignored. The need for display marker for showing already marked page doesn't justify the effort to maintain that marker for every bookmarked page. So I'm just saying use a marker to show some information, it is not supposed to be a permanent part of a page. It will be an overlay, just like the status bar, but user don't need to remove it in most cases (the status bar need to be removed because it blocked some contents), and "page down" will jump to next page directly, that's all.

As for the location of the marker, how did KPV calculate the location of status bar? It was just showed "over" current page, the location is related to current screen, do you really need to know the location to the page? Anyway it should be just like the status bar, just it don't need to take both top and bottom, but only a corner. I don't see why there should be any difference in implementing this.

**Comment by tigran123** [comment]
Ah, I see what you mean now... Ok, that is very easy to implement of course. But it won't be as useful as Amazon's "folded tip of the page" triangle at the top right corner, i.e. when looking at a page you wouldn't know if it is already bookmarked or not and would have to press `B` to get the bookmarks list to find out. Are you sure that you would be happy with this? I thought you wanted a full-featured Amazon-style "folded tip of the page" thingy...

**Comment by dracodoc** [comment]
A full featured tip will be more useful but it doesn't fit KPV's case. Because amazon format always have some corner space, the folded tip will not interfere with reading. With full screened display pdf in KPV (and I often crop the pdf as much as possible), it's very possible the folded tip can block a little bit of page. And there is the problem of maintaining that marker for pages which is more complicated than amazon.

And when do you want to know a page is bookmarked beforehand? Only after you have read this part of book then go back. I can always use keyboard shortcut to jump between bookmarks, and with the overlay method, just bookmark it again will not take too much hassle. So this feature will be a bonus but not really needed.

Considering all the cost, I think just use the marker as an temporary overlay would be good enough and will not introduce too much trouble (I've always trying to limit the effort it needed for all my feature suggestions :P). With the marker as an overlay, the bookmarking process can be at least twice fast and do not introduce any global refresh. I think that's good enough.

**Comment by dracodoc** [comment]
I think it will be easier to use text as mark instead of a graphical mark. When a page is bookmarked, just display "Page Marked" at top, use the same method of show info box by pressing menu key. Similarly, just display "Page Already Marked!" at top when current page is already bookmarked.

This is very easy to do, I tested a little bit in the simulator. Though I'm not familiar with the other details and the commit process so I didn't try to complete it in the right way. Right now I just hacked as follows:

unireader.lua

---

```
--show msg in top, added by draco
function UniReader:drawTopmsg(msg)
    local width, height = G_width, G_height
    -- changed to be the same font group as originaly intended
    local face = Font:getFace("rifont", 18)
    fb.bb:paintRect(0, 0, width/3, 15+6*2, 4)
    renderUtf8Text(fb.bb, 10, 15+6, face, msg, true)
    fb:refresh(1)
end
```

---

```
self.commands:add(KEY_B,MOD_ALT,"B",
    "add bookmark to current page",
    function(unireader)
        ok = unireader:addBookmark(self.pageno)
        if not ok then
        -- changed by draco
            UniReader:drawTopmsg("Page already marked!")
        else
            UniReader:drawTopmsg("Page marked")
        end
    end)
```

---

crereader.lua

---

```
self.commands:add(KEY_B, MOD_ALT, "B",
    "add bookmark to current page",
    function(self)
        ok = self:addBookmark(self.doc:getXPointer())
        if not ok then
        -- changed by draco
            UniReader:drawTopmsg("Page already marked!")
        else
            UniReader:drawTopmsg("Page marked")
        end
    end
)
```

**Comment by dracodoc** [comment]
I believe some other pop up dialog could use this method too, like the gamma value. User often need to adjust multiple steps of gamma value before satisfied, change the pop up to a one time overlay will make the procedures much quicker.

**Comment by tigran123** [comment]
First of all, your drawTopmsg() function (aside from the non-compliance with the existing KPV naming convention) is really a generic utility function and should not be any object's method.

Second, why would one need it anyway? What's wrong with the existing method of displaying a pop-up window? Your post only mentions the time delay (2 seconds on DXG), but this has nothing to do with the display of the pop-up (which can take only 1.5 seconds maximum and can be aborted by pressing any key) and is due to the slow refresh of eInk screen and big size thereof on DXG. I see no need to change it --- it is quite good (if not perfect) as it is.

**Comment by dracodoc** [comment]
My modifications is just a temporary hack, I don't know much about the lua so I'm just messing around here.

As for the need, I think I never said the time wasted is because of the delay or whether or not abort the dialog by pressing any key, I knew it's simply because DX need this much time to do this.  Then what's the difference between dialog and the marker on top? The dialog will block the center of screen, it's impossible to continue reading before it fully disappears, while a marker on top that don't need refresh will not interfere with reading, I can simply continue to read once I pressed the Alt+B, then page down when I finished. I saved at least 2 seconds for every bookmark.

It's fine that you don't need it, but I don't think everybody else will have same opinion.

**Comment by tigran123** [comment]
So, if I understood you correctly you are suggesting to overwrite some part of the page (top right corner) with the message "Bookmark added" (the error message "Bookmark already exists" should remain as a popup) and if the user doesn't like the fact that some text was overwritten then he can press Space to refresh the page. Right? I have no objection to such change, as long as the message "Bookmark added" is clearly visible.

**Comment by dracodoc** [comment]
You can try it in simulator. I believe it is clearly visible. I used a gray background for the marker area.

Both "page marked" and "page already marked" messages are changed to top marks, I don't see why the latter need to be kept as popup. Space will refresh the page though it take two refreshes in my DX, I guess it could be related to the fb:refresh(1).

**Comment by tigran123** [comment]
Ok, I'll try it. There are a couple of bugs in your implementation --- I'll submit a PR soon.

**Comment by tigran123** [comment]
done in the PR #617

**Comment by dracodoc** [comment]
Thanks! I knew my hacks are just temporary and must have problems. Though the manual refresh with space still cause 2 refreshes, I think there is no real need to change that since I expect the need to refresh is rare.

**Comment by tigran123** [comment]
Hmmm, does Space really cause two refreshes? I will look into this and try to fix it if it really does... It shouldn't do that.

**Comment by dracodoc** [comment]
Yes it does. According to here

```
self.commands:add(KEY_SPACE, nil, "Space",
    "manual full screen refresh",
    function(unireader)
        -- eInk will not refresh if nothing has changed on the screen so we fake a change here.
        fb.bb:invertRect(0, 0, 1, 1)
        fb:refresh(1)
        fb.bb:invertRect(0, 0, 1, 1)
        fb:refresh(0)
        self.rcount = self.rcountmax
        self:redrawCurrentPage()
    end)
```

I'm guessing the faked changed add up with the bookmark change so there are duplicate refreshes. To fix it seemed easy enough but that will need the space command check if the drawTopMsg had been called and use different procedures if it was really called.

**Comment by tigran123** [comment]
That's ok then.

**Comment by houqp** [comment]
Wow, @dracodoc  finally see your commit lands in master :)

Just a quick question:

> I'm guessing the faked changed add up with the bookmark change so there are
> duplicate refreshes.

I don't quite get this. Why bookmark change will add up with facke changes? Is there any relation between bookmark change and manual screen refresh?

**Comment by tigran123** [comment]
I think he referred to the change in Space command handler which fakes a change on the screen. Plus there is a fb:refresh(1) coming from adding bookmark.

**Comment by dracodoc** [comment]
Normally the manual screen refresh will clear the screen then display the content again. When a bookmark is added in current method, manual screen refresh will first refresh the screen with bookmark then refresh the screen again without bookmark, so there will be 2 refreshes. I was guessing the reason for this behavior, but I think it's ok to just leave it as is because the scenario will be rare and the solution could introduce more complexity.

**Comment by houqp** [comment]
oh, yes. There is actually 3 refresh. The first two (including the fake one) is needed to do a full refresh, the third is used to restore the original document page content. Yeah, but I can l live with it. let's leave it as is...
