### ISSUE TITLE
battery level log on wake up

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#539]
I found my DX battery level is dropping faster recently. Can KPV add a simple battery level log feature?

On every wake up from screen saver, the battery level and time can be logged to a text file. This should not have any harm since it only log when waked up, which is not very frequent. And the data will show how much battery level dropped in sleeping mode, which is useful and comparable.

**Comment by tigran123** [comment]
This is very simple to implement as the error output from `gasgaugeinfo -s` command shows the type of info you need. So, we can output that on the sleep/wake up events.

Btw, I personally always exit KPV back to Amazon's framework before putting Kindle to sleep.

**Comment by dracodoc** [comment]
That will be great! And yes, it should log both on sleep and wake up.

**Comment by tigran123** [comment]
Ok, do you want it in crash.log or in a separate battery.log file?

**Comment by dracodoc** [comment]
Maybe better in a separate file, and write it into some csv kind of format. Like this:

Date   Time  Battery level     Event
11.1     5:20  89%                  sleep
11.1     6:40  70%                  wake up  

So user can even make graph from it if they want...

**Comment by tigran123** [comment]
Ok, I will implement it tomorrow.

**Comment by dracodoc** [comment]
Thanks a lot!

**Comment by eLiNK2gl** [comment]
@tigran123 I personally prefer not to exit the KPV at all.
Part of the reason is the 'bug' with firmware 3.2.1 on KDXG, which increases waiting time from the sleeping mode. Somehow, this waiting time, while the KPV is active, is noticeably shorter.

**Comment by dracodoc** [comment]
Somebody mentioned that disable indexing will reduce the waiting time, did you try it? Though I didn't try it and I don't quite believe it.

;debugOn
~
disableIndexing
;debugOff

I didn't use the 3.2.1 on DX solely because of this bug.

And I almost never quit KPV too :)

**Comment by tigran123** [comment]
Ok, this feature is ready but it relies on PR #541 (because it changes LUA_FILES in Makefile as well) so I'll wait until it is merged before submitting the new PR (otherwise it would conflict with it)

**Comment by tigran123** [comment]
The feature is merged into master now. (but I am going to make it optional and disabled by default)
