### ISSUE TITLE
cannot register font <./fonts/droid/DroidSansFallbackFull.ttf>

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#542]
If you start reader.lua with "-d" flag you will see this error message. This is the font that made the distribution size grow to over 9MB. So, shall we get rid of it (i.e. not include in the distribution) or what?

**Comment by houqp** [comment]
um, where can I get that `fonts/droid/DroidSansFallbackFull.ttf`? I cannot find it in my fonts directory.

**Comment by tigran123** [comment]
If you pull --rebase upstream master and clean everything and "make fetchthirdparty" you will get it. It came with the recent upgrade of MuPDF.

(or just clone a new copy of your "origin" tree, then pull --upstream master and "make fetchthirdparty")

**Comment by houqp** [comment]
Thanks, got it :)

Since mupdf define `NOBUILTINFONT` by default, I think we are safe to get rid of it.

**Comment by tigran123** [comment]
Ok, good, that will bring the size of distribution zip file down...

**Comment by hwhw** [comment]
But it makes me thinking whether DroidSansFallbackFull should replace DroidSansFallback...

**Comment by tigran123** [comment]
Ok then we need to figure out why the registration fails.

**Comment by houqp** [comment]
OK, it turns out that `DroidSansFallbackFull` and `DroidSansFallback` have dulplicate definition, so crengine's fontman fails at line 2516 of lvfntman.cpp:

``` cpp
if ( _cache.findDuplicate( &def ) ) {
    CRLog::trace("font definition is duplicate");
    return false;
}

```

So if we decide to use fallbackfull, then we will need to get rid of fallback. Um.. so far cant see any harm of replacing fallback with fallbackfull...

**Comment by tigran123** [comment]
Have you measured the time it takes for registering the full version? If it slows down KPV startup and brings no tangible benefits then it is not obvious that we should switch to it. I'll try to measure the timings now.

**Comment by tigran123** [comment]
Ok, the timings are exactly the same for "Fallback" and "FallbackFull". And it takes the same amount of time to register the font as it takes to fail to register it, so we should definitely get rid of one of these.

**Comment by houqp** [comment]
thanks for the testing, I prefer to try using FallbackFull for the development code base then ;p

**Comment by tigran123** [comment]
Ok, I'll submit a PR that switches to it now.

**Comment by tigran123** [comment]
The fix is in the master, closing the issue.
