### ISSUE TITLE
unable to make fetchthirdparty in nightly build server

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#552]
I use the script below to nightly build against the latest code tree. 

```
git pull
git reset --hard
make fetchthirdparty
make clean cleanthirdparty
make thirdparty kpdfview customupdate
```

But I found there were errors when running make fetchthirdparty

```
error: Unable to find eb6f890ebd01ee4cf4f31a66d8a946bc8dccd885 under http://luajit.org/git/luajit-2.0.git
Cannot obtain needed object eb6f890ebd01ee4cf4f31a66d8a946bc8dccd885
error: Fetch failed.
Unable to fetch in submodule path 'luajit-2.0'
```

After I removed `luajit-2.0` directory with the command `rm -rf luajit-2.0`. The error came to this:

```
From git://git.ghostscript.com/mupdf
   31791f3..05219d0  master     -> origin/master
error: The following untracked working tree files would be overwritten by checkout:
    thirdparty/README
Please move or remove them before you can switch branches.
Aborting
Unable to checkout '05219d086a5136ee19f643cf062bd5c0d3aef5d3' in submodule path 'mupdf'
make: *** [fetchthirdparty] Error 1
```

And after I removed `mupdf` directory with the command `rm -rf mupdf`. The building script went on smoothly. I don't know what's wrong with this building script.

**Comment by houqp** [comment]
For the luajit submodule, same thing happened to me yesterday, I also did the `rm` dirty hack ;p So probably it's not your script is wrong, but the way we keep up with upstream is not complete? Maybe we need to do something else except from `pull` when there is submodule update? No idea...

**Comment by tigran123** [comment]
why not simply "git clone" the kindlepdfviewer repository from scratch on each build?

**Comment by chrox** [comment]
The "git clone" is a good idea for my case. But probably there is also something wrong in `make fetchthirdparty` script that prevent one fetching the latest third parties.

**Comment by tigran123** [comment]
make fetchthirdparty is "non-idempotent", i.e. cannot be run twice in the same tree.

**Comment by chrox** [comment]
That should make sense. And I would close this issue. Thanks.
