### ISSUE TITLE
caching of rendered tiles out of shape

### ISSUE THREAD

**Issue by hwhw** [koreader/kindlepdfviewer#56]
The mechanism which is used to save rendered tiles should probably get adapted to the current state of things regarding zooming/panning (and later also: rotating). When zoomed, I'd like to render full pages (up to a certain size, at least). Then display only excerpts of those rendered tiles. I think currently, we're re-rendering each time we pan on zoomed pages. Also, pre-caching the next page doesn't work right now.

**Comment by houqp** [comment]
Will you work on this fix? Seems that it cannot be done without touching C codes?

**Comment by hwhw** [comment]
Well, it can, it's only relevant for the Lua side. But I'll do it anyway. Weekend is near and I should be able to spend some hours on the code :-)

**Comment by hwhw** [comment]
I just committed a new implementation. However, I'm almost certain that this might have introduced bugs that weren't there before (or that didn't manifest). Please try and report (or, of course, fix) :-)

**Comment by Germanc** [comment]
It is segfaulting with a lot of files, and there is some weird rendering on top of others (http://imgur.com/1hrBu). Also the right last pixels are repeated on the left (http://imgur.com/7Ku01). Both on emu mode and on the kindle

EDIT: it's segfaulting in line 442 (fb.bb:blitFrom(bb, dest_x, dest_y, offset_x, offset_y, width, height))

**Comment by hwhw** [comment]
Ah, well, I was almost certain I lost the overview of all the different cases. Maybe it was a wrong decision to tackle that before release :-( I'll play with the patches that were sent (thanks a lot!). But I see that in the end I'd like to have all the layouting code much better abstracted. I would go as far as to say that we need abstractions for points and rectangles, eliminating lots of fine-grained, constantly repeating code concepts. I'm really in the mood of doing a great overhaul of unireader.

**Comment by hwhw** [comment]
And as for why it segfaults: this is probably due to incomplete boundary checks in the C code. I'll insert more cases there that will error out when input parameters are not in the expected constraints. My guess is on the negative value cases.

**Comment by houqp** [comment]
> Ah, well, I was almost certain I lost the overview of all the different cases. Maybe it was a wrong decision to tackle that before release :-(

If I were you, I would rewrite the cache strategy too :) I think speed is the most important factor and it will make me feel very uncomfortable if an out of shape cache strategy is delivered to end user ;P

After about half a day of reading (testing), I would say so far the cache system works fine and no crashes happen to me. 

> I would go as far as to say that we need abstractions for points and rectangles, eliminating lots of fine-grained, constantly repeating code concepts. I'm really in the mood of doing a great overhaul of unireader.

Sounds cool! Hope the release can be out soon, there are lots of changes here waiting to be integrated into the next next release :D

**Comment by hwhw** [comment]
I'll close this one for now.
