### ISSUE TITLE
configuable epub styles

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#569]
KPV use its own css for epub, which have lots of advantages and I actually like it. However that also means I need to adjust font size and line spacing manually. This is not a problem in many times because I will simply use same settings for all my English books, but I need to select font, line spacing for every new Chinese epub, because I cannot make the font selection default, that will break font selection for English epub.

So I'm suggesting to make configurable styles like following:
1. press a key to save current display styles, including font, font size, line spacing etc. The style name could be inputted or just use the current book name.
2. press a key to load previous saved display styles and apply one of them.

This should be easy to implement and can work as a alternative to customizable css support without big changes on crengine.

Besides, since the format information talked here are saved in file history already, these "styles" can be seen as a special file history. So "save current style" in a book could mean just pick part of the history information and write to a special "history file". Then any other book with same type could "apply styles" and select one of the special history file, actually just merge the special history with current file history and reopen the file with the new history, this will serve the purpose of applying styles. 

Of course this is just one way to do this, and I'm sure there could be other better methods.

**Comment by mayabtlaloc** [comment]
I also join this function is implemented

**Comment by kai771** [comment]
If anyone is interested, you can choose a style sheet to use per book in Librerator.

**Comment by houqp** [comment]
closed since feature implemented in master
