### ISSUE TITLE
Memory usage control needed

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#58]
eLiNK reports that the kpdfview causes his kindle DXG reboot (framework restart) after some page turns. The reboot can always be reproduced by serval page turn in files with large images. I saw his top command output and found that his kindle is ran out of memory:

```
top - 02:42:38 up 42 min,  1 user,  load average: 2.02, 0.97, 0.45
Tasks:  56 total,   3 running,  51 sleeping,   1 stopped,   1 zombie
Cpu(s): 90.1%us,  6.6%sy,  0.0%ni,  0.0%id,  3.0%wa,  0.3%hi,  0.0%si,  0.0%st
Mem:    127172k total,   125136k used,     2036k free,     2608k buffers
Swap:        0k total,        0k used,        0k free,    13332k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 4398 root      25   0 79592  62m 1920 R 82.8 50.0   0:33.96 reader.lua
 4469 root      24   0  248m  30m 6120 R 11.9 24.6   0:05.66 cvm
 4391 root      15   0  2384  672  436 R  0.7  0.5   0:01.80 top
  146 root      10  -5     0    0    0 D  0.3  0.0   0:04.53 mmcqd
 2155 root      15   0 19684  728  520 S  0.3  0.6   0:00.59 powerd
    1 root      15   0  1484  104   40 S  0.0  0.1   0:01.13 init.sysvinit
    2 root      10  -5     0    0    0 S  0.0  0.0   0:00.00 kthreadd
    3 root      34  19     0    0    0 S  0.0  0.0   0:00.00 ksoftirqd/0
    4 root      RT  -5     0    0    0 S  0.0  0.0   0:00.00 watchdog/0
    5 root       0 -20     0    0    0 S  0.0  0.0   0:00.00 events/0
    6 root      10  -5     0    0    0 S  0.0  0.0   0:00.00 khelper
   37 root      10  -5     0    0    0 S  0.0  0.0   0:00.03 kblockd/0
   38 root      20  -5     0    0    0 S  0.0  0.0   0:00.00 cqueue/0
   40 root      10  -5     0    0    0 S  0.0  0.0   0:00.29 mxc_spi.1
   58 root      12  -5     0    0    0 S  0.0  0.0   0:00.03 kmmcd
   76 root      15   0     0    0    0 S  0.0  0.0   0:00.00 pdflush
   77 root      15   0     0    0    0 S  0.0  0.0   0:00.00 pdflush
   78 root      10  -5     0    0    0 D  0.0  0.0   0:00.89 kswapd0
   79 root      20  -5     0    0    0 S  0.0  0.0   0:00.00 aio/0
   99 root      20  -5     0    0    0 S  0.0  0.0   0:01.85 mtdblockd
  134 root      10  -5     0    0    0 S  0.0  0.0   0:00.00 kondemand/0
  157 root      12  -5     0    0    0 S  0.0  0.0   0:00.00 kjournald
  259 root      11  -4  1520  400  236 S  0.0  0.3   0:00.91 udevd
  497 root      10  -5     0    0    0 S  0.0  0.0   0:00.03 kjournald
  728 root      10  -5     0    0    0 S  0.0  0.0   0:00.30 eink_fb_bt
  730 root      10  -5     0    0    0 S  0.0  0.0   0:00.00 eink_fb_pt
  806 root      15   0  1948  524  304 S  0.0  0.4   0:00.79 syslog-ng
  933 root      10  -5     0    0    0 S  0.0  0.0   0:01.46 charger/0
 1261 root       0 -20     0    0    0 S  0.0  0.0   0:02.19 loop0
 1296 root      25   0 56152 1112  184 S  0.0  0.9   0:11.05 fsp
 1349 root      15   0  2128  124   16 S  0.0  0.1   0:00.19 launchpad
 1418 root      25   0  2656  164    4 S  0.0  0.1   0:00.03 lifeguard
 1480 root      25   0  2656  164    4 S  0.0  0.1   0:00.00 lifeguard
 2012 messageb  16   0  2236  564  340 S  0.0  0.4   0:00.46 dbus-daemon
 2105 root      15   0 19608  744  512 S  0.0  0.6   0:00.46 pmond
 2319 root      18   0 44504  536  292 S  0.0  0.4   0:00.10 wand
 2410 root      18   0 47720  616  260 S  0.0  0.5   0:00.14 phd
 2473 root      17   0 35784  184    0 S  0.0  0.1   0:00.02 mcsd
 2529 root      15   0 19600  196    0 S  0.0  0.2   0:00.08 volumd
 2732 root      18   0 50040 1176  472 S  0.0  0.9   0:00.42 audioServer
 2786 root       1 -19 1018m 2800   48 S  0.0  2.2   0:00.39 ttsd
 2948 root      17   0 38936  688  268 S  0.0  0.5   0:00.10 tmd
 2966 root      16   0  2652   96    4 S  0.0  0.1   0:00.05 crond
 2972 root      25   0 19324  544  388 S  0.0  0.4   0:00.03 lipc-daemon
 3059 root      18   0 85576 2664    0 T  0.0  2.1   0:00.73 browserd
 3133 root      18   0  2656  572  392 S  0.0  0.4   0:00.55 start.sh
 3213 root      17   0     0    0    0 Z  0.0  0.0   0:00.00 sh <defunct>
 3303 root      18   0  2656   84    0 S  0.0  0.1   0:00.00 getty
 3670 root      20   0 36032  236    0 S  0.0  0.2   0:00.07 cmd
 4364 root      15   0  1816  112   32 S  0.0  0.1   0:00.10 busybox
 4378 root      16   0  2084   96    4 S  0.0  0.1   0:00.01 dropbear
 4388 root      15   0  2656   96    4 S  0.0  0.1   0:00.01 sh
 4396 root      17   0  2652   76    0 S  0.0  0.1   0:00.00 sh
 4397 root      19   0  2656   84    4 S  0.0  0.1   0:00.01 kpdf.sh
 4462 root      18   0  2656  572  372 S  0.0  0.4   0:00.00 start.sh
```

This is the snapshot after the reboot, so I guess reader.lua consumed more memnory before the reboot. I suspect the reboot is caused by the framework, which forces a brute force gargage collection when memory is low. It does not happen to me maybe because my K3 has double memroy. 

I don't have a DXG to test with. Does this also occur to your DXG?

**Comment by dpavlin** [comment]
When you have DXG with only 128 Mb of RAM you get used to out of memory problems ;-)

On more serious note, we used to stop Kindle framework in launchpad script, but I removed it some time ago because it introduces huge delay on enter and exit since we have to stop/start Kindle framework which seem very like reboot.

I was playing today with sending signals to ckvm (which seems to be Sun's embedded java) in hope that one of them will force Java to run garbage collection and free more RAM, but without luck. We don't have swap (which is my initial motivation for hacking kernel on DXG but I didn't get to it yet) so our options are limited.

**Comment by houqp** [comment]
Oh, that's bad. This makes kpdfview some how unusable for viewing image based pdfs.

Geekmaster said in KT, they have real time garbage collection that prevents the reboot. 

If we can turn kpdfview into an opensource kindle OS, then we don't need to worry about all these. ;P

**Comment by dpavlin** [comment]
We could ask user opening large pdf file if he wants to turn off Amazon's OS to get more memory I guess.

**Comment by houqp** [comment]
> We could ask user opening large pdf file if he wants to turn off Amazon's OS to get more memory I guess.

Yep, I can't come up with better one.

**Comment by houqp** [comment]
memory usage for MuPDF can be now controlled thanks to commit 14b26a4aebd5c95aab5d7b245e9055b2abd4c9ff, now all we need to do is to add a configurable entry in .reader.kpdfview.lua :)

**Comment by traycold** [comment]
hi guys, with commit e2e5af1c6135f846a0995e45cff0a73bc5a2063d on my fork I addes some debug code to better understand memory usage by muPdf. Wrapping default malloc/realloc/free it's possible to log the allocated memory by muPdf for rendering of PDF documents.
As you can see playing with the value of cachesize, it seems to me that this value is not strictly respected by muPdf (at least, not when the value is quite low, let's say 3 Mb). Apparently the cachesize could be overcome by muPdf if it's necessary to render pages. But they may also be leaks... (or, of course, the count of used memory is not accurate!).

**Comment by houqp** [comment]
wow, nice try :)

Hope that "leaking" cache size control can beat that reboot ;P

**Comment by dpavlin** [comment]
This seems very interesting. I was thinking about using http://www.canonware.com/jemalloc/ mostly after watching https://www.facebook.com/photo.php?v=696488619305 but never got pass source checkout. Do you think it would make sense to pursue this further? (not me, if at all possible :-)

**Comment by dpavlin** [comment]
@traycold would you mind submitting pull request before we go off-topic? ;-)

**Comment by traycold** [comment]
just submitted the pull-request!

**Comment by houqp** [comment]
can we close this now?

**Comment by dpavlin** [comment]
Sure. It seems that #79 is followup to this one.
