### ISSUE TITLE
Bug in panning with alt key

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#59]
Seems that alt key is very different from shift key. When you press alt key alone, it will not generate alt key press event. And when you press alt key with following keys, it will not generate alt key events too:
- Q-P (only numbers, not combinations of alt+char)
- fiveway keys (only fiveway key events, no alt key event)

This leads to a bug in panning. When we use alt + fiveway to pan, it should move in 20 pixels. It actually does in EMU mode, but in real kindle, it still moves 100 pixels.

**Comment by dpavlin** [comment]
Good catch!

My first thought was to suggest Q-P keys as configurable steps for panning, but then I tried that on Kindle and it doesn't seem intuitive. After pressing a few more keys here is one possible alternative to pan step change:
1. we record last fiveway direction
2. if next event is from fiveway with shift in _same_ direction we _increase_ step to double size and move
3. if next event is from fiveway with shift in _opposite_ direction we _decrease_ step to half size and move

This also allows easy fix of "oh, I scrolled too much" errors so it might be usable. What do you think?

p.s. I think that same bindings might be good for moving page margins in manual crop #35

**Comment by houqp** [comment]
I found this bug when I was trying to manual crop my book in djvu. And I found it some how impossible to move the main content to the center of the screen just with 100 pixels and 50 pixels move. When I want to try 20 pixels with alt key, the bug jumped out. I guess 20 pixels wont help in some situations too.

> ```
> we record last fiveway direction
> if next event is from fiveway with shift in same direction we increase step to double size and move
> if next event is from fiveway with shift in opposite direction we decrease step to half size and move
> ```
> 
> This also allows easy fix of "oh, I scrolled too much" errors so it might be usable. What do you think?

This do solve the problem of "oh, I scrolled too much", but I am afraid decreasing step to half is not enough as I mentioned above.

> My first thought was to suggest Q-P keys as configurable steps for panning, but then I tried that on Kindle and it doesn't seem intuitive. After pressing a few more keys here is one possible alternative to pan step change:

I think that looks good. To make it intuitive, we can pop up a input box and just let users specify the step they want. How do you think about that?

**Comment by kljohann** [comment]
However on 2012.03 if I use Alt+> or Alt+< first and then press Alt+five way it works correctly. I have not looked at the source though so this is only what I'm experiencing.

**Comment by houqp** [comment]
> However on 2012.03 if I use Alt+> or Alt+< first and then press Alt+five way it works correctly. I have not looked at the source though so this is only what I'm experiencing. 

Are you using K3 or DXG? In my K3, five moves in in same distance as Alt+fiveway.

**Comment by kljohann** [comment]
I'm using a K3 too and alt+five way pans by a shorter distance when used immediately after alt+>. But maybe this is a bug and the alt modifier is not reset properly?

**Comment by kljohann** [comment]
I checked again and I am not able to reproduce this anymore without keeping alt pressed the whole time which makes this behavior explainable. Sorry for making noise.

**Comment by houqp** [comment]
solved by #247, close for now
