### ISSUE TITLE
Pressing Home should also quit Last Document view

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#598]
Right now user can only press back to quit Last Document view. However after pressing Home to quit current books, I always reach to home button to quit again then only to found I have to use back. 

I suggest that pressing Home should also quit Last Document to filechooser view.

**Comment by kai771** [comment]
I'm not 100% sure, but I think that if you ask tigran, Home should only quit KPV. Closing documents with Home is actually a bug :).

**Comment by dracodoc** [comment]
OK, I can live with that.

**Comment by kai771** [comment]
Personally, I think Alt-Home should be used for closing KPV, and that Home should be used to go to FileChooser, and if on n-th page of filechooser list to go to the first one (similar how Amazon does it), but it's just my opinion.

**Comment by eLiNK2gl** [comment]
I once made a similar suggestion.
Except that I suggested closing the KPV with Alt-Back (or was it Shift-Back? actually it does not matter).
I'd love to see Home used for some KPV relevant actions, like switching into 'home' directory in the FileChooser.
For me , Home is no longer the kindle framework :)
