### ISSUE TITLE
bug: history,screenshots,clipboard dirs not existant in emu

### ISSUE THREAD

**Issue by kai771** [koreader/kindlepdfviewer#609]
Don't you think we should either include them in Git or make them with make? Without history dir, emulator won't save settings per book. As it is now, they're only made in customupdate target.

**Comment by tigran123** [comment]
screenshots is not need in the emulator because this function doesn't work there. But the other two, yes, we should create them in make, just as we create libs-emu during the build.

**Comment by kai771** [comment]
@tigran123 Please fix it, since my fix probably wouldn't be elegant at all :).

**Comment by tigran123** [comment]
Ok, I added a commit to my PR #612 with the fix.
