### ISSUE TITLE
cannot delete bookmark in epub

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#615]
We can delete bookmark in pdf but cannot do the same in epub. I expect this should also be implemented in epub.

**Comment by tigran123** [comment]
When I wrote the code for deleting bookmarks I only supported PDF and DjVu. But you are right --- there is no reason why we shouldn't do the same for crengine-supported ebooks like epub, mobi, fb2, etc. I'll look into it.

**Comment by houqp** [comment]
closed as code lands in master
