### ISSUE TITLE
Coding Styles

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#62]
The cleanup work should leave to next release I think.

I went through the Lua wiki and following guidances relavent to our project:
- Booleans 

It can be helpful to prefix Boolean values or functions used as predicates with is, such as is_directory rather than directory
- Function naming
  camelCap
- Variable naming
  - All variables should use underscores: offset_x
  - global variables should be prefixed with `G_`: G_width
- Constants 
  ALL_CAPS
- Module/package naming
  Module names are often nouns with names that are short and lowercase, with nothing between words. (we are doing fine with this)
- i, k, v, and t are often used as follows:

``` lua
for k,v in pairs(t) ... end
for i,v in ipairs(t) ... end
mt.__newindex = function(t, k, v) ... end
```
- Class names

Class names (or at least metatables representing classes) may be mixed case (BankAccount), or they might not be. If so, acronyms (e.g. XML) might only uppercase the first letter (XmlDocument). 

Using of TOC breaks this ;P

**Some other tips I found might be useful:**
- Use locals rather than globals whenever possible. 
- End terminator

Because "end" is a terminator for many different constructs, it can help the reader (especially in a large block) if a comment is used to clarify which construct is being terminated:

``` lua
for i,v in ipairs(t) do
    if type(v) == "string" then
        ...lots of code here...
    end -- if string
end -- for each t
```
- Check empty table
  Determine if a table t is empty (including non-integer keys, which #t ignores):

``` lua
    if next(t) == nil then ...
```

Reference: http://lua-users.org/wiki/LuaStyleGuide

**Comment by houqp** [comment]
>  So: underscores are fine to me. But: what style will result in the least amount of needed fixes in the code? :-)

For current code, should be camelCap. :)

But given the better readability of underscores, it might reduce potential  bug in future.

**Comment by dpavlin** [comment]
- tabs for indenting

**Comment by houqp** [comment]
Since other developers are not so enthusiastic on changing style for function name, I suggest we stick to camelCap and use underscores for variable name (which is what most of current code does). Any comments?

**Comment by hwhw** [comment]
works for me :-)

**Comment by houqp** [comment]
I suggest if there is still no objection after the release, we should start cleaning up our code in next release.

**Comment by dpavlin** [comment]
I can't decide if link to this issue should go into README.TXT, should we move it to wiki and include link to that or 
create new file DEVELOPMENT.TXT in repository and distribution (and my slight preference is last one). What do you think?

Should we also provide information how to build cross compiler toolchain?

**Comment by hwhw** [comment]
I'm all for that DEVELOPMENT.TXT. It should contain links, a short explanation of the "two stages" of development, i.e. Lua programming only (only an editor needed), or Lua+C(++), for which a toolchain is needed.

That said, I have made further experiences with the toolchain. When using a rather new toolchain, say a newer Sourcery one, there's the problem with not-matching libstdc++ and libgcc. But this is in fact easy to fix: one just has to compile those both libraries statically into the resulting binary. That way, you can use a "standard" cross toolchain without looking out for old esoteric versions :-) (although gcc has special flags for statically linking those two libraries, they did not work for me. however, specifying them manually in the linker step did work fine.)

**Comment by houqp** [comment]
+1 for DEVELOPMENT.TXT

**Comment by houqp** [comment]
I suggest prefixing global variables with `G_` (or anything else). For instance, `width` and `height` can be written as `G_width` and `G_height`. Currently, the choose method of filechooser and selectmenu all have a `height` argument , which overwrites and is very likely to be confused with the global `height` defined in `reader.lua`. 

Also global prefixing can warn developers so they might think twice before changing that variable.

**Comment by hwhw** [comment]
This is a good idea. I like it much more than, say, drop all globals into a single table. I thought about this, but I like those prefixed globals better, I think.

**Comment by houqp** [comment]
closing for now as I have moved the guide line to wiki:
https://github.com/koreader/koreader-base/wiki/Coding-style
