### ISSUE TITLE
Run multiple versions of KPV through launchpad

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#623]
Because the new muPDF update changed the rendering effect for some scanned pdf, I was thinking if it is possible to keep 2 versions of KPV in different directories, then launch them by launchpad.

I copied the old version KPV to a directory called kindlepdfviewer-stable, then modified a kpv.ini in launchpad, but the key sequence still launch the newer version. It seemed that launchpad only run the kpdf.sh, which always run programs from the directory of kindlepdfviewer, so it will not go through other directories.

I'm not sure if it is worth the effort to support this, it depend on 2 things:
1. How many times the directory name is hard coded, how hard to abstract it.
2. Are there more people want to run multiple versions of KPV through launchpad?

If there is no real need from others, or it will be too much hassle, please just forget this.

What do you think about this?

**Comment by tigran123** [comment]
You can change kpdf.sh to go to the proper directory to do this.

**Comment by dracodoc** [comment]
I replaced the folder name in kpdf.sh, now it seemed working fine. So if anybody need to do this, he only need:
1. copy another version of kpv to a different directory name.
2. replace the directory name in kpdf.sh under kpv directory.
3. place a new ini in launchpad to launch this version, also use a different key combination.

**Comment by dracodoc** [comment]
Yes, @tigran123 , I just found out by myself too, thanks!
