### ISSUE TITLE
Time for the new 2012.11 release?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#633]
At the moment KPV is very stable and fast --- how about making a 2012.11 release?

The only bug I am aware of is that attaching the USB power (but not data) causes it to display "Going into USB mode..." and the message stays on the screen so you have to manually press Space to refresh the screen. But everything continues to work correctly while charging, so it is hardly worth fixing (because this is quite dangerous area and any change in that code can break it completely as I see that there are some fragile/empirical timeouts hardcoded in there....)

**Comment by houqp** [comment]
Yes, no objection :)

**Comment by aliabbasjp** [comment]
also please include the logical page number issue feature

**Comment by tigran123** [comment]
@dpavlin are you going to tag it or shall I do it? Is it just `git tag 2012.11` in the master and then push upstream or do you pass any extra options?

**Comment by houqp** [comment]
@aliabbasjp sorry that we might not be able to include it in this release because a new feature needs some time for testing to make sure it does not break other features.

@tigran123 , should be `git tag v2012.11`  ;p

**Comment by tigran123** [comment]
Ok, I am doing it now.

**Comment by tigran123** [comment]
I did `git tag v2012.11` and then `git push --tags origin` and also `git push --tags upstream`, but `git describe HEAD` still returns the number relative to the previous tag, i.e. `v2012.10-241-ga4fa231`. Any ideas what have I missed?

**Comment by tigran123** [comment]
Ah, `git describe HEAD` only looks among annotated tags and the one created by default is _not_ annotated. So I'll delete it and create a new one annotated as "Release 2012.11". So, the correct command sequence is:

```
$ git tag -a -m "Release 2012.11" v2012.11
$ git push --tags upstream
```

**Comment by tigran123** [comment]
I have uploaded the release, updated Wiki and announced it on mobilread.com and the-ebook.org forums.

**Comment by houqp** [comment]
Thanks @tigran123 :)

**Comment by dpavlin** [comment]
@tigran123 sorry for not replying earlier to your question, but I have quite busy few weeks ahead of me, and you correctly figured how to add tag. Congratulations on your first release, keep up the good work!
