### ISSUE TITLE
Cache doesn't work correctly for some fb2 books

### ISSUE THREAD

**Issue by ghost** [koreader/kindlepdfviewer#651]
I have a book in fb2 which is opened for very long time. Even in CoolReader it's opened for 22 seconds. There it's opened for 39-38 seconds. What is more strange, that it is opened 38-39 seconds always - in first session, second...tenth. And it has never been opened for less time. Seems, cr3cache should "help" to open files faster next times. But it doesn't work.
http://narod.ru/disk/64288901001.d227db21f8c675717ba5d5e663f12107/%D0%9A%D0%9E%D0%91%D0%97%D0%90%D0%A0%20edit.fb2.html

Here's a link to mentioned file. If this is bug - maybe somebody might fix its. If this is just a feature of this file - ignore it)

**Comment by houqp** [comment]
Thanks for the report :)

@dpavlin is the cache expert here. I will also take a look at it when I have time.

**Comment by houqp** [comment]
This is fixed in https://github.com/hwhw/kindlepdfviewer/pull/706

First open required 25s. When the cache is generated, only 2-3s on open. Thanks for report :)
