### ISSUE TITLE
Integrate KPV into Kindle framework with KPVBooklet

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#653]
The idea of implementing a booklet to startup external application is originated from @bhaak with an example booklet called [HackedUpReaderBooklet](https://github.com/bhaak/HackedUpReaderBooklet) which is used to launch CoolReader for Kindle. I modified the code to accommodate with KPV. And I add an interface to  synchronize the last access and reading progress between KPV and Kindle's content catalog. The source code can be found at  https://github.com/chrox/KPVBooklet . And the KPVBooklet.jar can be downloaded at https://github.com/chrox/KPVBooklet/downloads.

HOW_TO_INSTALL:
1.  copy `KPVBooklet.jar` to `/opt/amazon/ebook/booklet`</li>
2.  add the entries below into appreg.db to associate KPVBooklet with PDF , DJVU and Epub documents:

```
INSERT INTO "handlerIds" VALUES('com.lab126.booklet.kpvbooklet');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','lipcId','com.lab126.booklet.kpvbooklet');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','jar','/opt/amazon/ebook/booklet/KPVBooklet.jar');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','detailFactoryPath','/opt/amazon/ebook/lib/detail_view.jar');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','detailFactoryClass','com.amazon.ebook.booklet.reader.impl.detail.ReaderDetailViewFactory');

INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','maxGoTime','0');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','maxPauseTime','60');

INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','default-chrome-style','NH');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','extend-start','Y');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','searchbar-mode','transient');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','supportedOrientation','URL');

INSERT INTO "associations" VALUES('com.lab126.booklet.kpvbooklet','application','MT:application/pdf','true');

INSERT INTO "mimetypes" VALUES('djvu','MT:image/x.djvu');
INSERT INTO "extenstions" VALUES('djvu','MT:image/x.djvu');
INSERT INTO "properties" VALUES('archive.displaytags.mimetypes','image/x.djvu','DjVu');
INSERT INTO "associations" VALUES('com.lab126.generic.extractor','extractor','GL:*.djvu','true');
INSERT INTO "associations" VALUES('com.lab126.booklet.kpvbooklet','application','MT:image/x.djvu','true');

INSERT INTO "mimetypes" VALUES('epub','MT:application/epub+zip');
INSERT INTO "extenstions" VALUES('epub','MT:application/epub+zip');
INSERT INTO "properties" VALUES('archive.displaytags.mimetypes','application/epub+zip','EPUB');
INSERT INTO "associations" VALUES('com.lab126.booklet.kpvbooklet','application','MT:application/epub+zip','true');
INSERT INTO "associations" VALUES('com.lab126.generic.extractor','extractor','GL:*.epub','true');
```

Then you can restart framework to activate KPVBooklet. And it will automatically scan the additional supported files in documents directory.

KNOWN_BUG:

<del>The menu bar in home screen(called ChromeHeaderBar)  does not show up when exiting from KPV.</del>

SUGGESTED_FEATURE:
Extract document information from Epub files.

KPVBooklet is a preferred alternative to the solution proposed in #648.

**Comment by chrox** [comment]
@bhaak Hi, I would like to know if there is also a ChromeBar issue mentioned above in HackedUpReaderBooklet. When I run the command `lipc-set-prop com.lab126.pillow displayChrome true` after KPV exits, winmgr says `no chrome to raise`. And chrome bar will not show up even after a framework restart. But after I start a native booklet as opening a mobi file, the chrome bar will be raised correctly.

**Comment by bhaak** [comment]
@chrox No, although I don't have a PW to test, I've only got a Touch. I don't see anything in KPVBooklet that would cause this from my understanding of the framework and then that this persists even after a framework restart is quite odd.

**Comment by chrox** [comment]
@bhaak That's really strange. Now I extend KPVBooklet from ReaderBooklet directly which mimics exactly the patching approach in https://gist.github.com/4193209. But the patching approach works fine while the extending approach still has the chromebar issue.

**Comment by bhaak** [comment]
@chrox I had a look into /usr/lib/libpillow.so and noticed the next to displayChrome there was a dismissChrome.

The last parameter isn't a boolean apparently and just needed as the system needs any value. Try this to remove the ChromeBar:
    lipc-set-prop com.lab126.pillow dismissChrome 1

**Comment by chrox** [comment]
Now ChromeHeaderBar is working after exiting KPV by adding the following entries into appreg.db:

```
INSERT INTO "handlerIds" VALUES('com.lab126.booklet.kpvbooklet');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','detailFactoryPath','/opt/amazon/ebook/lib/detail_view.jar');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','detailFactoryClass','com.amazon.ebook.booklet.reader.impl.detail.ReaderDetailViewFactory');
```

But this issue is only partially solved. The ChromeTitleBar which displays device name, or book title when reading a book is still not working. I guess its because some part of the booklet cannot extract book title from epub file. Missing the book title the titlebar just dies. I will check that later.

Ah, after adding these entries both ChromeTitleBar and ChromeHeaderBar are working perfectly.

```
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','maxGoTime','0');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','maxPauseTime','60');

INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','default-chrome-style','NH');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','extend-start','Y');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','searchbar-mode','transient');
INSERT INTO "properties" VALUES('com.lab126.booklet.kpvbooklet','supportedOrientation','URL');
```

**Comment by chrox** [comment]
Now KPVBooklet is at https://github.com/chrox/KPVBooklet.

**Comment by houqp** [comment]
awesome! I am installing it now :)

**Comment by houqp** [comment]
I just downloaded the binary from your repo. It works like a charm :+1: 

Now l think we need an auto install script :)

**Comment by chrox** [comment]
And probably we need an update_kpvbooklet_5.30_install.bin. I will figure out how to pack these things up.

**Comment by chrox** [comment]
KPVBooklet works fine on firmware 5.12, 5.20, 5.30 and 5.31. So this issue is closed.
