### ISSUE TITLE
Uploads/downloads are deprecated on whole site of Github. 

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#663]
See the official blog: https://github.com/blog/1302-goodbye-uploads

I'm afraid it will be not as easy as before to release KPV binaries.

**Comment by hwhw** [comment]
Too bad :-( Well, I'll think about alternatives. The obvious being
mobileread forum downloads, but as I've heard, mobileread has some things
in the queue, a different approach to downloads may be feasible there.
OTOH, I have a dedicated server that I could offer. Will need to calculate
needed bandwidth, though... 20.5k downloads for 2012.09 scares me a bit,
but it should be within my per-month limits.

**Comment by houqp** [comment]
Or do a repo mirror in bitbucket? Since they also have download feature.

**Comment by tigran123** [comment]
And what is to stop us from creating a `bin` directory in the source code and placing distribution .zip files in there? Currently we have pdf files in the `test` directory and I just tested that clicking on the "View Raw" link causes a direct download of the physical file. Presumably this is true not just for pdf but for zip files also?

**Comment by houqp** [comment]
If we want to put bin in repo, we should create a gh-pages branch for that. It works, but will missed the fun of download counting ;)

**Comment by chrox** [comment]
The tricky part of downloading binaries from source trees is clicking "View Raw" link. But if someone mistakenly downloads the "blob" one, he/she probably will get a broken zip file which will definitely complicate the installation process. And what's even worse is that the broken part of directly downloaded files is undefined which may brick devices in certain circumstances as @houqp was encountered when installing jbpatch.jar. Details of this accident can be found at #648.

**Comment by tigran123** [comment]
Ok, then let's do it properly, i.e. by hosting it elsewhere. Let's not risk breaking user's devices or causing any inconvenience.

**Comment by milekpl** [comment]
The downloads may go to code.google.com

**Comment by houqp** [comment]
Yeah, code.google.com is also a good place for file hosting. I actually prefer google code, how about others?

**Comment by tigran123** [comment]
I used sourceforge and github and github is definitely better. But I haven't use code.google.com...

**Comment by houqp** [comment]
It's definitely not as good as github, but if we just want to use it for file hosting, it's fine. @hwhw also has a project hosted on googlecode:
http://code.google.com/p/droidreader/downloads/list

**Comment by tigran123** [comment]
I would like to understand how @chrox manages to make nightly builds if the official upload api is gone? What I am saying is that if @chrox way works and will continue to work indefinitely then we have no real problem, i.e. we just wait for the next nightly build to appear (corresponding to a tagged release) and point to it from the Wiki Downloads page.

**Comment by houqp** [comment]
If I remember correctly, the api will be closed after about two months.

**Comment by houqp** [comment]
Just saw it yesterday in a local LUG maillist that github is block by China's GFW. @chrox , can you verify this? I guess the GFW in Beijing blocks more sites than other cities in China....

**Comment by chrox** [comment]
Yes. The whole site of github.com is blocked in most part of China. I will migrate the nightly builds to google code tonight.

**Comment by chrox** [comment]
Migration done. Now nightly builds are at https://code.google.com/p/kindlepdfviewer-package/downloads/.

**Comment by houqp** [comment]
Thanks, I think we can close this now?

**Comment by chrox** [comment]
Yes. And we will wait to see if the build robot could upload new packages to Google code.
