### ISSUE TITLE
Bug in crereader after rotating screen

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#668]
After opening EPUB/MOBI files, pressing J/K keys will rotate screen clockwise/counterclockwise respectively. But in the most recent version(gea2bae5) when screen is rotated to landscape the screen is divided to two-columns too, which is an unexpected result. And one has to press PAGE_FORWARD key twice to scroll out one screen.

**Comment by tigran123** [comment]
Fix merged into master.
