### ISSUE TITLE
handle corruted item in TOC

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#67]
Some TOC comes with item that has no page number. Refer to discussion under this commit: https://github.com/hwhw/kindlepdfviewer/commit/c8f87d5661208896a0529b020dae3448b53b85a9

**Comment by dpavlin** [comment]
I'm under impression that this problem is no longer issue. Am I mistaken? Can we close it @houqp ?

**Comment by houqp** [comment]
Um.. seems that there is still no code to handle TOC entry without page number. I think it can be closed as long as kpdfview can correctly fix the TOC in one of the book that traycold has (refer the the comment in c8f87d5661208896a0529b020dae3448b53b85a9).

**Comment by traycold** [comment]
@houqp : you are right (i.e.: no code in kpdfview to handle corrected TOC); but on the other end, in my case actually was the TOC to be broken (i used a pdf split/merge tool to generate that document); probably, it's not possible in normal situations that a TOC having pages without page numbers may exist.
Moreover, even in that case, kpdfview doesn't crash, just jumped to page 1 when an item without page number appeared on the TOC.
So, for me, +1 to close the issue.

**Comment by houqp** [comment]
OK, so let's close it :)

**Comment by eLiNK2gl** [comment]
it looks like the pdf2djvu (http://code.google.com/p/pdf2djvu/) creates djvu files, which are somewhat problematic.
The Pdf & Djvu Bookmarker (http://sourceforge.net/projects/djvubookmarker/) reports there are no page numbers attached to the TOC entries but the WinDjView (http://windjview.sourceforge.net/) handles them just fine.

Such files crash the kpdfviewer upon calling the TOC.
The message from the crash.log is "Segmentation fault".
