### ISSUE TITLE
pdf viewer cannot remember last read position

### ISSUE THREAD

**Issue by johnskiller** [koreader/kindlepdfviewer#701]
when exit pdf viewer from document menu , it can save last read position, but when close cover/use power button to enter screen saver mode, then wake up again it did not back to last opened book, but return to file browser. When open last read pdf again, it show last saved position which was saved from last normal exit, not the position when left for screensaver

posible cause: KPV only save last read pos when exit from menu, not every page turn?

KPW 5.3.1 with KPV2012.04.2

**Comment by houqp** [comment]
Are you using the latest code? It should be fixed in this PR: https://github.com/hwhw/kindlepdfviewer/pull/699

**Comment by johnskiller** [comment]
I'm using kindlepdfviewer-v2012.04.2-585-gc487bd6.zip d/l from https://github.com/chrox/misc/downloads

will check newest version and report back

**Comment by johnskiller** [comment]
yes, it was fixed in kindlepdfviewer-v2012.04.2-593-g3793b97.zip — kindlepdfviewer-touch-nightly-20130110

**Comment by chrox** [comment]
Bug already fixed in new_ui_code branch. So this issue is closed.
