### ISSUE TITLE
Time for a 2013.1 release of KPV?

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#707]
Is this a good time for 2013.1 release? Are there any critical fixes still outstanding?

Or should we wait a bit and make both KPV and the new yet to be named version for touch/paperwhite available simultaneously?

Btw, with no upload facility I guess we'll need to wait for the first nightly build of the new release to appear and then point to it from the Wiki page.

**Comment by houqp** [comment]
Yes, but maybe wait for a couple of more days? I am not sure whether the page mode is stable enough and we have new commits just landed in master.

As for the new version, it's just working right now and we need some time to stabilize it, so no need to wait for it :)

For upload, we can use bitbucket as a temporary download site, I just created my own ;p
https://bitbucket.org/houqp/kindlepdfviewer/downloads

**Comment by tigran123** [comment]
Ok, let's test it for a few more days. The gamma support in crengine doesn't seem to work properly, i.e. the difference between two values is negligible and even after pressing it 30 times or so (to get to the maximum) it is only very slightly different from the minimum value (or maybe even that is optical illusion?). Maybe we should increase the maximum or increase the step or both?

**Comment by houqp** [comment]
Maximum seems to be bounded by crengine, but we could change the step to 2 or even higher. I changed the step to 2 in new ui branch for testing purpose, so haven't applied it to master yet. You can try with different value and see which is the best :)

**Comment by mayabtlaloc** [comment]
wish you could fix the gamma. I would be very grateful!

**Comment by houqp** [comment]
@mayabtlaloc you mean increasing the step?

**Comment by mayabtlaloc** [comment]
houqp : no, I mean the maximum increase much more, because even with the maximum (30) dark tone is very clear

**Comment by houqp** [comment]
Oh, that won't be a easy task then because we have to dig through coolreader's code. Did you find it unreadable in all your documents or just some?

**Comment by mayabtlaloc** [comment]
I do not think it's a code problem, because the gamma coolreader3 works well with the same books

**Comment by houqp** [comment]
Oh, really? That's strange, because I saw that the maximum gamma value is hard coded in crengine. So you mean coolreader3 can display darker font than KPV?

**Comment by tigran123** [comment]
Yes, it does actually. I wanted to show you screenshots to compare, but  I don't know how to make one in coolreader3. Does anyone know?

**Comment by houqp** [comment]
Ah, no need to do the screenshots, I believe what you guys said ;p

Now we need to figure out how coolreader did this.. 

A quick grep through the android reader gives me no hint, sigh..

**Comment by tigran123** [comment]
I must warn you that it may not be a simple issue of gamma setting, so we may be chasing a wild goose (or red herring) here... Namely, there is only one very "special" version of CoolReader3 (very precious to me due to this fact) that has _ideal_ rendering of very complex fonts like Adobe Garamond Premier Pro. Only this version (i.e. compared to many previous and later versions I tested) has rendering superior to KPV. All others are either the same or inferior, including the very latest build. Now, what is special about this version is that it is linked with a particular version of freetype and also a particular qtKindle build, NOT matching the ones used in the latest coolreader3.

So, when I say "CoolReader3 is superior to KPV when viewing fb2 files" I only refer to this "lucky" version, so this is unfair comparison, I suppose.

**Comment by houqp** [comment]
wow, that's very interesting :) Even though I haven't check the full code, I am quite sure that we can patch crengine to render darker font with freetype. But I think this is not the right way to do.

where can we get that "lucky" version of CR3? (would be better if you reply to #718 ;p)

**Comment by houqp** [comment]
BTW, @tigran123 , feel free to do the release if you think it's ready. I think I am done with the bugs that I can fix for this release.

**Comment by tigran123** [comment]
ok

**Comment by tigran123** [comment]
I tagged the release as "v2013.1", so now it is a matter of nightly builds picking it up and we can update the Wiki to point to it.

Update: updated Wiki and announced on mobileread.com and the-ebook.org forums.
