### ISSUE TITLE
add css selection menu for crereader

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#711]

**Comment by kai771** [comment]
If anyone is interested, this feature is present in Librerator.

**Comment by tigran123** [comment]
If this feature is really worth having then someone would bother porting it to KPV. I, for one, don't think it is worth spending time on it as CoolReader3 for reading fb2 files is still superior to KPV, even with the latest addition of hyphenation and page mode to the latter... The real strength and value of KPV is in the PDF and DjVu area, not in crereader.

But there is no harm in porting it, if someone has the time of course :)

**Comment by houqp** [comment]
closed since feature implemented in master
