### ISSUE TITLE
new_ui crash

### ISSUE THREAD

**Issue by johnskiller** [koreader/kindlepdfviewer#725]
after install newest version from chrox download(kindlepdfviewer-v2013.1.zip), the kpv could not started. crash.log shows:

`lua config error: ./reader.lua:107 error opening input device </dev/input/event1>: 2`

what's wrong?

I'm using kindle paperwhite with firmware 5.3.1

**Comment by chrox** [comment]
The newest version kindlepdfviewer-v2013.1.zip is for keyboard Kindle not for touch. While you can find the secret build channel for touch at https://github.com/chrox/misc/downloads in which the latest build is kindlepdfviewer-v2012.04.2-621-gf99cea8.zip as for Jan 21.

**Comment by johnskiller** [comment]
oops, how stupid am I

**Comment by johnskiller** [comment]
it works. thanks.
