### ISSUE TITLE
rotate issue for new_ui

### ISSUE THREAD

**Issue by johnskiller** [koreader/kindlepdfviewer#726]
use backdoor to open a pdf with native view, rotate screen then close.
open same pdf with kpv and it was in rotated mode to which is fine.

To show document menu, I have to touch the top of screen, not the left side. the document menu shows at left side which is right but I have to use original position to close it( touch some where near the top of screen)

**Comment by houqp** [comment]
The touch version cannot handle screen rotate yet, sorry ;p

**Comment by houqp** [comment]
close for now since it's fixed in new ui branch
