### ISSUE TITLE
return to native system on Touch

### ISSUE THREAD

**Issue by th0mass** [koreader/kindlepdfviewer#731]
I want to use KPV with the new launcher instead of KPVBooklet. This launcher extension seem to work fine: http://www.mobileread.com/forums/showpost.php?p=2406316&postcount=5  .  However  I need an option to return to the native system  

like this item on redaermenu.lua: 
table.insert(self.item_table, {
        text = "Return to file browser",
        callback = function()
            UIManager:close(self.menu_container)
            self.ui:onClose()
        end
    })

**Comment by houqp** [comment]
Yep, I am working on it since Kobo also needs this :)

**Comment by houqp** [comment]
closed as fix merged into master

**Comment by th0mass** [comment]
thanks :+1:
