### ISSUE TITLE
Screen getSize returns wrong width on Paperwhite

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#744]
Now Screen:getSize() returns 

```
# Screen size {
    ["h"] = 1024,
    ["w"] = 768
}
```

It ought to be 1024*758. This bug was introduced in #732.

**Comment by houqp** [comment]
Um, this is very strange, because screen width is calculated as `buf.pitch * 2`, which should be the real line_length for the framebuffer. If I remember correctly, this should be 758. I don't have the device with me right now, will have a look tonight.

**Comment by houqp** [comment]
Damn, I finally figure out what's happening now... So I have to create a 1024_758 blitbuffer but before updating screen, it needs to be padded with 10px dummy pixels each line in order to fit into kindle's 1024_768 framebuffer.

Why does amazon come up with this strange design ...
