### ISSUE TITLE
hide the technical folders in documents folder.

### ISSUE THREAD

**Issue by th0mass** [koreader/kindlepdfviewer#759]
It would be a good idea to hide the folders  which has a name ends with ".sdr" .  This way navigation through files could be easier.

**Comment by chrox** [comment]
The "sidecar" (sdr) folders are generated by the native system to hold metadata of the documents. So it has nothing to do with KPV. See http://www.blog.asafewebsite.com/2011/06/amazon-kindle-forensics.html

**Comment by th0mass** [comment]
I know this. what i mean is different: when I use KPV I see this folders on the file manager list. they can be not listed.

**Comment by tigran123** [comment]
I would say it is a bad idea to enforce such a policy, at the very least in the Unrestricted mode all directories and files should be visible.

**Comment by chrox** [comment]
On firmware 5.\* each amazon document (mobi and azw files) will have a "sidecar" folder in the documents directory. One may need to skip several pages of "sidecars" in order to find certain document in KPV's Filemanager. So I think it can be justified to set that policy. Anyway in the future the exclude file pattern should be editable by the users. It will become a filtering mechanism.

**Comment by chrox** [comment]
And PR is sent in #761.

**Comment by houqp** [comment]
I would prefer to add a config entry in `settings.reader.lua` so users themselves can decide what to filter.

**Comment by chrox** [comment]
Close this issue since PR is merged.

**Comment by chrox** [comment]
We should not expect that all users could edit the src code in a proper way to config the behavior of KPV. Some even don't have a decent text editor to do the job. The ultimate way is to provide a unified interface inside the KPV reader for configuration.

**Comment by houqp** [comment]
yeah, but that has a long way to go. ;p

**Comment by th0mass** [comment]
Sorry for the misleading title and thanks for your responses.
