### ISSUE TITLE
Nagios alert inquiry (for pc-lvc01 and pc-lvc02)

### ISSUE THREAD

**Issue by fadrian** [koreader/kindlepdfviewer#764]
Please advise on the following Nagios alerts:

pc-lvc02 11h 26m 26s CRITICAL - 11.3.8.76: rta nan, lost 100% 
pc-lvc01 11h 26m 30s CRITICAL - 11.3.8.75: rta nan, lost 100%

**Comment by hwhw** [comment]
nope, sorry. Try to find the right site to report this, I - and I guess the other developers - don't have the slightest idea what you are talking about.

**Comment by fadrian** [comment]
Thanks, and sorry about the confusion.

Favio Adrian
Computer Operations

International Securities Exchange
60 Broad St., New York, NY 10004
Computer Operations: 212-897-0288  Option 1
Network Operations: 212-897-0284 Option 2

Market Operations: 877-473-9989

Technology Member Services: 212-897-0244

computeroperations@ise.commailto:computeroperations@ise.com
[cid:image001.png@01CA57AF.636D9620]
