### ISSUE TITLE
a full refresh after exit?

### ISSUE THREAD

**Issue by th0mass** [koreader/kindlepdfviewer#775]
When I exit it from KPV it doesn't refresh the screen. And even when I use home button once more upper part of the screen remains unchanged.

However [KindleExplorer](https://code.google.com/p/kindle-explorer/) exits smoothly. I think you may want to look at it. I'll try but I have very very little coding info hence it's a hopeless attempt. 

using Kindle Touch+KUAL+latest nighly build

**Comment by houqp** [comment]
That's interesting, will take a look on that next weekend. Thanks for the link :)

**Comment by houqp** [comment]
Cannot find any special cleanup code in KindleExplorer. My guess would be it's using GTK which does not conflict with the native UI framework. While KPV is using it's own UI framework which takes over framebuffer and all other stuffs from native system.

**Comment by th0mass** [comment]
thanks fixed on 20130313 :+1:

**Comment by chrox** [comment]
This issue is closed since patch is already merged.
