### ISSUE TITLE
Shortuct for refreshing page

### ISSUE THREAD

**Issue by artemstorozhuk** [koreader/kindlepdfviewer#78]
Hi,

It would be great to have shortcut for refreshing page (like in CoolReader). I've seen such method in API.
Or is it possible for program to refresh page after each leaf (like in default pdf reader in kindle)?

Thanks.

**Comment by houqp** [comment]
Thanks for the report.

> It would be great to have shortcut for refreshing page (like in CoolReader). I've seen such method in API.

One workaround for this could be editing the `unireader.lua` file. Goto the definition of `Unireader:showMenu` function and you can see following code:

``` lua
fb:refresh(1)
```

Change that `1` to `0`. Now everytime you double press the `menu` key, kindlepdfviewer will do a full screen refresh.

> Or is it possible for program to refresh page after each leaf (like in default pdf reader in kindle)?

Yes, again, you can achieved this by editing `unireader.lua`. At about line 25, you can find a assignment for `rcountmanx` and `rcount` variables. Change both of them to 1 will do the trick:

``` lua
-- framebuffer update policy state:
rcount = 1,
rcountmax = 1,
```

We will add a configurable entry in .reader.kpdfview.lua in next release :)
