### ISSUE TITLE
a small problem on manual cropping.

### ISSUE THREAD

**Issue by th0mass** [koreader/kindlepdfviewer#795]
while setting  the active area, the page should be displayed smaller to be able to set the area borders very close to one edge of a page. I personally can't set a border  too close to a screen border on Touch. (landscape mode helps me for now)

**Comment by houqp** [comment]
you mean manual cropping?

**Comment by th0mass** [comment]
yes. 
(I fixed the title, sorry)

**Comment by houqp** [comment]
Yeah, I also have the same problem.

@chrox , could you take a look at it? I really should go to sleep now ;p

**Comment by chrox** [comment]
Now fine tuning of bbox size is implemented with a swipe gesture around the four edges of the box. You can give it a try with the latest nightly build.

**Comment by chrox** [comment]
Patch already merged, so this issue is closed.

**Comment by th0mass** [comment]
thanks for fixing this, not tried yet though
