### ISSUE TITLE
switch default branch on github to new ui branch

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#802]
master is some how under maintenance mode now, should we switch the default branch on github to new_ui_code? 

I cannot see the project setting tab. So seems that only @hwhw can make the changes, it should be under the fork button BTW :)

**Comment by clenton** [comment]
it is a good idea

**Comment by houqp** [comment]
another choice will be we factor out the core backend part and split the project into three repos:
- kpv-core
- kpv
- koreader

For that, we should better create an organization page so we can also include all the other forks of KPV and @chrox 's KPVBooklet.

**Comment by chrox** [comment]
I think the second choice is better to eliminate the confusion of these projects. And in this way we could resolve this matter once and for all.

**Comment by houqp** [comment]
@hwhw , @dpavlin @tigran123 , what do you guys think about that? This idea come into me when I notice that it could be weird when some searching koread and google gives out the link: https://github.com/hwhw/kindlepdfviewer

If we take this approach, we should do it ASAP because release will likely be in next week and we need to have more time for testing.

**Comment by hwhw** [comment]
So many great additions lately. Yes, I guess it's time to change. I'll need
to do a close look on how to do this repository maintenance - I'll only
have time for that in ~30 hours, sorry. But of course I'll look into it. I
agree that the release point is likely in the next week - all is very well
prepared for that. Thank you all so much.

**Comment by houqp** [comment]
Thanks @hwhw, 30 hours should be enough :) I think it won't take too much work. Probably put all the document render related modules and dependencies into a core repo, then use that as a submodule in both old/new code base repo.

We probably don't want to put the input and eink module into core because it diverges too much in both branches.

**Comment by houqp** [comment]
we might not need this, but in case we do, following is a post on how to move subdirectories into repositories.
http://airbladesoftware.com/notes/moving-a-subdirectory-into-a-separate-git-repository

EDIT: also this link:
https://help.github.com/articles/splitting-a-subpath-out-into-a-new-repo

**Comment by hwhw** [comment]
I'm still reading up on git-rebase and stuff.

Then I'll need to check what to split into which repository.

**Comment by houqp** [comment]
Let us know if there is anything we can help with :)

ownClound community is recently splitting their repo now using the second link I posted above. Seems to work pretty well :)

**Comment by hwhw** [comment]
A bit restructuring will be needed - specifically it's factoring out the
"core", i.e. the Lua-C-API that is shared between old and new UI. And I
guess that LuaJIT, muPDF, djvulibre and creengine might also be included by
that "core" part, but then it might be enough to only separate out our own
"core" and have the "old" KPV include those third-party libs as well as the
"new" Koreader.

If someone beats me to it - factoring out the C API to a subdirectory would
be a welcome thing to do.

**Comment by houqp** [comment]
Will give it a try when I have time :)

I am trying to create an organization in github to hold all the repos. Unfortunately, KPV has already been taken, how name like `OpenEink`?

**Comment by tigran123** [comment]
Eink might be a trademark. And OpenInkpot is already taken.

**Comment by houqp** [comment]
wow, just checked it out, openinkpot is a very interesting project :)

How about using the new name KOReader?

**Comment by hwhw** [comment]
I'm in the course of doing the repository split now. I've settled on
- koreader-base for the Lua/C API,
- koreader for the frontend Lua code for the former new_ui_code branch,
  and I'm unsure of whether I should create a "koreader-legacy" repository,
  renaming this one, or just keep this one as is and include "koreader-base"
  here.

Will report back soon!

2013/3/21 {Qingping,Dave} Hou notifications@github.com

**Comment by hwhw** [comment]
I factored out the koreader-base repository. All collaborators were added
to that. While I was happily hacking and creating a "koreader" repository,
I made up my mind and came to the conclusion that we need a tad bit more
discussion: A new repository would not migrate the issues in the issue
tracker. I'm not sure yet if that is good or bad: starting from scratch
there might also be a good thing. So maybe, it's OK to go with a new
repository. Maybe we should rename this one to "koreader" and either create
a "koreader-legacy" repository for the old codebase, or even make that a
"legacy" branch of this one (like now, but reversed - and of course with
factored out C/C++ API).

**Comment by hwhw** [comment]
OK, I've created a new koreader repository (you're all collaborators
there, too). Let's start there from scratch (well, concerning issues,
that is, of course file history is retained!). It contains code from
the new_ui_code branch - it's building already, but the Makefile still
needs a bit of love. So please go ahead and work in that new
repository!

This repository - kindlepdfviewer - is the legacy frontend code
repository. I'm currently updating the legacy code to use
koreader-base for the C/C++ API. In the long run, the "new_ui_code"
branch can be deleted (as well as some other branches which are
out-of-development now).

Let's see how this all works out. And please comment. We still have
the option to change things.

**Comment by hwhw** [comment]
I've made a minor error so the KindlePDFviewer repository is now
already updated. I intended to do the changes to the "legacy" branch -
instead, that branch now reflects the state of the legacy code base
before factoring out koreader-base. Nothing to worry, I guess.

State of things is now:

Repository koreader-base: this is the C/C++ API, shared for old
KindlePDFviewer (legacy) codebase as well as the new koreader
codebase.

Repository koreader: frontend code for the new codebase, formerly
branch "new_ui_code".

Repository KindlePDFviewer: legacy codebase

**Comment by houqp** [comment]
Code looks a lot cleaner now :)

One suggestion, I would be better to create a koreader organization page so we can put all the KPV related stuffs in there, like KPVBooklet. And you don't need to manually add people to repo owner every time a new repo is created ;p

**Comment by hwhw** [comment]
Thanks - and I need to look into that organization thing, I've never really
bothered yet. But that might be a good idea, agreed.

And yes, I also find this to be much cleaner now. And maybe it's a bit more
inviting to start hacking, now that the distinction between frontend code
and backend API is more clear.

**Comment by houqp** [comment]
Also all the repos can be transferred to an organization so we won't lose all the issues and stars. Did I mention that we are the top 4 Lua project in Github? ;p

**Comment by hwhw** [comment]
Oh! Nice :-) So one more reason to keep this repository and - maybe -
rename it. OK, I'll look into that organization thing.

**Comment by hwhw** [comment]
So I'm stuck with a few issues/questions regarding the organization thing.

#1: I would be ready to convert my user account to a organization
account (which seems it is how it is done). This will likely (though I
found no confirmation, but I guess it is and stays the same
repository) preserve the status of the project (stars).

#2: In the first step, the name of that organization would still be "hwhw".

#3: I will then create a new personal account and move my other
projects there. None of them have a relevant user base, i.e. they are
all more or less personal stuff.

#4: Is it possible to change the organization name to "koreader"
afterwards? What are the implications?
#4a: will stars be kept, i.e. is it still the same repository within
the limits of Github?
#4b: is there some kind of mechanism that makes the old references
still work? within other Github repositories? outside of them?

It's a bit unclear to me right now.

**Comment by houqp** [comment]
I have created the organization page and added all of current contributors so you can keep your personal account :)

Now, we can start transfer ownership of repo to the organization (it's on repo's setting tab), all the issues and stars will be kept.

Um.. what do you mean by old references?

**Comment by hwhw** [comment]
OK, I'll start with the new repositories, then see what happens. I mean the references that others keep in their forked repositories or repositories that include ours as a sub-repository (not likely, I guess).

**Comment by houqp** [comment]
Just checked, the reference is also updated, great!

**Comment by hwhw** [comment]
OK. The submodule isn't, though. But I guess that is a minor. A bigger issue is that there is no redirection for the old URL.

My suggestion:
- move the old "kindlepdfviewer" repository, too - and maybe rename it to "koreader-legacy" then?
- I'll create a new "kindlepdfviewer" repository in my account, containing only a README that will point users to the new place. This will serve well for old links on the Web, I guess.

What do you say?

**Comment by houqp** [comment]
Yes, that's the way to go :)

I would prefer to keep the old `kindlepdfviewer` naming for the old code base

**Comment by hwhw** [comment]
OK, easier to see what happened that way. I'll have a go then.

**Comment by houqp** [comment]
Will you also update the submodule reference? If so I will work on emulator bootstrap target.

UPDATE: never minde, it's already updated ;p

**Comment by hwhw** [comment]
Yep, did so. The new informational page on http://github.com/hwhw/kindlepdfviewer is now also in place.

Edit: Uh, I guess I now have definitely broken the nightly builds. Sorry. My fault, should have made a list. But that aside, it seems to have worked quite well.

**Comment by houqp** [comment]
yeah, @chrox should be sleeping right now, hopefully he can fix the build script when he wake up ;P

**Comment by houqp** [comment]
closing for now.
