### ISSUE TITLE
readers crash when paging from TOC

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#815]
I didn't reproduce this bug in the emulator. But it happened in both pdf reader and epub reader on Kindle. Debug info says 

```
*** glibc detected *** ./kpdfview: double free or corruption (!prev): 0x00655630 ***
```

or simply: `Segmentation fault`.

**Comment by chrox** [comment]
And more tests show that it crashes much more often in landscape mode than portrait mode. You can reproduce it by opening any pdf documents with TOC information and just selecting several TOC entries. It will crash randomly with these info:

```
Segmentation fault
```

or

```
*** glibc detected *** ./kpdfview: double free or corruption (!prev): 0x00655630 ***
```

or

```
*** glibc detected *** ./kpdfview: malloc(): smallbin double linked list corrupted: 0x007084a8 ***
```

or

```
kpdfview: malloc.c:4636: _int_malloc: Assertion `victim->bk_nextsize->fd_nextsize == victim' failed.
```

**Comment by chrox** [comment]
This bug also exists in kindlepdfviewer-v2012.04.2-676-g72eecac.zip, the very first version we introduced landscape screen mode.

**Comment by houqp** [comment]
um, heap corruption bug....

will take a look tomorrow :P

**Comment by houqp** [comment]
close for now
