### ISSUE TITLE
Suggest to use Left to move up in folders

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#819]
I think an natural operation in file browser is to use the Left of the five way rocker of DX/K3 keyboard to move to parent folder. This should be extremely simple to implement, and it will save some time for user if the file list is rather long.

**Comment by houqp** [comment]
Thanks, will implement it tomorrow :)

**Comment by houqp** [comment]
closing for now. Current master branch still has a bug on font rendering. We are still trying to fix it. You might just want to copy the latest file chooser file into your kindle.
