### ISSUE TITLE
Update k2pdfopt to v1.65

### ISSUE THREAD

**Issue by andreimariusb** [koreader/kindlepdfviewer#834]
Hello,
Could you update the nightly built to the latest k2pdfopt ?

**Comment by chrox** [comment]
Sorry that the nightly build script for kindlepdfviewer failed to make installable package. Anyway I fixed it just now. And there should be a new download in the download page.

**Comment by andreimariusb** [comment]
Thanks :+1: 
I think you should also add the information to the wiki / Download section about the update of k2pdfopt to the 1.65.

**Comment by chrox** [comment]
OK. Will do that right now. :-)
