### ISSUE TITLE
Fit content mode should align to center

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#844]
When I defined a page box by shift-x then use shift-a to fit content, the cropped page will align to left side which is not very good looking. I believe the previous version don't have this problem.
Of course I can move the page to center manually, however 2 books with manual movement will interfere with each other, So this manual method is not practical.

**Comment by houqp** [comment]
confirmed, will fix that tomorrow

**Comment by houqp** [comment]
Hi @dracodoc , could you check my RP to see if it works? I have no idea why previous version does not have this bug though...

**Comment by dracodoc** [comment]
@houqp , it worked now. Thanks for the quick fix! I don't remember if I tried this feature in the most recent version, so the bug could have be introduced some time ago.
