### ISSUE TITLE
Unable to read any epub file

### ISSUE THREAD

**Issue by mmjoshi** [koreader/kindlepdfviewer#858]
I was using the v2015.11-stable version. It gave me no problem in reading a large collection of epub files that I have. RecentlyI installed the latest nightly koreader-nightly-20160702 on my Kindle Touch and now I am unable to read ANY epub file :( Is this the problem of the latest nightly or should I stick to the stable release? When will this be fixed?

mj

**Comment by houqp** [comment]
You probably already found it, but please give koreader a try, this project is deprecated :) We should update the readme.

**Comment by mmjoshi** [comment]
In fact I mistakenly posted here! I have now posted to the KOReader forum. 

You are right, you should update the Readme or not allow postings to this forum ☺️
