### ISSUE TITLE
Power slide event capturing

### ISSUE THREAD

**Issue by houqp** [koreader/kindlepdfviewer#86]
I have been playing with this for a whole afternoon and with little progress. :(

Well, some how I did find a ugly way to capture the event:

use `lipc-wait-event  -s 0 com.lab126.powerd goingToScreenSaver,outOfScreenSaver` to capture the event. Then parse the return value and simulate a event to our inputloop.

This does work for the purpose of event capturing, but it can not hold a exclusive access to the event like `EVIOCGRAB` request to ioctl. So the framework will also receive the event and mess things up. If this can be fixed, we can fix bug #85.

Why is the power slide so different from other keys? Which part of the kernel source should I read to find out the reason?

**Comment by dpavlin** [comment]
We could stop framework with `kill -STOP <backquote>cat /var/run/cvm.pid<backquote>` and suspend ourselves with `echo "mem" >/sys/power/state` just like `/etc/init.d/framework` does. Would that help?

**Comment by houqp** [comment]
> We could stop framework with `kill -STOP <backquote>cat /var/run/cvm.pid<backquote>` and suspend ourselves with `echo "mem" >/sys/power/state` just like `/etc/init.d/framework` does. Would that help?

Except from writing `/sys/power/state`, are there anything else the framework does for power management? Maybe we could resume the framework on event occur to let it handle the power management and screen saver drawing?

**Comment by houqp** [comment]
I happened to find the file `drivers/char/luigi_button.c` in the released kernel source. Looks like the driver for the power slider.

Edit:
`cat /proc/misc` does lists the `luigibutton` device.

**Comment by houqp** [comment]
Maybe we can pull events from the power button with ioctl on `/dev/pmic`?

**Comment by hwhw** [comment]
I've changed it a bit now and spawn the new process from within kpdfview via fork(). I reused the code you wrote in slider_watcher, since I really like the hackyness of the event emulation :-)
Worked very well for me. This should probably also be incorporated in other event loops.
While working on the code in input.c, I also enabled "waiting forever" in select().

**Comment by houqp** [comment]
Good job, fork looks cleaner. :)

I am closing this issue for now.
