### ISSUE TITLE
serializing lua state of current document (zoom, pan, etc)

### ISSUE THREAD

**Issue by dpavlin** [koreader/kindlepdfviewer#9]
Serializing state of document would be useful for last read page tracking, but also for different zoom levels or pans for odd/even pages in pdfs which have different layout.

I'm lua newbie and it seems there are a lot of ways to dump serialize lua data, do you have any ideas about that?

**Comment by hwhw** [comment]
Hi,

I didn't yet look into it and don't have very much experience regarding this. Lua doesn't have serialization primitives AFAIK, it is a very tight language with a very small standard library. However, I'll bet that there are serialization libraries readily available.

As for storing serialized state information, I thought about using a sqlite interface for Lua. That's the beauty of having Lua in the middle: We can build upon existing Lua libraries or interfaces for native libraries.

**Comment by dpavlin** [comment]
On Mon, Nov 28, 2011 at 12:56:28PM -0800, HW wrote:

> As for storing serialized state information, I thought about using a sqlite interface for Lua. That's the beauty of having Lua in the middle: We can build upon existing Lua libraries or interfaces for native libraries.

At first sight, using SQLite for storing page meta-data seems like overkill, but if I share my goal of replacing Kindle reader, making annotations and full-text search[1] which comes with SQLite makes a perfect sense.

I think that model of one meta-data file per original document is correct one (like existing Kindle's pdr files for each pdf), so we could create one SQLite database per pdf file which gets filled for full-text search as we go through pages.

1: http://www.sqlite.org/fts3.html

**Comment by hwhw** [comment]
Well, there's full-text, there might be annotations at some point, maybe some fancy "store password" functionality - I've chosen Lua for the ease of prototyping using it, so I though SQLite might roughly follow this line by offering a lot of flexibility.

I concur that metadata per-file is the way to go. Some long-term goal of mine would be to allow the use of crypto-filesystems (via FUSE) to provide some protected document spaces on the device. Having the database right next to the document makes perfect sense then.

I've just integrated building of SQLite into the Makefile.
