### ISSUE TITLE
font handling changed

### ISSUE THREAD

**Issue by hwhw** [koreader/kindlepdfviewer#96]
I just commited a larger patch that introduces a new approach to fonts. I hope I got everything in order. Unfortunately, some local Makefile changes of mine (toolchain settings) got in the mix, so I fixed that on the go and made it more flexible. I hope I haven't broken too much stuff - please tell me if I did...

**Comment by houqp** [comment]
So far so good :)

Will be better if you put the commit log (538940baf78527137a1151f1408140e3d1b53932) in document.

**Comment by dpavlin** [comment]
With invalid font configuration (e.g. old fonts directory which doesn't point to mupdf/fonts and doesn't have all fonts referenced in code) reader segfaults. It's not show-stopper, just a quick note.

I like new build system, btw :-)

**Comment by hwhw** [comment]
Maybe we should switch over to using mupdf/fonts instead when creating the customupdate ZIP file?

**Comment by Germanc** [comment]
When launching in emu mode this happen:

#! Font scfont (./fonts/droid/DroidSansMono.ttf) not supported: freetype error
#! Font infont (./fonts/droid/DroidSansMono.ttf) not supported: freetype error
#! Font hpkfont (./fonts/droid/DroidSansMono.ttf) not supported: freetype error
#! Font hfont (./fonts/droid/DroidSans.ttf) not supported: freetype error
#! Font pgfont (./fonts/droid/DroidSans.ttf) not supported: freetype error
Segmentation fault

Is that expected ? I just created and copied the droid fonts in that folder and everything worked, but better tell you just in case.

**Comment by houqp** [comment]
> Maybe we should switch over to using mupdf/fonts instead when creating the customupdate ZIP file?

Or link these fonts in to `./fonts` directory on fetchthirdparty? This can help setup proper emu environment for developers too.

**Comment by hwhw** [comment]
I think we need a meaningful error message for the above error....
That said, linking mupdf/fonts to fonts is already in the Makefile, I think. I switched the variable over that points to the font folder. So it's hitting developers who already have a symlink there and who didn't update it. Hmmmm....

**Comment by houqp** [comment]
Oh, I did not notice that the linking is already here, sorry ;P

Then I am for the meaningful error message.

**Comment by dpavlin** [comment]
I think we can close this one.
